### ISSUE TITLE
[Feature] Making manual tagging more efficient when defining Scene markers

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#1011]
If tags are added to a marker on a scene, please set those same tags to the scene itself.
This avoids a scenario where tagging requires the tagging of the marker _as well as_ duplicating that same tagging effort on the scene itself.

**Current scenario**: Scene Marker is set at 10:15 with a primary tag of "bouncing". User has to then also click on the Edit tab and manually also add in the "Bouncing" tag to the scene

**Ideal scenario**: Scene Marker is set at 10:15 with a primary tag of "bouncing". Tag is added to both the marker and the scene.

Thanks! 🙏

**Comment by WithoutPants** [comment]
If this is added, it needs to be optional.

**Comment by WithoutPants** [comment]
$40 bounty added.

**Comment by gitgiggety** [comment]
I've been thinking about extending the "Tags" filter with choices for where to search for the tag. So that on the scenes list when adding the tag filter you can opt to search for the tag on the scene, and/or a marker and/or a performer. So instead of having two or three tag filters (currently two, one for "Tags" and one for "Performer tags" you add a tag filter and select to search the tag on the scene, or performer, or both (or marker)). My use case for this would be for example hair color tags which can be applied to performers, but mostly is also added to a scene during scraping. So you could then just search for "Blond hair", check scene and performer and you get all scenes where either the scene or one of the performers has that tag.

Would that work for you as well? As you could then search for tag "Bouncing", select scene and scene markers to search for the tag and it would also list all scenes where the tag is (only) applied to a marker.
This would remove the need to duplicate tags, and also prevents you to having to remove tags from the scene when you remove them from the marker. (for example when you later remove the "bouncing" tag from the marker it still will be applied to the scene, while you most likely would want to remove it there as well when no other markers have that tag).

**Comment by WithoutPants** [comment]
I am hoping to meet the requirements of this issue using a plugin mentioned in #1452 rather than extending the core code.

Implementing this feature in the core system is a pretty simple affair, but my main hang up with it is that it adds another configuration key to the list. There may be similar requests for adding tags from performers when adding a performer to a scene - to use a contrived example. Rather than adding configuration flags for all these specific behaviours, I think it's better to defer this behaviour to plugins, to allow users to extend the behaviour of the core system to their liking.

Embedded javascript plugins, and now plugin hooks allows us to add this functionality without polluting the settings pages with niche behaviour flags.

I'm hoping that this will be an acceptable compromise @ALonelyJuicebox 

The implementation of the plugin itself is available as an attachment to #1452

**Comment by ALonelyJuicebox** [comment]
@gitgiggety Hey I actually like that UX change, and it simplifies the dropdown.
If I understand you correctly, are you considering something like this? (Very rough edit just for visualization purposes)
![image](https://user-images.githubusercontent.com/76471868/120060077-703a3180-c00a-11eb-8c25-b455a78eace4.png)

@WithoutPants Agreed. I'm a hobby dev at best-- whatever sounds more reasonable to implement. Agreed with your secondary example as it's another thing I'd actually love to see added. 😅
More power to the plugin option if that's the best path forward!

**Comment by gitgiggety** [comment]
> If I understand you correctly, are you considering something like this? (Very rough edit just for visualization purposes).

Correct, that's what I'm thinking about adding. Obviously with Scenes, Performers, and Markers being checkboxes which you can enable on an individual basis.
