### ISSUE TITLE
[Feature] Selective Clean

### ISSUE THREAD

**Issue by SpedNSFW** [stashapp/stash#1074]
Similar to Selective Scan, but for Cleaning. When you know that the only content that needs cleaning is in a specific directory, going through your entire database can be a little time consuming, especially if it's rather large. It gets to be rather unnecessary and I would rather it didn't occur.

**Comment by rg9400** [comment]
In addition to this, it would be nice to be able to run Clean while doing a Selective Scan itself, like it allows you to do with Generate Previews. Ideally, clean would run first before scan, then generate, i.e. Clean -> Scan -> Generate. This helps if you are doing file upgrades, so a deletion of the old file at lower resolution and scanning a new file at higher resolution. Stash does not pick  these up as renames where it just updates the path because it is actually a delete + create with two distinct files.

**Comment by WithoutPants** [comment]
> In addition to this, it would be nice to be able to run Clean while doing a Selective Scan itself, like it allows you to do with Generate Previews. Ideally, clean would run first before scan, then generate, i.e. Clean -> Scan -> Generate. This helps if you are doing file upgrades, so a deletion of the old file at lower resolution and scanning a new file at higher resolution. Stash does not pick these up as renames where it just updates the path because it is actually a delete + create with two distinct files.

This is covered by #1095. A small note however - clean would best be done after scan, otherwise a file rename would cause metadata to be lost (since the old filename no longer exists and the scene will be deleted during clean, then re-created during scan). In place file changes should be detected by scan now since it checks by mod date of the file.
