### ISSUE TITLE
[Feature] Parent studios

### ISSUE THREAD

**Issue by OffspringFan88** [stashapp/stash#115]
Is there a way currently to add images for series e.g Big Tits at Work and add this under a Studio? At the moment I'm adding the series under studio with the logo or adding them as Tags.

**Comment by StashAppDev** [comment]
Right now images (galleries) are tied to scenes since a lot of paid sites have both a video and a gallery of images for any particular scene.  Are you saying that you want to see all of the galleries from a studio, rather than just the scene?

**Comment by OffspringFan88** [comment]
No what I mean is can you have another tab like the Studio one and have it as Series.

Sort of like a sub category of the studio, so for instance Brazzers have a lot of different series under their banner, so you could have Brazzers as the studio and then link the different series under their banner.

At the minute I've had to do all the series in Studio to due to them being so many.

![image](https://user-images.githubusercontent.com/54474989/63640800-b8d9f380-c69c-11e9-8fa2-916be716b388.png)

**Comment by OffspringFan88** [comment]
Yes! @echo6ix thats exactly what I meant! Thank you for clarifying. 

Would love this to be added down the line!

Do we have an idea on when this would be included in a future release?

**Comment by echo6ix** [comment]
@OffspringFan88, no idea when this would be included other than when the developer or contributors get to it. I can start mocking up some concepts of how this would change the studio list.

It might be helpful to change the topic to something more accurate of what the dev already acknowledged to be a useful feature request, like **[Request] Parent Studios**, just so it matches the roadmap description.

**Comment by echo6ix** [comment]
I made this UI "studio list" concept pretty hastily. Some logos and thumbnails are recycled throughout the concepts even where not relevant, don't read into it other than laziness. I suppose these are also related to #108 

**Channels, probably a more suitable term to use than _studios_**

One thing I realized when creating these concepts is referring to this section as studios isn't representative of the content. I would recommend renaming the studio section to _channels_ because we're not necessarily creating studios specifically. A channel is broader term than studio and it can be representative of whatever the user wants. We can think of channels as having one or two parts: (a) the parent channel, and (b) the option to hold sub-channels.

**Channel/"studio" list page**

![studio concept](https://user-images.githubusercontent.com/37937507/63905857-94a34d00-c9e3-11e9-8de0-82a1cd8a699c.png)

Both parent and sub-channels are displayed as thumbnail cards in a grid view. This concept shows how the user can filter between parent and sub-channels using the filter option.

**A. Parent channel**
The parent channel would be like the studio name, network name, an amateur web site, production company, distributor, platform name, etc. The parent channel is the top of the channel hierarchy, and obviously there can only be one parent channel per channel.

![parent channel page](https://user-images.githubusercontent.com/37937507/63905984-01b6e280-c9e4-11e9-833e-c1f937bcc114.png)

**B. Sub-channels**
Sub-channels are a division of the parent channels, and they can only be assigned to one parent channel. They would be the equivalent of a series produced by a network, or the name of an amateur studio (content creator) hosted on a platform. For example, ManyVids is the platform (parent channel), and the amateur studio name is the sub-channel.

![subchannel page detail](https://user-images.githubusercontent.com/37937507/63905998-0c717780-c9e4-11e9-9a5c-9c0a8e561db6.png)

**Channel and sub-channel creation, editing, and deletion**

- When making a channel the user can select the type of channel: `parent channel` or `sub channel`.
- If sub-channel type is selected, the user has the option to assign it to a list of the available parent channels from the database. They can always go back and change these settings by reassigning to a different parent channel, or by changing their channel type to parent.
- If a user wants to delete a channel they should be prompted with a modal window informing them the parent channel has sub-channels attached to it.
- If they choose to continue the parent and all assigned sub-channels will be deleted.

![subchannel page edit](https://user-images.githubusercontent.com/37937507/63906002-109d9500-c9e4-11e9-8e73-3e7de664e910.png)

Note: These concepts are obviously made for a desktop viewport. Some aspects would need to be revised for a mobile viewport.

**Comment by OffspringFan88** [comment]
Yes!!

This is exactly what I’d love to see! Great concept even if you made it quickly it still looks great!!

**Comment by echo6ix** [comment]
I didn't fully explain the concept of the _channel tags_ in the attached image. The channel tags should just be a list of the top tags used (by count) associated with the scenes that are assigned to said channel.

![channel tags](https://user-images.githubusercontent.com/37937507/63980340-447ec600-ca89-11e9-9218-e43c414ff518.png)

When I first created it I was thinking of displaying the proposed "studio tags" that would be used for the auto file based tagging feature, but the aforementioned idea is better.

**Comment by echo6ix** [comment]
Here's another updated version of a channel page, specifically a "sub-channel."

 ![channel page 1](https://user-images.githubusercontent.com/37937507/63984860-1904d700-ca9b-11e9-8fab-bfdce120c1d9.png)

Stuff I added in this concept:

**Country flag**
- Users can select a country for a channel from a drop-down list in the channel edit panel.
- The country flag is displayed in the attached image, and clicking it would take you to the channel list grid view page, and automatically filter all channels by country. This could be useful for sorting foreign channels.

**Performers panel**
This displays all the performers in any scenes associated with a channel. I don't know how this wasn't on my original concept. It's basically the equivalent of the "models page" on any porn web site. Clicking a performer would take you to all their scenes assigned to the channel.

**Comment by OffspringFan88** [comment]
Loving all of this @echo6ix.

This is pretty much what I've been looking for as a lot of my collection includes scenes belonging different series.

**Comment by Leopere** [comment]
This is a great issue!

**Comment by GernBlanston12** [comment]
Nice!  Don't forget to extend the concept to vanilla tags, like "Lingerie" with sub-tag "thong", that would be cool.

**Comment by echo6ix** [comment]
> Nice! Don't forget to extend the concept to vanilla tags, like "Lingerie" with sub-tag "thong", that would be cool.

@GernBlanston12 This is discussed in the road map, but states the concept needs to be fleshed out. Do you want me to start a new thread for it?

**Comment by GernBlanston12** [comment]
Thanks, I was just thinking the two issues would have a lot of common architecture in their solves, whatever that turns out to be. With regard to inherited tags, for example, if I tag anything "thong", it would also tag the video with "lingerie" (i.e., "thong" is a sub-category of "lingerie" if I set it up that way).  This also works well for sub-sites to internet studios ("Future Darkly" is sub of studio tag "Pure Taboo") as well as in the future perhaps accounting for series-to-studio relationships for DVDs.  Parent tags should be accessible by regular means (I should still be able to tag a video with studio Pure Taboo, without having it show up with Future Darkly, but whenever I tag it with Future Darkly, it should add tag Pure Taboo. It's an "All beagles are dogs, not all dogs are beagles" sort of thing)

**Comment by echo6ix** [comment]
On Discord there was brief discussion about the concept of a "DVD object" or "Movie Collection" that would be a compilation of individual scenes that belonged to a movie.

I think this might integrate seamlessly with the above _channel/sub-channel_ paradigm I've proposed to supersede and expand upon the current _studio_ functionality. For example,

| Channel | Sub-channel |
| --- | --- |
| {any name you want here} | {any sub-channel name here or can be left blank} |
| Movies | Debbie Does Dallas |
| Movies | The Fashionistas |
| Movies | Justice League XXX An Axel Braun Parody |
| Brazzers | Mom's In Control |
| Brazzers | Pornstars Like It Big |
| PornHub | {blank / no sub-channels} |
| ManyVids | _{Performer channel name here}_ |
| Reality Kings | Reckless In Miami |
| Reality Kings | Moms Bang Teens |

The only exception is the _Movies_ channel would need to be hard-coded as a channel, and similar to how a gallery can be selected on any scene from a drop down form, a movie could be selected from a drop down form to compile a set of scenes that make the movie.

**Comment by echo6ix** [comment]
I'm not sure I've done a good job articulating what channels would be, but I think it would probably be best to think of them as "playlists" or "smart playlists" that can contain "folders" in hierarchies. It might be easier to visualize how this would work using a treeview.

```
Channels
├── Studios
│   ├── Brazzers
         ├── MGB
│   └── Bang Bros
├── Amateurs
│   ├── collection name
│   ├── collection name
│   └── collection name
├── DVDs
│   ├── Title
│   ├── Title 2
│   └── Title 3
├── Amateur

```
This paradigm lets the end user precisely organize their content subjectively to their needs, rather than locking everyone into a rigid "studios" only page, "dvd" only page, etc. -- which in my humble opinion clutters the UI experience with a rigid organizational paradigm the user may not even use.

In the above treeview example, all those objects are terms the end-user would have created and organized. Another user may decide they don't won't so many nested studios and would have them all displayed under the umbrella of a primary channel called "Studios", "Networks", or whatever.

These channels could have attributes, such as an associated avatar(s), URL, tags, etc.

Where an end-user now selections a studio to associate with a scene, they would instead selection any of the available channels with a few exceptions, such as channels that act as "smart playlists", where a smart playlist would basically be a short-cut of a [custom query using something like query-syntax](https://github.com/stashapp/stash/issues/185) from #185 

I hope that clarifies my channel concept, which is basically playlists/smart-playlists.

**Comment by WithoutPants** [comment]
Would a scene still have a single channel/studio under this paradigm?

**Comment by echo6ix** [comment]
@WithoutPants That's a good question and it demonstrates that my channels suggestion was evolving more into a multi-node playlist paradigm and getting away from simply assigning a scene to a studio or it's subsidiary studio.

Everything I've said on this thread after this [post](https://github.com/stashapp/stash/issues/115#issuecomment-526409199) is more about playlists than studios and if it's possible, I would split this thread starting [here](https://github.com/stashapp/stash/issues/115#issuecomment-559706125) into a feature for multi-node playlists.

My idea was getting too convoluted and it's clear Stash needs a dedicated section for users to manage and browse networks, platforms, studios, websites, and all their subsidiary nodes.

To answer the question: (1) A scene should be able to belong to more than one playlist. (2) A scene typically belongs to one studio node, though I think there are exceptions with video clips or movies having more than one studio. But that exception to the rule doesn't change anything about studio management and presentation.
