### ISSUE TITLE
[Feature] Better handling for aliases (especially in scene details search)

### ISSUE THREAD

**Issue by MartinWe13** [stashapp/stash#1162]
**Is your feature request related to a problem? Please describe.**
Many performers sometimes have a lot of nicknames, which makes clean maintenance very cumbersome in the long run. Especially if the "right" names don't want to come to mind when entering them in the scene details.

**Describe the solution you'd like**
First of all, a clean database structure for aliases is necessary. I thought here of an input of the actor details like for tags:

![Aliases1](https://i.ibb.co/tJmTkKn/aliases1.jpg)

![Aliases2](https://i.ibb.co/FW0d4F6/aliases2.jpg)

When entering the names in the details for a scene, the aliases should now also be searched. If a matching alias is displayed for the current input, the regular name can be displayed together with the found alias (only the matching one, not all) and made available for selection:

![Aliase in scene details](https://i.ibb.co/SQh1ngG/aliases3.jpg)

**Additional context**
I think it adds significant value along with a better performer search ([see here](https://github.com/stashapp/stash/issues/1114))....

**Comment by echo6ix** [comment]
In your concept showing a match-as-you-type query, I presume an alias is being queried, and your concept has the matches displaying the primary performer name with the matched alias in parentheses. I think that would be confusing from a ux perspective, and maybe it should show matched aliases in white and the associated primary performer name in parentheses. I just point that out because I think it's important to give the user visually relevant matches to the pattern being queried.

Example:

- Pattern queried: `John`

- Returned matches:
  - John (Bill Wilson) <--- Alias matched, primary name in parentheses
  - John Brown
  - John Doe
  - John Smith
  - Johnny (Tom Anderson)  <--- Alias matched, primary name in parentheses

**Comment by MartinWe13** [comment]
Thanks echo6ix. It’s also nice(er). I think for the first part it’s important to have any lookup for aliases...

**Comment by stg-trainer-annon** [comment]
This seems to be similar to #422

**Comment by MartinWe13** [comment]
Push :-)
