### ISSUE TITLE
Improvement- Mobile: Video preview plays too early on entry

### ISSUE THREAD

**Issue by timmehtimtims** [stashapp/stash#1386]
Not a feature or a bug perse but an improvement request:

When browsing on mobile I noticed that the video preview begins when it enters the viewable area, and then stops when the next one enters, that one then starts playing the preview and so on…
It feels odd because often the second video will be barely/partially visible when it starts playing and the first preview is still in the middle of the screen and has stopped playing. This is especially noticeable on larger screen mobiles where portions of 3 videos will be in the viewing area at any one time.

It would be great to have some padding around the timing of when the preview videos start to play on mobile eg: when at least 50% - 75% or maybe even 100% of the video becomes visible. That way the preview of the video that is in the middle of the screen is playing. 

iOS chrome .

**Comment by JacobNoerhave** [comment]
I assume you are using stash version 0.6 and are viewing the scene in the grid view (As i have experienced the same thing). In the current developer release / next release (0.7) the scenario you describe does not seem to be there anymore. You can now active the preview manually by holding your finger slightly longer on a scene card. This change is likely due to #1340.

**Comment by SuperEllipsis** [comment]
I assume you are using stash version 0.6 and are viewing the scene in the grid view (As i have experienced the same thing). In the current developer release / next release (0.7) the scenario you describe does not seem to be there anymore. You can now active the preview manually by holding your finger slightly longer on a scene card. This change is likely due to #1340.
