### ISSUE TITLE
[Bug Report] Auto Tag not matching pattern when target contains the pattern with white space removed

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#1450]
**Describe the bug**
When auto tagging from the task page or Studio pages, patterns are not being matched if the target has spaces stripped from the pattern. However, it does work as expected when auto tagging is initiated from the Performers and Tags pages respectively. 

Example:
Pattern = 'String string'
Target = 'StringString.jpg`

- Auto Tag will **not** find the Pattern in the Target if auto tagging is initiated from the Task page or Studio sub pages
- Auto Tag will find the Pattern in the Target if auto tagging is initiated from the Performers or Tags sub pages

**Expected behavior**
I am assuming the expected behaviour is to match Patterns even when the Target has white space removed from the Pattern.

**Stash Version: (from Settings -> About):**
Version: | v0.7.0-35-gc5fed1bb
Build hash: | c5fed1bb
Build time: | 2021-05-27 23:04:39

**Additional context**
This behaviour or at least portions of this behaviour have existed for about a month at least.

**Comment by WithoutPants** [comment]
Confirmed. This is occurring due to how stash queries for performers/studios/tags when tagging from scene/image/gallery. The performer query divides the file path by it's separators: `foo bar.baz.mp4` becomes `[foo, bar, baz]`, and it queries for performers that match `%foo%`, `%bar%`, `%baz%`. Unfortunately, this does not cover with the file is named `foobar.mp4` and the performer is `foo bar`. I'll need to rethink the performer/etc query once again.

**Comment by GsMumbo** [comment]
Question - When searching or filtering in a collection, searching for “Firstname Lastname” is treated as an OR search instead of an AND. Is that due to the same reason mentioned above (how the query is made)?

**Comment by WithoutPants** [comment]
That is unrelated. The auto-tagger doesn't use the same method of querying. The text-field querying uses OR by design - I believe there are one or more issues related to changing how that works.
