### ISSUE TITLE
[Bug Report] svg logos scale really small

### ISSUE THREAD

**Issue by CuddleBear92** [stashapp/stash#1472]
Noticed a svg logos that overlay scenes does scale really badly. 
It scales into a very small size, hard to really read it cleanly and clearly.
svg files are vectors so i would guess it would scale to any size the user wants.
maybe the scaling should take up a set % of width of the thumbnail or studios should have a setting you can set per studio.

![image](https://user-images.githubusercontent.com/8496821/120519972-8ada2500-c3d3-11eb-9a7f-4c8c61b2c625.png)
![image](https://user-images.githubusercontent.com/8496821/120520089-b1985b80-c3d3-11eb-806b-9f0762df132b.png)

source logo:
<https://www.eroticax.com/m/cmxui2ekv9wso044/EroticaX-GREY-2019Logo.svg>

**Comment by CosimoVestri** [comment]
I found that this issue doesn't occur with all .SVG files. I noticed this problem when I was setting up my _stash_ library (early in 2021, I think).

When I was collecting .SVG files from the studios and vectorizing logos that weren't available as vectors, I noticed that scaling, especially on the overlays for scenes, like this issue shows, wasn't always consistent.

At the time, I was using some combination of Adobe Illustrator, Affinity Designer (I switched to this after I discontinued my CC subscription after my discount ended), Vector Magic (I used the desktop version, which despite the age and lack of updates does a good job. An associate of mine bought it a long time ago and we have some software on a shared remote machine. If it was still being developed, I'd say it might almost be worth the $300 for some use cases; however, it isn't.), and Inkscape.

If I recall, opening the file with Inkscape and changing the document or art board size to match artwork bounds solved the issue. I never thought to file a bug report since I believed it was my error, so I missed this issue at the time.

I'll likely have copies of the files archived somewhere. Probably on "cold" storage, on tape. I'll try retrieving it soon. I'll compare the files to see what's different and share my findings. That might be useful in fixing this.
