### ISSUE TITLE
[RFC] Reducing the allocated size for generated content

### ISSUE THREAD

**Issue by puzyt** [stashapp/stash#1490]
*### Scope*
The way current generated thumbnails are stored takes a lot of space on disk because of the allocated space the individual files need.

As a reference I have around 106 Gb of media content, across 500+ scenes and 4000+ images, and the generated content for that is around 7,4 Gb, of which 4,3 Gb is allocated space on disk for thumbnails, the actual size of the thumbnails being only around 160 Mb.

The same problem occurs with other generated content, but at a lower size to allocated size ratio.

The generated folder size is presented below, as viewed on TreeSize.

![1](https://user-images.githubusercontent.com/85498792/121026441-0ce49800-c79e-11eb-82f7-717200c8e5f6.png)

My current setup runs as a docker container on a Odroid HC2, with the files being stored on a EXT4 partition, so maybe this problem is filesystem dependent.

A solution could be to store these files in a zip file, the same way you can do with an image gallery in a cbz file, but my input on the actual coding side is limited.

**Comment by bnkai** [comment]
The above issue is not related to stash.
You are using a fs that is not tuned  for a lot of small files. From the image above it seems that you have setup the partition with a block size of 1MB (default for most fs is 4KB). I would double check to see if something went wrong during the setup of that partition ( `tune2fs -l /dev/sdXX` for example ) or with the mount options. 
As a reference i have `41112 items, totalling 803 MB` in thumbnails and `921MB` are allocated for them. That is with the default Block Size: 4096 in ext4.
I would either move the generated folder into a different disk/partition with a proper block size (check the bs first) or reformat the partition if the issue was indeed from it.

**Comment by puzyt** [comment]
I've checked and it seems like the default allocated size on smb shares is 1 Mb, but the actual block size on the drive is 4K, so i guess the 1 Mb size is only being reported through smb and not actually being implemented in the fs.

Thanks for the trouble.
