### ISSUE TITLE
[Bug Report] Filter for 'Duration Range' in Scenes

### ISSUE THREAD

**Issue by ghfsa** [stashapp/stash#1504]
**Is your feature request related to a problem? Please describe.**
Can choose duration to be less than or greater than a specific time, but unable to set duration, say between 30:00 - 50:00. Tried to use two filters: Duration greater than 30:00 & Duration less than 50:00, but couldn't get it to work.
(If one can indeed set a range, can anyone point it out for me?)
Thanks

**Comment by ALonelyJuicebox** [comment]
Creating those two filters works fine, but it's likely ORing the two duration queries instead of AND-- which would explain the results.
I'd maybe change this to a bug rather than a feature
![dfgdfgdd](https://user-images.githubusercontent.com/76471868/122548481-457a4200-cfe6-11eb-94b3-4a2170705283.JPG)

**Comment by ghfsa** [comment]
> Creating those two filters works fine, but it's likely ORing the two duration queries instead of AND-- which would explain the results.
> I'd maybe change this to a bug rather than a feature
Thanks! Changed it.
