### ISSUE TITLE
[Feature] Automatically tag all scenes by the name of the folder

### ISSUE THREAD

**Issue by ghost** [stashapp/stash#1566]
**Is your feature request related to a problem? Please describe.**
It would be great if we could have all scenes tagged by the name of the folder they're in.

**Describe the solution you'd like**
In the "Library" task section, have a new checkbox like "Tag with directory name" which, when enabled, will automatically add the folder name for each scene as a tag.

**Describe alternatives you've considered**
Have a totally separate task that will perform this operation across all the library.

**Additional context**
I have all my videos organised by performer name, some by studios. It would be great to take advantage of this existing information without having to manually set it for each scene.

**Comment by gkddev** [comment]
Yeah It would be great to have such feature. Even I have organized local contents. But after scanning on stash for the first time , I realized I did many mistakes while organizing data locally , like file duplication or misplaced videos  because many performers first name or last name matches with other. So while organizing files locally it can cause error. So better take all the information from metadata of a file or filename rather than folder name.


Truly speaking , stash is made to decrease pressure or load on us , to save time. Even after using stash if we have to do all the work then why use stash?

but your feature will be helpful if someone has files with filenames not matching with content like "111Xyz..mp4" or  "zzz12zz.mp4". So +1 vote from my side.

**Comment by ALonelyJuicebox** [comment]
Just my opinion but I feel like this might be best for a plugin but not as an addition to core stash. 
It's awfully niche imo.

**Comment by melavas** [comment]
@ALonelyJuicebox why the thumbs down? If we think this is a good feature, to me, it doesn't matter if it's a plugin or implemented in core, that's an implementation detail, isn't it?

**Comment by kermieisinthehouse** [comment]
This is exactly what autotag is for. Simply create (or scrape) the performers, tags, and studios in stash, and then run an auto-tag task. The directory name will be scanned for names of performers, studios, and tags, and all of the content inside will be associated to it.
