### ISSUE TITLE
[Bug Report] Scenes: Is Missing "date" breaks filter

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#1571]
**Describe the bug**
When applying the "Is Missing: date" filter to scenes, the filter seems to break.

**To Reproduce**
Go to a performer -> scenes tab -> apply "Is Missing date" filter.

In my experience, the entire filter breaks so it shows scenes from all performers.

**Stash Version: (from Settings -> About):** v0.8

**Comment by gitgiggety** [comment]
@WithoutPants this is due to missing parentheses, as the query is generated as `WHERE (scenes.date IS "" OR scenes.date IS "0001-01-01" AND performers_join.performer_id IN (?)) GROUP BY `. IMO the best fix would be to automatically wrap every clause added with `filterBuilder.addWhere` in parentheses, as they then aren't needed anymore on the callers end. Obviously this would lead to a lot of redundant parentheses but that shouldn't be any problem. Furthermore I think that about every ORM solution I have used, containing a query builder, does do it like that, just wrapping every `*Where()` call in parentheses.

So do you agree with changing `addWhere` instead of just fixing this single code path for "is missing: date"?
