### ISSUE TITLE
Kubernetes \ Rancher Deployment

### ISSUE THREAD

**Issue by matda59** [stashapp/stash#1584]
seem to have an issue getting Stash running in Rancher. it doesn't seem to map the port to the container.  

INFO[2021-07-15 07:29:16] stash is listening on 0.0.0.0:0
INFO[2021-07-15 07:29:16] stash is running at http://localhost:0/

also when i add a blank configuration.yml into .root\ it apply the internal cluster IP in port : section. .. . 

eg) port: tcp://10.43.129.29:9999

**Comment by digitaldensha** [comment]
You can specify the port by adding the following to your deployment environment variables

`
 - name: STASH_PORT
              value: "9999"
`
More options can be find in:
https://github.com/stashapp/stash/blob/16fe21138ffc7ac1d593c115d72dcc3314ca0e17/pkg/manager/config/init.go

It is kind of a patch, instead of fixing the problem. But I haven't get to the bottom of this at the moment.
