### ISSUE TITLE
[Feature] Filtering with Parent/Child Tags

### ISSUE THREAD

**Issue by yoshnopa** [stashapp/stash#1725]
**Is your feature request related to a problem? Please describe.**
The possibility to add Parent and child tags is useful for structuring large amounts of tags, however, without integrating it into the filter options, it remains not really useful, as one can get associated tags, for a selected tag, but no more sophisticated requests.

**Describe the solution you'd like**
There should be filter options that take the parental tags/child tags into account.

- The simplest would be "is missing", parent or children tags.
- Coming after that, children tags/parent tags is/bigger than/smaller than NUMBER.
- Children/parent tags contain certain tag.

Interesting, but far more sophisticated (maybe too much so, I'd say out of the scope of this issue) would be the possibility to add a filter that will be applied to the parent or children. For example, a filter that returns all Tags who have one (or more than, equal, all...) Tag as a children that miss an image. This could be done recursively in theory, which makes it kind of outside of what the current filter system is built for I'd say - still I thought this should be mentioned as a possible idea.

**Comment by gitgiggety** [comment]
> The simplest would be "is missing", parent or children tags.
> Coming after that, children tags/parent tags is/bigger than/smaller than NUMBER.

IIRC @WithoutPants want to drop the "Is missing" filters and replace them with dedicated ones. So in this case it would mean going for "Parent count" and "Sub count" filters which have equals, not equals, less than, bigger than, between and not between. So instead of "Is missing: parents" you use "Parent count: 0"

For all your suggestions the main question (or problem) would be whether this should be recursive or not (/ either be non-recursive, or be non-recursive and have an option to be recursive, the same as tag and studio filters are non-recursive by default).

> For example, a filter that returns all Tags who have one (or more than, equal, all...) Tag as a children that miss an image

I'm guessing that would be:
* "Has parent: X (including grandparents)"
* and "Is missing: image"

Am I correct? So that would be solved by your third request / bullet if it's possible to include grandparents / grandchildren as well.

"Has parent" and "Has sub" could then support "Includes all", "Includes" and "Excludes" as well.

So it boils down to:
* "Has parent" with includes all/includes/excludes and having a checkbox to include grandparents as well
* "Parent count" with the default numeric options for equals/not equals/less than/greater than/between/not between, (including a checkbox to count grandparents as well? Not sure if that makes sense. And it might open up the idea to only count the "roots", so if you have tag A with B and C as parents and B having D and E as parent that it only counts the root tags being D, E and C (thus ignoring B as it isn't a root)).
* "Has sub" => same as "Has parents" but then going down instead of up
* "Sub count" => same as "Parent count" but once again going down instead of up

**Comment by yoshnopa** [comment]
@gitgiggety First thank you for breaking it down. About the bullet points, your absolutely right and its probably easier to understand that way, also the option to include grandparents and subs is an important adding I haven't thought of. 
If "is missing" will be deprecated, then of course it doesn't make sense to implement it here, as you said, it can be substituted with the count being zero.

> I'm guessing that would be:
>
>    - "Has parent: X (including grandparents)"
>    - and "Is missing: image"
>
>Am I correct? So that would be solved by your third request / bullet if it's possible to include grandparents / grandchildren >as well.

There seems to be a misunderstanding here however that I want to break down. Like I said, I'm not really into adding such a feature, I just wanted to add it here for mapping out the complete theoretical possibilities of the filter. 
Assume we have a Tag A with Subtag B, the Filter I lined out as an example would return A when B has no Image set. 
So what I was thinking was: Having a way to filter not only by the qualities of the Tag that should be returned, but also by the qualities that this Tag has as Sub/Parent. 
For example, this could be used for returning all Parent Tags that have Subtags which are used on Galleries (Gallery Count >0). This would not be possible with whats outlined in the bullet points, as you could search for all Tags that have Gallery Count > 0 and a Parent tag, but you cannot return these specific Parent Tags, just these Subtags.

I hope this was more clear.

**Comment by gitgiggety** [comment]
> There seems to be a misunderstanding here however that I want to break down.
> I hope this was more clear.

Yes and yes :)

This would mean having some form of dedicated filter where you can filter based on the properties of the parent or subtags. So you can say "Where subtags have: is missing image", or instead of "is missing" any filter you can apply to tags. While technically possible that would be hard to add to the UI as well. (Case in point: I've got the changes lined up to filter scenes / images / galleries based on performer properties. This so you can go for "scenes where all performers have black hair" or "any performer is between 20 and 25 years old (in the scene)", or "no performer has blue eyes". But I've still got absolutely no idea how to add this to the UI. While the API is already finished). And the same problem would apply to your request. After you select Add filter => "Where subtags" you want to be able to apply any filter once more, but specific for this "subtags have", which would mean having some nested "Add filter" dialog which would result in a terrible user experience (in addition to technical difficulties).

**Comment by yoshnopa** [comment]
Ok, in that case you can omit this from the issue. I already thought that this would be difficult to implement, I just wanted to make sure that its mentioned as a possibility in case its easier than I suspect or if somebody else got an idea how to do it. 
With that said, I think we can limit this issue to the bulletpoints presented by @gitgiggety
