### ISSUE TITLE
Scraping scene data from websites

### ISSUE THREAD

**Issue by ueaslsef** [stashapp/stash#173]
Scenes have an url attribute. Why don't offer a scrape button alongside it if a scraper exists?

E.g. a scraper for the vixen network could look like this: https://gist.github.com/ueaslsef/23bc22cfc42e7d18d7f2392a46782444.

Designwise: As soon as an url is entered whose hostname is found in a scraper list, a button "fill metadata from source website" could be shown.

I would suppose that it does not overwrite current values but instead simply appends the scraped data to the current field to avoid accidential deletion.

**Comment by Leopere** [comment]
Scrapers would be really useful I wonder if this could be a thing that could be added in some kind of modular way such that it won't break the application when this function stops working for some reason or another but also works in a way so that people can add their own fairly trivially in the future.

**Comment by ueaslsef** [comment]
Suggestion:
Before the button is shown, the scraper already tries to fetch the scenes metadata. Only if it succeedes, it shows the button to enter it.

**Comment by Leopere** [comment]
Maybe don't hide buttons but shade it out

**Comment by WithoutPants** [comment]
I'll be looking into this when I look at the metadata server integration. 

Definitely prefer a plugin/script style system so that we don't need a new binary when scrapers are updated.

**Comment by Leopere** [comment]
We've effectively decided that we're going to aim for using our own API in the long run which will poll other scraper API's potentially in itself.  

That said if people feel like our system is not good or as fast on the feature uptake perhaps we should aim for maybe planning for a plugins system as @WithoutPants said.

**Comment by BonerFide** [comment]
I think any scraper based effort that relies on a specific someone doing anything is going to fall over long term. 
Rather than making an API I'd probably rather an API format defined, and so people can contribute a scraper on a per-studio basis if necessary. Then just a spot to configure in the app 'get data for this studio from this url'.
You can default that to any API you write, but it means people can write and share their own scrapers or data sources for other brands.
Ideally I'd like to be able to write a scraper that can get one, more or all of date/filename/filesize/length/[performers]/studio/scene id/url at it, and be able to return the metadata.

Eg, often just filename is enough to extract enough data to match it to a scene if you have the full site's data in a DB somewhere. Failing that, being able to two step match filename > performer + studio + date will almost always give a unique match.

**Comment by Leopere** [comment]
@BonerFide we're going to get enough data from the Filenames. However, parsing them can be a nightmare and ensuring that it's precisely what the metadata is for will be up to [Stash-Box](https://github.com/stashapp/stash-box) hopefully we can finalize and deploy a testing instance or two soon.  Scrapers will likely hook into Stash-Box's API and dump information into that which will then be interpreted by any clients including the Stash app itself.

**Comment by WithoutPants** [comment]
This is basically resolved with #236 and its refinements (#256, #285) and I think it can be closed.
