### ISSUE TITLE
[Bug Report] Tag Hierarchy loop detection is bugged

### ISSUE THREAD

**Issue by kermieisinthehouse** [stashapp/stash#1754]
**Describe the bug**
The loop detection doesn't allow you to add some sub-tags, when they are valid.

**To Reproduce**
1. Create four tags, A,B,C,D
2. Under A, list B and C as sub-tags.
3. Under D, list B as a sub-tag, and save.
4. Under D, attempt to list C as a sub-tag.
5. The operation fails with "Cannot apply tag "C" as it is linked to "A" which already is a child"

**Stash Version: (from Settings -> About):**
Develop branch after 0.9.0

@gitgiggety

**Comment by gitgiggety** [comment]
If I understand you correctly you end up with `A <- C`, + `A <- B <- D <- C`, correct? In that case the error fact there is an error is correct, although the message should be "already is a parent". Because when applying this `C` would thus have `A` as parent twice, once directly and once via `D -> B`. And I'm guessing that if you try to edit `C` and set `A` and `D` as parent it will be more clear what's going on. (or at least state "parent" instead of child)

_But_ this limitation shouldn't be necessary. And in case there is a valid use case to allow it it could be removed anyway.

**Comment by kermieisinthehouse** [comment]
Sorry, there seems to be a misunderstanding. The hierarchy is only one layer deep. I created this structure earlier in the history of the patch, so it used to be possible, but now I cannot modify it without it throwing errors, or recreate it. Here's a diagram and a usecase:

![Screenshot_20210921-231008_1](https://user-images.githubusercontent.com/84814418/134291993-bdd2dde9-1697-4600-b915-88af0b79b96d.jpg)

Reproduction steps, same as above:
![Screenshot_20210921-231413_1_1](https://user-images.githubusercontent.com/84814418/134292535-9efb11ce-3df1-4c1d-974c-97a4bd091cda.jpg)
![Screenshot_20210921-231439_1](https://user-images.githubusercontent.com/84814418/134292551-0a6ea8da-daa0-4690-84be-6834a122e473.jpg)
![Screenshot_20210921-231432_1](https://user-images.githubusercontent.com/84814418/134292558-420e5e2b-a1b4-489d-a915-ee50a170c40f.jpg)

**Comment by gitgiggety** [comment]
Sorry, you're right, I did misread but the image clears it up.

The error indeed is very strange. Although could be explained by the fact that validation of the hierarchy does go both up and down. So it does check B and sees A as parent, so it "assumes" that A is kind of a subtag of D as well. When then checking C it once again sees A and yields the error because it already is applied as some form of child.

And as your use case does seem valid I think this constraint should be removed. Validating it is to hard while I don't believe there is a actual reason to disallow it. The only valid constraint would be "you may not create a loop" (i.e.: applying the same tag as parent and child, either directly or indirectly).

@WithoutPants any objections for removing the constraint that a single tag may only be applied once through a hierarchy? As I first didn't create this constraint and only added it after you asked a question about it :)

**Comment by gitgiggety** [comment]
Hmm, there might be an easy fix for this after all? I guess that the query which collects the parents & children can get the depth as well. And this recursive query could / should stop at a depth of 0.

So in this example when adding B & C to D it would put B & C on depth -1 (starting level 0 - 1), when going up again A would get level 0 (level of child + 1). So depth 0 then means it is on the same depth as the starting tag (D) so there shouldn't be any issues with recursion or same parent (or child) being applied multiple times.

**Comment by gitgiggety** [comment]
It seems like that solution might work. I just pushed a branch for this, but still need to do a lot more testing if all other scenarios work (/result in an error when expected).

The branch can be found here: https://github.com/gitgiggety/stash/tree/tag-hierarchy-validation-fix So if you can please test it before I will create a PR for it.

**Comment by kermieisinthehouse** [comment]
Tested, this works. I tried a few obviously invalid loops and they didn't work, I think this is safe

**Comment by gitgiggety** [comment]
On this branch I can use your diagram as starting point, but add A as parent of D. Afterwards saving others (A, B and C) does fail, but when editing D it thus can be saved just fine. So that at least is a bug with this change.
