### ISSUE TITLE
[Bug Report] Empty the search when applying popover filter

### ISSUE THREAD

**Issue by Belleyy** [stashapp/stash#1795]
**Describe the bug**
When you apply a filter the search query is still set.

**To Reproduce**
1. Go to Scene
2. Search `a` (or anything)
3. Apply a popover filter (tag/perf)
4. The search still contain the word. (`a`)

**Expected behavior**
The search to be reset.

**Stash Version: (from Settings -> About):**

<html><body>

Version: | v0.9.0-78-ga5ca8fc6
-- | --
Build hash: | a5ca8fc6
Build time: | 2021-10-03 00:52:10

</body>
</html>

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox 92.0

**Additional context**
I forget to notice that when #1765 was push 😢

**Comment by WithoutPants** [comment]
I pretty strongly disagree with the expected behaviour here. The filter button is supposed to be additive. A very typical personal use case of mine is to enter the search term first, then filter further. Your change would require filtering first, then enter the search term - and if I wanted to filter even further then the search term would be lost.

The only thing I can think of is that you're referring to clicking the popover buttons in the results, in which case the description needs to be clarified.

**Comment by Belleyy** [comment]
> The only thing I can think of is that you're referring to clicking the popover buttons in the results, in which case the description needs to be clarified.

Yea i mostly use the 'card popover button' (sorry for forget to write that). 
So my case is: searching something, then see a performer that i want to see more, so i click on perf name, the filter is applied but my search text is still here.

Other option: 
- maybe just having a button that only appear when you hover the search, that clear the field. So i won't need my keyboard to remove the text.

**Comment by WithoutPants** [comment]
In that case then I agree that it should be clearing the query field when clicking a popover link. It's incorrect behaviour.
