### ISSUE TITLE
[Bug Report] Windows console output loses color when log to file enabled

### ISSUE THREAD

**Issue by 7dJx1qP** [stashapp/stash#1837]
**Describe the bug**
The console output text is colored when there is no log file configured, but once you configure a log file instead of the output being colored, you see the actual color escape characters.

**To Reproduce**
1. Go to Settings -> Configuration and set a log file
2. Restart stash
3. Console output will no longer have color

**Expected behavior**
The output should still be colored. Enabling log to file should not affect the console log display.

**Screenshots**
Without logging to file: ![image](https://user-images.githubusercontent.com/38586902/137006349-e21678ec-12c0-4f34-8090-7ab7585714aa.png)
Logging to file:
![image](https://user-images.githubusercontent.com/38586902/137008137-97e39fc9-8e77-4539-a359-eba07ab4a55b.png)

**Stash Version: (from Settings -> About):**
Version: | v0.10.0
Build hash: | f4b78387

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by SmallCoccinelle** [comment]
I checked, and this doesn't happen on Linux, so it's likely to be Windows-specific. 

The thing to analyze, however, is why this happens. Looking at the code, it seems consistent and always format everything with color escape codes, including the log file output path. And that is indeed what happens in a typical Linux terminal. Since the escape codes are present I'm wondering if there's something going on with that windows terminal and its processing.
