### ISSUE TITLE
[Feature] [css] add unique class names to all scene/performer card elements

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#1870]
**Describe the solution you'd like**
To facilitate better customization of css, give card elements their own class selector names.

- scene cards elements
  - scene title
  - description
  - date

- performer card elements
  - name
    - class name for the performer's name
  - age
    - class name for the integer value of the performer's age
  - age-suffix
    - class name for the string value of the suffix after the performer's age, where the suffix is the string "years old"
  - nationality-flag
    - class name for performer's nationality represented as a flag image
  - nationality-string
    - class name for performer's nationality represented as the 2-letter ISO code
  - gender-icon
    - class name for performer's gender represented as an icon
  
- Etc

Some class names can be hidden by default in the stock CSS, such as `nationality-string`, but at least the option is there for the user to display it.

See below for example

**Comment by echo6ix** [comment]
The age is currently displayed as `<div class="text-muted">34 years old</div>`, specifically:

```
<h5 class="card-section-title flex-aligned">
   <div class="TruncatedText" style="-webkit-line-clamp: 2;">John Doe</div>
</h5>
<div class="text-muted">34 years old</div>

```
And that renders as
```
John Doe
34 years old
```

When we get really precise with the class names, we can do something like this:
```
<div class="performer-card-content">
   <div class="name">John Doe</div>
   <div class="age">27<span class="age-suffix"> years old</span>
    </div>
</div>
```
```
.performer-card-content .name,  .performer-card-content .age { display: inline; }

.performer-card-content .age-suffix { display: none; }

.performer-card-content .age::before {
   content: "(";
}

.performer-card-content .age::after {
   content: ")";
}
```

Which renders to (hopefully if my CSS was correct)

```
John Doe (27)
```

**Comment by WithoutPants** [comment]
Breaking up the age presentation is probably not going to be reasonable.

The age string is generated using internationalisation. The presented string changes depending on whether the performer card is in the context of a scene. When it is outside the context, it generates as `{age} {years_old}`, where `years_old` is an internationalisation handle. When inside the context, it is generated as `{age} {years_old} in this scene`. In some languages, the "in this scene" string is a prefix rather than a suffix.

It ends up being a lot of effort just to enable rather niche styling on sentence elements.
