### ISSUE TITLE
Mobile view for stash UI

### ISSUE THREAD

**Issue by Leopere** [stashapp/stash#192]
Since the majority of internet users are now some variants of Mobile users, we should consider mobile in UI design choices.

* [ ] Responsive
* [ ] infinite scrolling.
* [ ] UX alternatives for the lack of Hover actions in mobile.

**Comment by endqwerty** [comment]
What do you mean by JIT loading when we're using Javascript?

**Comment by Leopere** [comment]
@endqwerty I really always thought that was a web dev term where the website loads and unloads elements as they come in and go out of view.

**Comment by endqwerty** [comment]
I see what you mean now. I don't think jit is the term. I could be wrong, but Google didn't give me anything near that. It was all about JIT compiling.

I do agree that it's a requirement. Needing to manually refresh on each change is annoying. I think it has to do with how the current react app is loading its components right now. There might be an easy fix for it in the current implementation, but probably not worth looking into if it's going to switch to vue.

**Comment by echo6ix** [comment]
The more common term is infinite scrolling.

**Comment by endqwerty** [comment]
@echo6ix I don't think that's what he meant. I took it to mean fixing the issue with how when you modify a performer then go to add them to a video, the performer doesn't exist yet. Since you have to refresh the page to fetch new data. Changing tabs doesn't do it. (that specific example might have been fixed recently, but it's an overall architecture thing that needs to be done for the whole app)

**Comment by Leopere** [comment]
@echo6ix thanks for the correction.

**Comment by StashAppDev** [comment]
We’d likely have to abandon [blueprint](https://blueprintjs.com/) to do this, since the framework is not responsive.  If we remove blueprint then that’s basically a rewrite of the UI.  Shouldn’t be a problem if we switch to Vue from React.  Just need to be sure that we keep mobile in mind from the beginning.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Leopere** [comment]
Well now that you've posted your .mp4 of your iOS app I care a little less about the web UI being responsive but if we can do everything with only one UI that's probably ideal.

**Comment by WithoutPants** [comment]
I'd like to submit that infinite scrolling be an optional thing. For querying purposes, I'd still personally prefer paging and would like that option.

**Comment by endqwerty** [comment]
I personally dislike infinite scrolling, but its definitely an implementable feature. Maybe a 2.0 feature though.

**Comment by Leopere** [comment]
infinite scrolling doesn't have to be a requirement but I wonder why @endqwerty doesn't appreciate it.  Optional as @WithoutPants mentioned sounds good to me, I really like it in case I'm just browsing search results and now that we have that situation where we snap back to page one every time I would kind of prefer one page fits all plus I feel it'll be more efficient on peoples browsers.

**Comment by endqwerty** [comment]
My basic experience with implementing infinite scrolling hasn't been great. Granted libraries could be better now. My knowledge is from a year or so ago. We had problems with making sure infinite scroll adapts to mobile view and a bunch of other implementation hassles.

Also, I don't use infinite scroll. So basically, as a side project I'm probably not going to work on it for a while. I will keep it in mind and make sure the components are structured so that it's implementable.

**Comment by WithoutPants** [comment]
The only thing remaining - now that v2.5 is merged - that is a requirement, is the hover alternative. From memory, I think only the O-Counter button needs to be re-thought on mobile. I don't think there are any other necessary hover buttons in the UI.

**Comment by kermieisinthehouse** [comment]
Closing as we've handled almost all mobile cases, refined with #1721 and #1769
