### ISSUE TITLE
[bug?] Tags disappear in edit panel when saving to new scene

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#195]
Recently on the latest builds, tags that are added to new scenes are disappearing from the tag input box in the edit panel when clicking the save button.

To recreate scenario: Add new scene -> Scene edit panel -> Add tags - > Click the save button

The `updated scene` notification banner appears, then the tags disappear. A page refresh is required to see them in the edit panel.

![insta](https://user-images.githubusercontent.com/37937507/68633260-2a1c8c00-04bf-11ea-947d-9338f9dbadea.gif)

**Comment by WithoutPants** [comment]
I believe this was introduced by #167 

Specifically, the `allTags` query is invalidated, but isn't refetched.

**Comment by StashAppDev** [comment]
I wonder if this is also related to https://github.com/stashapp/stash/issues/194

**Comment by WithoutPants** [comment]
#167 made it so that when a scene was updated, the system would invalidate the cache for a subset of queries. These queries were selected based on what queries could be made stale by a scene mutation. `allTags` is included in this list because the `scene_count` field may change if a scenes tags were updated.

I suspect that the cache invalidation code is going to need further work. I've tried two different fixes:
- remove `allTags` from the invalidated queries, and
- add `refetchQueries: ["AllTagsForFilter"]` to the mutation call

Both fixes work, but both result in the Tags page showing stale data. This is expected with the former method, since the `allTags` query isn't being updated. The latter is most likely because the refetch gets the object fragments, but the full objects are still cached. The invalidate code will need to be extended to remove objects of a given type from the cache as well.  

Another way that we might side-step this issue is to change the tags page to use a `findTags` query like the other pages. That way `findTags` can be added to the queries to invalidate, and `allTags` can be left off.

I'm going to go with the latter fix for this issue for now, but this will result in a regression in the tags page showing stale scene counts. #166 should probably be reopened to track this.
