### ISSUE TITLE
[Feature] Half Stars / 0-10 Rating System

### ISSUE THREAD

**Issue by Emilaia** [stashapp/stash#1962]
I think it's self explanatory, below you'll find an explanation for my reasoning of why this should be a thing.

Your personal collection is very likely centered around the things you like, or as the app name implies, it might have a lot of stuff that you stashed and haven't properly looked at yet. 

If we follow the first line of thought, given it's already centered around things you like, and if you belong to the subset of people that rate entries, then you're very likely to keep rating stuff probably at a 3/5 or above. 
And if we follow the second line of thought, if you were to find something stashed in your collection you're thinking on rating a 1/5, you're also likely thinking about deleting it altogether, that's why the delete option is there after all.

Under this pretense, I don't find it far fetched to assume that the people that rate entries, are likely rarely using the full spectrum of star ratings, keeping it all in the 3/5-5/5 realm, and that in a sense is limiting, because you're likely going to have to blend your "9/10"s and "10/10"s together as 5*. 

Sure, you could adopt a standard for yourself where you keep 1* as a "6/10" and 5* as a "10/10", but it's far from elegant.
Personally, if I'm going to rate things like movies or games, I prefer to have the option to give even half points (i.e. 8.5/10), but quarter stars would look a bit silly, and changing the feature idea to support different systems you can pick from (i.e. 5 stars, 0/10 full numbers, 0/10 with a single decimal) would be quite the step up in work required from half stars.

This might look a bit silly of a request, but if effort was put into the ability to give ratings, might as well go the extra mile.

**Comment by ALonelyJuicebox** [comment]
Supporting different systems also sounds like there would have to be a way to convert from system to system if the user decided they didn't like one rating system or the other if it were to be implemented. That...could get interesting.

If we did this, I'd go so far as to ask for one more option. 
I want the opposite. Just a simple favorite button, no rating. Similar to how performers are handled.

In fact, I've cleverly used CSS to enforce this in my stash today. There's either a selection for 5 stars or nothing else. 
If I didn't like it, it shouldn't be in my Stash. If I like it but I don't love it, it doesn't get 5 stars.

**Comment by WithoutPants** [comment]
> And if we follow the second line of thought, if you were to find something stashed in your collection you're thinking on rating a 1/5, you're also likely thinking about deleting it altogether, that's why the delete option is there after all.

This is not true for datahoarder or archiving types.

> This might look a bit silly of a request, but if effort was put into the ability to give ratings, might as well go the extra mile.

This has come up before (and probably multiple times) on Discord. I'm actually surprised that this is the first time it's been raised here. 

The biggest obstacle to this is that I do not want to force this change on everyone. I personally don't want a half-stars/10 rating system. Optionally allowing a half-star system would be the better option in my opinion, given the UI rating controls we have already - 10 stars would be ungainly, and the alternative is switching to a dropdown list (which is what it was originally). We have rating banners that assume 1-5 as the range, and our UI filter code likewise assumes this. The difficulty is going to be allowing 5 and 10 star systems to co-exist with a single implementation, not to mention a migration path between the two systems.

All this said, I'm not against this in theory, it's just that the implementation is difficult, so it isn't something I've committed to doing myself.

**Comment by 7dJx1qP** [comment]
I think the complexity lies in the front-end UI and supporting different controls for each rating system variation. But for the backend, every rating system variation could just be converted to a 1-100 scale. Each rating system control would take a 1-100 input and have logic to do find the closest representation in its system, so users could freely switch between rating systems without the underlying rating values not needing to be changed.

- thumbs up/down would use 1 or 100 (interpret values 1-50 as down, 51 to 100 as down)
- 1-5 use multiples of 20
- 1-10 use multiples of 10
- 1-100 use the whole range

**Comment by SmallCoccinelle** [comment]
Most rating systems runs on some kind of linear scale: 1-5, 1-7, 1-10, 1-100, with each step being the same amount of relative rating in between them. So the step from 1 to 2 has the same difference as 50 to 51 (assuming 1-100). This means they easy to transform, as it's just a scaling factor.

In Machine Learning, you would typically feature-engineer that scale. You would map it into a float32 on the scale -1 to 1 where 0 is the middle rating. You would bias-correct the rating in the mapping, taking the global average, the item and the person who rated into account. You can also apply normalization in the end: make the distribution center on 0 with a standard deviation of 1.

You do this to make the data easier for the ML system to pick up on, and avoid gradients going haywire too early.

Wrapping this to UX: people use rating systems in different ways (hence the bias correction, to plug that hole), so I would be hesitant to assume people use it the same way. Give a person a tool, and you'd be amazed how they are going to use it for things you never thought of. One important thing with a 10-step-rating system is that the average point is 5.5. And this cannot be chosen. That's why you often see an odd number of options, since it guarantees the indifferent point is in the middle. You could include 0, but that's often reserved for "no rating given yet".

I think if you make changes such as these, you do so decisively. Supporting multiple rating systems is going to be a lot of work, so unless you have someone who really wants to champion such an implementation, I would personally stick to one system. The systems are also going to permeate the code one way or the other, even with some kind of standard scaling. In a search box, writing `rating:4` would make sense. Writing `rating:★★★★` could also work in a pinch. But if there's scaling going on, you would have to remap `rating:4` into, say, `rating:80`. Doable, but requires more code.

**Comment by CosimoVestri** [comment]
I think that this is one of those items that I would chalk up to be a _design decision_. It is an area in which an executive decision may just need to be made by the development team and stuck with. Not everything will be customizable in Stash, as that would result in chaos and make maintainability problematic.

Personally, I don't have a strong preference as to 5 or 10 point ratings, or addition of decimal or half points. I see usefulness in having a larger size of rating options, though workload/development costs need to be considered.

Adapting to legacy design choices is unfortunately a necessity in many cases.
