### ISSUE TITLE
[Bug Report] Stash shouldn't be able to scan its own generated folder

### ISSUE THREAD

**Issue by kermieisinthehouse** [stashapp/stash#1984]
A user might set up stash in their media folder. This can lead to situations where a scan will index its own generated folder. Scans should confirm that the generated folder is not a subpath of any Stash path.

**Comment by bnkai** [comment]
That's probably a regression from a recent pr. Stash actually silently ignores(d) the generated folder.
It seems that the queue files pr didn't reimplement that functionality for the scan part
Original issue #1102
Relevant fix PR #1118

**Comment by kermieisinthehouse** [comment]
Sorry this was based on a user report. I've just tested and it's not an issue, they must've done something else

**Comment by bnkai** [comment]
> Sorry this was based on a user report. I've just tested and it's not an issue, they must've done something else

Have you tried with latest dev build and generated was ignored correctly? I posted the above from my phone so i couldnt double check

**Comment by kermieisinthehouse** [comment]
Yeah I tested latest develop, built fresh

**Comment by bucketcat** [comment]
Stash scanned its own generated files back in one of the 0.17.x for me (all 80 gb of previews...) as long as I had the drive root containing its files added to the library. Had to de-select the entire drive since it kept re-scanning the generation folder no matter what after cleaning the 80gb of junk being added. In 0.18 it seemed to not scan its own generated files, until I added the path to the exclusions which did not exclude but resulted in it being scanned like normally. Ended up creating a partition for Stash itself so that it can fuck off without getting caught in a recursive self-scan loop. So something is certainly acting up. I might have done a selective scan of the entire drive before when it first scanned its own generated files, just a guess and not entirely sure how to replicate sadly. Slightly annoying either way.


 A dirty fix for this while ignoring the root cause could be to have all generated files be of a unique file format that is globally excluded (functionality wise identical, just renamed for files generated by Stash. Sadly, MKV is the only open source video format I know of where you can clone it and convert to your own file extension. For images, both PNG and jpg are open source formats). So making a copy, that is identical to the original file format besides a renamed extension for all generations and adding it as a global exclusion could be something worth considering. Would be the quickest way to resolve any similar issues without having to spend time trying to replicate the conditions.


@bnkai since this issue is technically closed I'll go ahead and ping you, hope you don't mind. Cheers.
