### ISSUE TITLE
[Feature] Delete file from unconnected drive.

### ISSUE THREAD

**Issue by z8r8xsmbxciryzv3g46j** [stashapp/stash#2093]
When deleting a file from a drive that is not connected, give an error or remember it to perform the action when the drive is connected.

**Comment by kermieisinthehouse** [comment]
We don't really have a way of determining if a file is missing because it was deleted outside of Stash, or if a drive is not connected, or if there's some other error. If you ask Stash to delete a file and it doesn't exist, we currently consider that a success, e.g. the user wanted something gone and it is gone. 

Having a list of files to delete should they become available sounds otherwise dangerous - how do you revoke a pending delete? What if you delete something that's missing, forget about it for years, and then download something of the same name, and it disappears?
