### ISSUE TITLE
[Bug Report] Panic in Generate

### ISSUE THREAD

**Issue by kermieisinthehouse** [stashapp/stash#2250]
Probably introduced in #2167

```
panic: runtime error: integer divide by zero

goroutine 105 [running]:
github.com/stashapp/stash/pkg/manager.(*GeneratorInfo).configure(0xc000136500)
    github.com/stashapp/stash/pkg/manager/generator.go:115 +0x9d
github.com/stashapp/stash/pkg/manager.(*PreviewGenerator).Generate(0xc000018310)
    github.com/stashapp/stash/pkg/manager/generator_preview.go:56 +0x78
github.com/stashapp/stash/pkg/manager.(*GeneratePreviewTask).Start(0xc00039a000, {0x198fc98, 0xc0001fa600})
    github.com/stashapp/stash/pkg/manager/task_generate_preview.go:59 +0x4b5
github.com/stashapp/stash/pkg/manager.(*GenerateJob).Execute.func3()
    github.com/stashapp/stash/pkg/manager/task_generate.go:127 +0x3c
github.com/stashapp/stash/pkg/job.(*Progress).ExecuteTask(0xc0001fa700, {0xc00038e160, 0xa9}, 0xc0001f2d00)
    github.com/stashapp/stash/pkg/job/progress.go:153 +0xcd
created by github.com/stashapp/stash/pkg/manager.(*GenerateJob).Execute
    github.com/stashapp/stash/pkg/manager/task_generate.go:126 +0x3bb
```

**Stash Version: (from Settings -> About):**
0.12.0

**Desktop (please complete the following information):**
 - OS: Docker on MacOS

**Comment by kermieisinthehouse** [comment]
It looks like setting segments or duration to 0 in the preview generation options will cause division by 0. We need some validation there.

**Comment by bnkai** [comment]
#2167 only changed code for the sprites generation so i dont think it was related

I think the issue is the `Number of segments in preview` that is set to 0
From a quick look
<https://github.com/stashapp/stash/blob/0388aec94294f4ce18c15ec65d4373067cd817d1/pkg/manager/generator.go#L115>
<https://github.com/stashapp/stash/blob/0388aec94294f4ce18c15ec65d4373067cd817d1/pkg/manager/generator.go#L149>
could be the cause

For the segment duration option we already take care of that as having too small of a duration had some issues
<https://github.com/stashapp/stash/blob/0388aec94294f4ce18c15ec65d4373067cd817d1/pkg/manager/generator_preview.go#L111>


For the chunkcount idk if its better to set it to 1 if its <1 (doesnt make sense with numbers <1) in the above function, before <	[stepSize, offset := g.Info.getStepSizeAndOffset()](https://github.com/stashapp/stash/blob/0388aec94294f4ce18c15ec65d4373067cd817d1/pkg/manager/generator_preview.go#L108)> or just/also alter the generator functions <https://github.com/stashapp/stash/blob/0388aec94294f4ce18c15ec65d4373067cd817d1/pkg/manager/generator.go#L115> <https://github.com/stashapp/stash/blob/0388aec94294f4ce18c15ec65d4373067cd817d1/pkg/manager/generator.go#L149>  to also check 

An extra chek here chould also be added
<https://github.com/stashapp/stash/blob/0388aec94294f4ce18c15ec65d4373067cd817d1/pkg/manager/task_generate_preview.go#L53>

**Comment by kermieisinthehouse** [comment]
This is what it was, the user had set segments to 0. We should disallow that in the UI.
