### ISSUE TITLE
[Feature] User-friendly error on marker creation

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#2256]
Whenever you leave the required fields empty when creating a marker, a parsing error pops up as the toast message. This should be changed to reflect what required fields were left empty.

On that note, should we consider adding an asterisk (*) next to field names that are required?

**Comment by IAmKontrast** [comment]
@QxxxGit What required fields do you mean? In my stash instance (v0.15) title, time and tags are not required.
'Primary tag' throws an error dialog but I guess this is caused by CommunityScripts/plugins/markerTagToScene.
Don't get me wrong, I like your request for UI/UX improvements but I prefer solving the empty-tag-issue at the markerTagToScene plugin.

`
Error
strconv.Atoi: parsing "": invalid syntax`

**Comment by DingDongSoLong4** [comment]
I believe this is fixed by #3945.
