### ISSUE TITLE
[Feature] Disable duplicate handling for a given path

### ISSUE THREAD

**Issue by PsychoSid** [stashapp/stash#2261]
**Is your feature request related to a problem? Please describe.**
Not really, I have a folder of models, site/studio etc. Which is being indexed but I also keep a slightly smaller collection of "favourite" files - both images, and scenes on a external drive that is also indexed and a lot of duplicates are thrown - as expected.

**Describe the solution you'd like**
Disable duplicate handling for a given path(s)

**Describe alternatives you've considered**
Just ignoring the messages etc. Or not indexing one path. Neither is that appealing to my use case.

**Additional context**
I may be asking for something unique here so might not be worth the effort. Also they may be other potential workarounds available ?

Cheers.

**Comment by PsychoSid** [comment]
Hi - Thanks for the reply - I don't think that's true. For example I have images in my favourites folder which were scanned first. These have no tags on them but the `<filename>` is the same. If I have the same image in a folder with an auto-tag structure `<model>/<site>` they do not show up under either the model or the site as images as they are ignored due to being duplicates.

**Comment by bnkai** [comment]
As it is now duplicate handling can not be disabled. There are plans (not soon though) to decouple files from scenes/images  which is the only proper fix for this imho.
Temporary for scenes that you have not yet scanned (not for the existing) you could do one of the below
- Move the prioritized folders up in the library (the scan searches the libraries folders in order so that `should` first detect and add the filenames/paths you want)
- Do selective scans first of the folders you want and then a plain scan


For the existing say images you mention you could try unmounting the external or renaming the root folder from the external and doing  a rescan. The scan will find the new files and since it wont be able to locate the existing ones it `should` update the images with the paths you want instead of the externals

**Comment by PsychoSid** [comment]
Thank @bnkai moving the paths around worked around the "problem" sufficiently for me. Appreciate the advice.
