### ISSUE TITLE
[Feature] Keyboard Shortcut 'f' to toggle fullscreen

### ISSUE THREAD

**Issue by IAmKontrast** [stashapp/stash#2262]
Keyboard Shortcut 'f' to toggle fullscreen on and off.
Also ESC should end fullscreen.
Pretty useful shortcut and default nearly everywhere.

**Comment by philpw99** [comment]
Have you tried "F11" ?

**Comment by IAmKontrast** [comment]
> Have you tried "F11" ?

This puts the browser in fullscreen only, not the video.
(Tried with Google Chrome v97)

**Comment by masterofobzene** [comment]
philpw99 is a harlequin around here. He just answers whatever comes to his mind and then tries to offer his non-working 3rd party plugin (made exclusively to patch this app's lack of playability).
Just ignore him. He thinks he's smart.

On the shortcuts side, they said they would implement a configurable shortcuts after my petition a while ago. Don't know if they honored that since I didn't tried this program since the last version, because it is completely useless from its fundations. And your issue here seems to confirm what I say. The may have added configurable shortcuts, but to useless functions. Typical around here.
Making a porn collection management app and advertising it as also a viewer (an "all in one solution"), but not giving a fuck about playability of your own collection; is at least bad reasoning.

**Comment by VonTittyslappen** [comment]
> philpw99 is a pet around here. He just answers whatever comes to his mind and then tries to offer his non-working 3rd party plugin (made exclusively to patch this app's lack of playability). Just ignore him. He thinks he's smart but he doesn't even know what a symbolic link is.
> 
> On the shortcuts side, they said they would implement a configurable shortcuts option after my petition a while ago #2021. Don't know if they honored that since I didn't tried this program since the last version, because it is completely useless from its fundations. And your issue here seems to confirm what I say. They may have added configurable shortcuts, but to useless functions. Typical around here. Making a porn collection management app and advertising it as also a viewer (an "all in one solution"), but not giving a fuck about playability of your own collection; is at least bad reasoning.
> 
> A suggestion: don't waste your time with stash. #2104

Here's a suggestion, fuck off, you entitled complaining prick. The audacity to bitch & moan about free software

**Comment by WithoutPants** [comment]
This is resolved by #2099. There was an existing fullscreen shortcut for `f` but it was being intercepted by the File Info keybind.
