### ISSUE TITLE
[Bug Report] Build stash on FreeBSD

### ISSUE THREAD

**Issue by isnogudus** [stashapp/stash#2429]
**Describe the bug**
Compiling stash on FreeBSD leads to an error.

**To Reproduce**
Run gmake in the stash source folder.

**Expected behavior**
The compilation should succeed.

**Screenshots**
[jmt@clu ~/src/stash]$ gmake
go generate -mod=vendor ./cmd/stash
validation failed: packages.Load: /usr/home/jmt/src/stash/vendor/github.com/kermieisinthehouse/systray/systray_nonwindows.go:13:8: could not import C (no metadata for C)
exit status 1
cmd/stash/main.go:1: running "go": exit status 1
gmake: *** [Makefile:165: generate-backend] Error 1

**Stash Version: (from Settings -> About):**
This error comes with v0.13.0. The version v0.12.0 compiles without any problems.

**Desktop (please complete the following information):**
 - Device: PC
 - OS: FreeBSD 13.0-RELEASE-p10

**Additional context**
The problem comes with the systray library. I managed to disable systray and work arround this problem for the FreeBSD os. But I thing the thrown error is not systray-specific.

**Comment by bnkai** [comment]
TBF i dont think that Freebsd is listed anywhere in the repo as a supported platform, so i wouldnt call this a bug.

Anyway for the systray in freebsd you should use the code that is for linux (it does nothing at all since systray isnt supported there) 

Disclaimer: All the below are untested. You can try them to see if they let you proceed a bit more

In the `stash/internal/desktop/systray_linux.go` file add a build tag for freebsd
```golang
//go:build linux freebsd
// +build linux freebsd
```
You should edit the `systray_nonlinux.go` as well to make it not compile 
```
//go:build windows || darwin || !linux || !freebsd
// +build windows darwin !linux !freebsd
```
Not compiling the nonlinux part should get you past the error you pasted.

You probably have to edit the `desktop_platform_linux.go` and add a build tag there
```golang
//go:build linux freebsd
// +build linux freebsd
```
A separate `desktop_platform_bsd.go` would be better but the code in the platform_linux file looks harmless, so it could work
