### ISSUE TITLE
[Bug Report] Commit 1920 introduces bad behaviour

### ISSUE THREAD

**Issue by dusparr** [stashapp/stash#2456]
**Describe the bug**
Making a "Max page length" for a tool used to normally affect a whole DB, is bad behaviour

**To Reproduce**
Attempt to use File-rename in a sane way

**Expected behavior**
Max, if exists, should be pulled from a config

**Fix
Revert the commit

**bad commit
https://github.com/stashapp/stash/pull/1920

**Comment by dusparr** [comment]
Hardcoded variable; max size limits possible affects of the tool when the
tool is designed to affect full DB; causes UI/UX issues with large DB due
to having to click many times to get anything done
This is Bad Code, Unintended Behaviour, Bad UI/UX behaviour
Those are all the simplest problems; just revert the change and think about
pulling the max size for pagination from a config file (also the drop down,
in fact all dropdowns with integers)

**Comment by WithoutPants** [comment]
Which tool are you referring to?

**Comment by dusparr** [comment]
Referenced in the bug: https://github.com/stashapp/stash/pull/1920

The commit only changes 1 file; the whole commit is the issue

**Comment by WithoutPants** [comment]
> Referenced in the bug: #1920
> 
> The commit only changes 1 file; the whole commit is the issue

This doesn't answer my question.

PR #1920 was added because we already limit page size to 1000 in the backend, the PR merely makes it consistent in the frontend. 

I'm not changing these values without an actual reason - specifically, what are you trying to do that you cannot do right now with the current limitations.

**Comment by dusparr** [comment]
Basic usage for the tool is to change many files at once; currently that is
unreasonably complicated due to max limits like this.
The page the tool is referenced on regenerates the list everytime you press
apply so it forces you to re-navigate from 0 every time
For example, with 50K files, this causes 100 clicks minimum due to having
to do many repeated navigations (actually closer to 200, but the match for
clicks is complicated)

Why would you limit it on the backend at all?

This is terrible behaviour for a user; Terrible behaviour from a DB
perspective (no real reason to limit it here); bad behaviour from a UI
design perspective (none of it is configurable and doesn't pull from
anything) and bad behaviour in general

**Comment by WithoutPants** [comment]
Basic usage of the tool _isn't necessarily_ to change many files at once, and the assumption is that 1000 is a reasonable upper limit to work on in the context of database queries and the UI. Large page sizes can cause indefinite loading times due to query complexities, and can cause memory issues in the UI.

So far you've talked in generalities about bad user experience, but you have to describe the actual use case that you are trying to do. Please state **specifically** what are you trying to do? What page/tool are you referring to and what operation are you doing that requires multiple clicks and reloads.

**Comment by Teda1** [comment]
I don't think Stash can handle more than 1000 items on a page which is likely why that restriction was added. Attempting to load 1000 items with very capable server and client machines yields a very sluggish navigation experience. If you need to make changes to many file it would be best to do it within a scrapper using the identify task or writing a script.

**Comment by WithoutPants** [comment]
Closing as invalid.
