### ISSUE TITLE
[Bug Report] VideoJs black bars

### ISSUE THREAD

**Issue by Mrgrpm** [stashapp/stash#2510]
**Describe the bug**
After the switch to VideoJs video content is not "centred" correctly. 
When I playing scene I get black bars around the video which causes me to see only half of the content and I need to scroll to the side to see whole video. 

**To Reproduce**
Play any video.

**Expected behavior**
Video should scale down to my resolution. (1920 x 1080)

**Stash Version: (from Settings -> About):**
14.0 

**Desktop (please complete the following information):**
 - OS: Windows 10 (1920 x 1080)
 - Browser Chrome 
 - Version 100.0.4896.88

**Comment by Teda1** [comment]
I assume you are referring to this issue: https://discord.com/channels/559159668438728723/559159910550732809/96313372747774773. If so adding the following custom CSS should resolve the issue for now:
```.VideoPlayer .vjs-touch-enabled {
    margin: 0px;
    width: 100%;
}```

Make sure to hit CTRL+F5 after applying the CSS to refresh your cache. A formal fix for this issue is in the process of getting merged.

**Comment by Mrgrpm** [comment]
> I assume you are referring to this issue: https://discord.com/channels/559159668438728723/559159910550732809/96313372747774773. If so adding the following custom CSS should resolve the issue for now:
> 
> ```
> .VideoPlayer .vjs-touch-enabled {
>     margin: 0px;
>     width: 100%;
> }
> ```
> 
> Make sure to hit CTRL+F5 after applying the CSS to refresh your cache. A formal fix for this issue is in the process of getting merged.

Yes, that's the problem.

**Comment by WithoutPants** [comment]
Fixed in the dev branch.
