### ISSUE TITLE
How should scrapers work. Studios, performers etc

### ISSUE THREAD

**Issue by goodtimes2** [stashapp/stash#2588]
New to this application, have a a few scrapers configured and I think they are working as they show detected in the UI. However when doing a scan of my library nothing ever returns and I receive errors such as No scenes found . Should the scrapers auto populate studios, performers and other scene data automatically?

**Comment by ALonelyJuicebox** [comment]
Hi welcome to Stash! This issue you've submitted is less of a bug report and more of a help request for either Github Discussions or (even better) something to ask on our public Discord.

After adding a scraper, there's a good chance you still need to add an URL to the scene in order for the scraper to pull the metadata from that site. The exception to this is StashDB, which uses procedural hashes in order to match your scene to the metadata on a community managed metadata service. 

Regardless, as I mentioned, please head over to the discord if you have additional questions.

**Comment by goodtimes2** [comment]
Thanks for the advise to check discord, worked great. Looks like stashdb was the way to go!
