### ISSUE TITLE
[Bug Report] Symbolic links inside plugin folder do not load

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#2605]
**Describe the bug**
Symbolic links to folders which are made inside `~/.stash/plugins` do not load.

**To Reproduce**
1. `cd ~/.stash`
2. `git clone https://github.com/stashapp/CommunityScripts.git` creates ~/.stash/CommunityScripts
3. `ln -s ~/.stash/CommunityScripts ~/.stash/plugins/CommunityScripts` to create a symbolic link of the above folder inside the plugins folder
4. Reload plugins, nothing appears.

**Expected behavior**
Stash should load the all the plugins/scripts contained within the symbolic link. The same process correctly works in Stash if a symbolic link is created inside the `~/.stash/scrapers` folder that points to a `~/.stash/CommunityScrapers/scrapers` folder.

**Stash Version: (from Settings -> About):**
- Version: 0.15.0-1-ga142ec22
- OS: Ubuntu 20.04.4 LTS

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 101.0.1210.47

**Comment by cc1234475** [comment]
I just tried this on today's build and seems to work.

I moved a plugin out of the directory and made a relative path symlink to it. stash was able to see it.

**Comment by echo6ix** [comment]
This still did not work for me using a relative pathname.

I tried it using an absolute pathname and it did work. 

Maybe it is not a Stash issue?

**Comment by WithoutPants** [comment]
Can you please provide more information on what works and what doesn't?

Tried to reproduce using the following adapted steps:

1. `(in ~/dev/stash/instances/main) git clone https://github.com/stashapp/CommunityScripts.git CommunityScripts`
2. `ln -s ~/dev/stash/instances/main/CommunityScripts ~/dev/stash/instances/main/plugins/CommunityScripts`
3. Reload stash

It of course gives some errors due to the new layout of the repo, but it does load.

Can you provide any error messages that get output in the log as well?

**Comment by echo6ix** [comment]
@WithoutPants I'm actually unable to reproduce this now. Both relative and absolute symlinks work.

User error. Earlier today I didn't reproduce the relative symlink properly. I tried `ln -s MyPlugins/ ../plugins/MyPlugins` in haste, which is obviously wrong.

Apologies for not being forthcoming with my process earlier.
