### ISSUE TITLE
[Feature] Change file delete to flag and queue to execute when Clean is run

### ISSUE THREAD

**Issue by KlfJoat** [stashapp/stash#2909]
**Is your feature request related to a problem? Please describe.**
It's a little unsettling that deleting a scene in the UI deletes the file immediately.  Honestly, I thought that I needed to run a Clean to execute the real delete.

**Describe the solution you'd like**
I'd like for "delete" to be just a flag that's set. Remove the scene from the UI, of course. But let me filter for it to view all scenes/files queued for deletion and remove the flag if I see something queued for delete by mistake.

Then running a Clean would execute the real delete.

Bonus:  Can pop up and say "you will delete this list of scenes/files during this Clean. yes/no", as a further protection from deletion.

**Describe alternatives you've considered**
No alternative. This would fundamentally change how a dangerous file operation like delete happens to make it safer.

Please note that I store my paid (honestly) scenes on a NAS. So there is no OS-level Trash or Recycling system. That one Delete popup (which can be disabled) is the only thing between a mis-click/tap in the UI and having to re-purchase. (backups? what are those?)

**Additional context**
This is somewhat related to #2908.

You could log the intent to delete (delete flag set), a removal of the delete flag, and of course the file deletion when it happens during Clean.

**Comment by 7dJx1qP** [comment]
Files are not deleted unless you have the `Delete file (and funscript)` option checked

![image](https://user-images.githubusercontent.com/38586902/190259540-bdbf8335-c4ef-4b57-a53b-9b0a22d6faf1.png)

If it's not checked, the scene is only deleted from stash and would be readded if another scan is run because the file still exists.

The delete confirmation popup also always appears

**Comment by KlfJoat** [comment]
I am aware. I referenced this pop-up in my description.

I'm asking for a different mechanism than the one currently in place.

**Comment by DogmaDragon** [comment]
Completely unnecessary and a waste of development resources. 

There is already plenty of protection from accidentally deleting something. Like 7dJx1qP mentioned above, by default, the checkbox to delete the file is not set. So you have to misclick 3 times to delete the actual file.

**Comment by KlfJoat** [comment]
I see you went to the Linus Torvalds school of developer-user relations.

I came and suggested a feature different from and more user-friendly than the current method. But because the current method "works" (for some naive definition of "works"), you make snide comments.

That tone wasn't necessary at all. And if you find it difficult to use a better tone, you could copy someone else's more polite wording and paste it in. But I bet you'd find that completely unnecessary and a waste of resources.

**Comment by ALonelyJuicebox** [comment]
While I don't agree that we need a "queue this for deletion then head to Tasks to perform the action" feature as you are suggesting @KlfJoat, I would agree that the wording and UI of the delete feature maybe isn't as clear as it probably should be.

Would love to see more emphasis on what _exactly_ is being deleted (Deleting an entry from Stash vs deleting the actual file) as well as some additional emphasis on the danger of the action.
Something like this perhaps
![improvements](https://user-images.githubusercontent.com/76471868/190285497-54cc7cf2-33e4-4f75-bc3a-acd59bf1a579.JPG)

**Comment by 7dJx1qP** [comment]
> I am aware. I referenced this pop-up in my description.

Yes, but you also said it could be disabled which isn't true so I wanted to clarify what the exact behavior is in case there was any misunderstanding. I also describe an alternative since you stated you didn't consider any.

> I'm asking for a different mechanism than the one currently in place.

Requesting a different mechanism is fine. I personally wouldn't like having to clean every time I wanted to remove files, as I prefer having to run clean as little as possible, but I don't agree with @DogmaDragon 's reply that it's completely unnecessary and a waste of resources. That's up to someone who chooses to implement it to decide, which anyone with the capability can do. However, if it is implemented I'd like to see a way to switch to the current behavior to remain.

**Comment by HereIam80** [comment]
I never ran a clean task in my stash for over two years now and I don't plan to.
It really would make me nervous having to click that button as some of my scenes are on external drives.
That button is an easy way to get rid of your metadata if some files are inaccassible for whatever reason.

That being said if something like this would be implemented I suggest creating a seperate task.

**Comment by SpedNSFW** [comment]
For reasons I'm not going to get into in this issue, I cannot run "Clean" on my Stash. I do delete scenes quite frequently because I tend to pick up a lot of duplicates.

There is absolutely no need for this change at all. The dialog is clear in what is happening and adding to it takes away from the QoL of users. If I delete a file, I want it gone. I don't want to have to go and run a task or something, I want it gone.

**Comment by WeedLordVegeta420** [comment]
I would also lean towards this seeming to be unnecessary. I don't see any clear advantage over just deleting the file initially. As previously suggested, you could also get largely the same result if you just apply a "To Delete" tag and then review it later before doing the actual delete.

For the OP, I'd also suggest looking into if it's possible to add some sort of "Recycle Bin" style functionality to your NAS as that sounds like it plays a large part in why you're so concerned about this. Depending on your setup, it might not be possible, but it's worth looking into it. I have a "Recycle Bin" plugin running on my Unraid NAS server that will instead of deleting a file, move it to a recycle bin folder. That folder then gets automatically cleaned once per week based on some criteria or I can manually clear it out. It has saved me some headaches occasionally, although not from anything directly related to Stash.

**Comment by PhuriousGeorge** [comment]
I concur this is unnecessary.  If you're concerned about accidently deleting a file, use custom css or a greasemonkey script, etc to get rid of the delete button and perform deletions manually in your file system.

If you don't want to do that, go to Settings > Library and be certain these are turned off:
![image](https://user-images.githubusercontent.com/1485658/200137818-59aea542-b94b-4fd5-875a-04c977f81969.png)

**Comment by KlfJoat** [comment]
Closing out since it won't be implemented.
