### ISSUE TITLE
[Feature] Show file path on list view

### ISSUE THREAD

**Issue by ghost** [stashapp/stash#2948]
As I've increased the number of files I have, stash has been getting slower and slower. Right now it takes 34 seconds on average for it to open a scene. I would like to be able to copy the path from the list view and open the file in a file manager.

**Comment by ALonelyJuicebox** [comment]
Oof, 34 seconds is pretty significant...

What kind of media file are you trying to open in stash? Is Stash transcoding the file?
What is the size of your Stash SQL db file? 
How many scenes do you have in your db?
What are the specs of the machine running Stash?

**Comment by JediMaster25** [comment]
> What kind of media file are you trying to open in stash? Is Stash transcoding the file?

I use mp4 and mkv, it doesn't change the time it takes to open. But it plays mkv slower so I never use stash for those.

> What is the size of your Stash SQL db file?

5.7 GB

> How many scenes do you have in your db?

100k

> What are the specs of the machine running Stash?

AMD 5600G

**Comment by MrX292** [comment]
> I use mp4 and mkv, it doesn't change the time it takes to open. But it plays mkv slower so I never use stash for those.
It is probably Transcoding those. 
When the video plays in stash click on the cog in the video player if there is no direct stream option selected and it is not in the list then it is transcoding.
You can try the Userscript `Stash Open Media Player` from https://github.com/7dJx1qP/stash-userscripts

**Comment by bucketcat** [comment]
I have quite a few issues that would be solved by a hotlink with the file path(such as the gallery/image viewer not being functional at all, 90% of the time, the scene viewer just breaks randomly making it impossible browse galleries. No clue what the source is so wont open my own issue, probably firefox ETP related). So please consider this topic instead of trying to solve OP's specific problem exclusively. This would be a useful band-aid for a lot of different problems that do/can arise as a fall back, without having to fully revert to using your local desktop environment and file manager to navigate the smut.
