### ISSUE TITLE
MacOS scan does not work, and cleaning attempts to remove entire filesystem

### ISSUE THREAD

**Issue by shanty-chits** [stashapp/stash#2950]
**Describe the bug**
Recent development versions do not scan folders correctly. Logs show an error about dotfiles (even if those are excluded) and the scan does not find any new items. The Clean utility also now attempts to remove the entire root directory. 

**To Reproduce**
1. Go to Tasks and select Scan
2. New items are not found and the scan shows errors.

1. Go to Tasks and select Clean
2. The entire filesystem root "/" is marked for cleaning. 

**Screenshots**
<img width="829" alt="Screenshot 2022-09-25 at 11 27 31 PM" src="https://user-images.githubusercontent.com/92681442/192188761-4993a6a6-d525-4b68-b5b4-ee87d88b41a1.png">

<img width="792" alt="Screenshot 2022-09-25 at 11 32 13 PM" src="https://user-images.githubusercontent.com/92681442/192188862-5ecbad52-4860-4744-bdc4-88af49d67677.png">

**Stash Version: (from Settings -> About):**
v0.16.1-67-g00820a87

**Desktop (please complete the following information):**
 - OS: MacOS 13.0
 - Browser [all]

**Additional context**

**Comment by WithoutPants** [comment]
The `Folder not in any stash library directories. Marking to clean: "/"` message is expected, if a little misleading. During the schema migration process for schema 32, it creates a number of `folder` entries in the database, all the way up to the root directory, even for those outside the stash library. When clean is first run, it removes these superfluous folder entries because they aren't actually valid. It's not actually removing anything else, otherwise you'd see `Marking to clean` for all of your other contained files.

I'll amend the migration to be a little smarter so that these folders aren't created in future, but for now there's no problem here.

I will however double-check the exclusion code to see why you're getting those `permission denied` errors.

**Comment by WithoutPants** [comment]
As far as I can tell, those `permission denied` are because `.Trashes` is a directory. Directories will _only_ be ignored if the path matches both the excluded video and excluded image patterns. If either do not, then the directory will be read, and if there is no read permission then you'll get those errors. Can you confirm that the `.Trashes` filename matches both exclusion patterns?

**Comment by shanty-chits** [comment]
Previously, my exclusions were set to ignore dotfiles according to the wiki:
<img width="809" alt="Screenshot 2022-09-28 at 11 04 53 PM" src="https://user-images.githubusercontent.com/92681442/192929695-86d3b099-e0a6-4a1b-ba84-6c111f4e9443.png">

Setting each and every identified file and folder as individual exclusions does work, though.

**Comment by WithoutPants** [comment]
I think the extra `\` character in the video patterns might be causing the issue. It's not present in the image/gallery pattern.
