### ISSUE TITLE
[Feature] Add performers in tagger mode

### ISSUE THREAD

**Issue by thedesi1** [stashapp/stash#2998]
Problem Statement:
While mass scraping scenes using StashDB or TPDB, there is no option in tagger view to add performers. 

Proposed Solution:
Ability to manually add performers if the source does not have them, just like tags, it would be even better if the performers are missing, the scrape screen suggest performers based on the file names.

Alternatives:
Scrape the scene and then go back and edit the scene, its very manual and annoying.

Additional context:
[Discord discussion](https://discord.com/channels/559159668438728723/1029180516064309350/1029485375334395964)

**Comment by Ch00nassid** [comment]
Is this not what you are looking for? 
![image](https://user-images.githubusercontent.com/57732969/195234089-c928e6af-7135-49a7-a96a-9bd5e20a2fe9.png)

**Comment by AdultSun** [comment]
We were discussing this on Discord first, the problem is that there is no way to manually add a performer to the scene *in addition to* the suggested performers in the Tagger results. You can create or reassign those three performers using the buttons in your screenshot above but you can't add a fourth performer to the scene because there isn't a fourth "performer slot" to use. The field for tags lets you manually add as many more tags as you'd like, but there's no easy way to do the same with performers. You have to either leave the Tagger view or re-scrape to manually re-assign a slot to the additional performer (existing performers are never removed by the Tagger), neither of which are very convenient.

**Comment by thedesi1** [comment]
![image](https://user-images.githubusercontent.com/108954762/195336616-4394d295-f0cd-4521-bfd0-b90a8836628c.png)
Look at this example from TPDB, no way to add or update a performer.

**Comment by thedesi1** [comment]
and I should pry delete this post because of the words in the pics...

**Comment by thedesi1** [comment]
not planned
