### ISSUE TITLE
Linux install

### ISSUE THREAD

**Issue by brauler** [stashapp/stash#30]
Hello!
I run the executable ./stash-linux from the terminal but it do nothing.
What's wrong? 
What i need to execute the file? 
Thx!

**Comment by brauler** [comment]
The executable is a 64 bit architecture? 😅😅😅

**Comment by seducingbits** [comment]
did the file had the right permissions? Did you try reaching stash on localhost:9998 or 9999?

**Comment by StashAppDev** [comment]
I haven't actually tried running the app on Linux yet.  Is anyone else seeing this issue?

**Comment by seducingbits** [comment]
Works for me. I run stash in a docker container based on ubuntu. Hadn't luck with the often recommended alpine base image. As a host I am using unraid/slackware linux.

**Comment by brauler** [comment]
I was runing a 32 bits arquitecture debian😅😅😅, I'm sorry, I tried it on 64-bit and it works perfectly!!! 🤣🤣🤣
Thx a lot!!

**Comment by iwiwdt** [comment]
```dockerfile
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y wget xz-utils && \
    wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz && \
    mkdir /ffmpeg && tar xf ffmpeg-release-amd64-static.tar.xz -C /ffmpeg && \
    mkdir -p /root/.stash && \
    cp -R ffmpeg/*/* /root/.stash/ && \
    rm -rf ffmpeg*

RUN wget https://github.com/stashapp/stash/releases/download/v0.0.0-alpha/stash-linux && \
    chmod +x stash-linux && \
    echo '{\n  "stash": "/mnt/data",\n  "metadata": "/mnt/metadata",\n  "cache": "/mnt/cache",\n  "downloads": "/mnt/metadata/downloads"\n}' > $HOME/.stash/config.json

CMD [ "/stash-linux" ]
```

**Comment by tarchive** [comment]
@seducingbits 
Unraid user here too. I'm trying to keep my dockers tidy and consistent so I was wondering if you had mapped this stash app's config files to your unraid appdata directory? If so how?

Using iwiwdt dockerfile as an example, the config files will be located in /root/.stash


Docker allows me to mount it as 
> -v '/mnt/user/appdata/StashApp':'/root/.stash':'rw'

 but the stash app wont start due to missing files. 


Docker log:
`time="2019-03-23T18:11:35Z" level=error msg="open /root/.stash/config.json: no such file or directory"
time="2019-03-23T18:11:35Z" level=error msg="config file parse error (ignore on first launch): invalid argument"
time="2019-03-23T18:11:35Z" level=info msg="couldn't find FFMPEG, attempting to download it"
time="2019-03-23T18:11:35Z" level=fatal msg="Unable to locate / automatically download FFMPEG\n\nCheck the readme for download links.\nThe FFMPEG and FFProbe binaries should be placed in /root/.stash\n\nThe error was: no ffmpeg url for this platform\n"`

I would expect it to create the missing files on startup but it doesn't. Permission issue maybe? 

Thanks

**Comment by StashAppDev** [comment]
Most of the time when people have issues with docker it is a permission issue.  I'd check to see what the permissions for that folder are on the host.

**Comment by tarchive** [comment]
The host folder permissions are nobody:users 99:100

For some reason i cannot reproduce the first error where config.json is missing. 

The next issue is missing the FFMPEG files. I was not aware when a empty host folder is mounted it will overwrite the existing contents of the container folder as an empty folder too.  I had though that the folders contents would merge so the existing FFMPEG files that were grabbed in the dockerfile would be put into the hosts folder automatically

With that known now if i manually extract the FFMPEG files to the host directory and start the container it appears to run normally.

I could accomplish this automatically in the future by putting a line in the dockerfile to copy in a script  that will check for FFMPEG files at startup, grabbing them in not found. 
Is this the right way to go about this?

Thanks

**Comment by seducingbits** [comment]
Hey, 
sry for the late reply. My Dockerfile:

```
FROM ubuntu:latest

WORKDIR /root/.stash

RUN apt-get update && apt-get install -y \
    curl xz-utils \
    && curl -s https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz \
        && tar -xvf ffmpeg.tar.xz \
        && mv ffmpeg-*/ffmpeg ./ffmpeg \
        && mv ffmpeg-*/ffprobe ./ffprobe \
        && rm ffmpeg.tar.xz \
        && rm -r ffmpeg-*

COPY . .

EXPOSE 9998
EXPOSE 9999

VOLUME /porn /config /root/.stash/stash-go.sqlite

RUN ls -la /root/.stash
CMD ["./stash-linux"]
```
The `copy . . ` line copies the stash-linux file and a config.json with the following content
```
{
    "stash" : "/porn",
    "metadata" : "/config/metadata",
    "cache" : "/config/cache",
    "downloads" : "/config/metadata/downloads"
}
```

and my Unraid config: https://imgur.com/a/A2kO6Oy

I hope that helps!

**Comment by Leopere** [comment]
This looks dated and likely solved.
