### ISSUE TITLE
[Bug Report] SQL error when submitting orphaned tagger fingerprints of a deleted scenes

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#3032]
**Describe the bug**
Stash reports an SQL error when trying to submit fingerprints of a scene that has been deleted.

**To Reproduce**
1. Go to the scene tagger
2. Scrape a scene and save
3. Delete scene from step 2, and all generated files.
4. Go back to the tagger, and try to submit the fingerprints.

**Expected behavior**
I suppose the file_fingerprints should also be deleted when the scene is deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/37937507/197311607-350dd5d8-3bb4-4942-bdc5-2d7d56ee59b6.png)

**Stash Version: (from Settings -> About):**
v0.17.1

**Comment by DingDongSoLong4** [comment]
This happens because the tagger stores the pending fingerprints to be submitted by their scene IDs locally in the browser, which are then not updated when a scene is deleted. 
A quick fix would be for the backend to ignore invalid scene IDs if they are submitted, but I would argue that storing the pending fingerprint information in the database would be a much better solution. That not only allows for deleted scenes (and deleted stash-box endpoints) to be easily removed using SQL relationships but would also allow the pending fingerprint list to be shared between devices.

**Comment by WithoutPants** [comment]
Fixed in 0.17.2.
