### ISSUE TITLE
[Bug Report] Studio Auto Tagging confusion with a master/slave directory structure

### ISSUE THREAD

**Issue by Cutters1982** [stashapp/stash#306]
Hi all

Happy New Year!

I've come across a bug with the Studio Auto Tagger where it keeps trying to add the same Studio tag over and over again to the same scenes, I've found that this issue is caused when you have a path structure with sub-site folders in a main site folder, example below:-

A:\Archive\Websites\Girlsway.com\Web Young\Ashley Adams & Milana Ricci - Web Young (Seeking Shelter).mp4

The auto tagger would keep saying it's adding the tag "Web Young" when this tag has already been added (confirmed this by checking in DB Browser), every press of Auto Tag would attempt to tag Web Young to this scene, over & over.

I have both Girlsway and Web Young added as studios, which seems to confuse the Auto Tagger

To resolve this issue, I've had to re-locate that scene to the below folder:-

A:\Archive\Websites\WebYoung.com\Ashley Adams & Milana Ricci - Web Young (Seeking Shelter).mp4

When pressing auto tag, it no longer tries tagging this video as Web Young and correctly detects that the tag is already assigned

This is a problem where people want to have a clean structure for their archive, examples below:-

\Girlsway.com\Mommy's Girl\
\Girlsway.com\Web Young\

This only occurs when both the parent folder & sub-folder have studios added under that name (with or without the .com) - I have confirmed this because this issue doesnt happen with my BangBros Archive I have added, which follows a similar structure, the reason for this is because I have not added "Bang Bros" as a studio.

Hopefully I've explained this properly, message me on Discord if not - username Simmy

Cheers!

**Comment by WithoutPants** [comment]
To simplify the example:

You have two studios in the system: `foo` and `bar`.
You have a scene file with the following path: `/stash/foo/bar/scene.mp4`

The auto-tagger will currently attempt to add both studios to the scene, but since it can only have one, I'm guessing it will first set it to `bar`, then overwrite it then `foo` (assuming it tags in alphabetical order, which may not be accurate). What I'm not sure about is why the auto-tagger is not also logging that it's setting the studio to Girlsway as well.

What behaviour are you expecting for this scenario? There's no obvious behaviour that I can determine. I can prevent it from re-setting the studio in a single operation, but that will just make it prefer one arbitrary studio over another. Or perhaps include a setting to not overwrite existing tags?

**Comment by bnkai** [comment]
Given that with current schema only one studio exists for a scene i would say stick with  the simpler solution. IMHO if there is already a studio id in a scene leave it alone, if not first come first serve (probably alphabetical order as you say).

**Comment by Cutters1982** [comment]
I guess this is something that can be reviewed in the future once a parent studio thing is added :) for now I'll have to put them in their own folder, though this issue is still happening with Blacked & Blacked Raw scenes, it tries to tag Blacked Raw as Blacked, even when they are in separate folders.

**Comment by Cutters1982** [comment]
Have found another scenario

time="2020-01-08T04:47:36Z" level=info msg="Adding studio 'Share My BF' to scene 'Kendra Heart & Vienna Black - Share My BF (Caught In Deeper Pussy)'"

This already has Share My BF studio added to it, but keeps appearing on the auto tag list, I think the reason being is because the scene description containers the word "Deeper" - as Deeper is added as a Studio, it confuses the auto tag further.

Requires further review

**Comment by Cutters1982** [comment]
Excellent, thanks @WithoutPants and @Leopere :)
