### ISSUE TITLE
[Bug Report] Scrubber image missing (Incorrect .vtt ?)

### ISSUE THREAD

**Issue by Belleyy** [stashapp/stash#3156]
**Describe the bug**
Some of my scene don't have the scrubber image (the image below the video player), but they exist in my generated folder.

**To Reproduce**
🤷‍♂️ I don't know

**Expected behavior**
Showing the image

**Stash Version: (from Settings -> About):**
v0.17.2-44-gb1c00a64
Build hash:
b1c00a64
Build time:
2022-11-17 04:01:41

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox 107

**Additional context**
It look like it's mostly my older scene created that have this issue.
This bug report is pretty bad, but I don't know what/where I should look at to report correctly 😕

**Comment by puc9** [comment]
A few questions that may help clarify:
1. Did you change the Generated file naming hash in the system settings? By default it is set to ohash but if you changed then you will need to regenerate.
![image](https://user-images.githubusercontent.com/51006296/202835836-984de009-5a1f-46a3-81f5-d91876a73a6d.png)

2. What happens if you try to regenerate just for one of the troublesome scenes (clicking on the tree dots in the scene page):
![image](https://user-images.githubusercontent.com/51006296/202835907-a5a4196c-75c4-40aa-84f0-72789fed2cec.png)
After you click on Generate you have to make sure that Scene Scrubber Sprites is on.
It would be useful to attempt first without setting the Overwrite existing generated files checkbox and if it still doesn't work then try again but with Overwrite existing generated files enabled.

3. How do you know that the sprites are in the generated folder? How did you find the exact file? By name or by looking at it?
You would need to find two files in the {generated}\vtt folder named {hash}_sprite.jpg and {hash}_thumbs.vtt. Both are needed, I think.
The {hash} value from above needs to be exactly the same as one of the fields in the File Info panel:
- Hash field if in system settings you have set ohash for the file naming
- Checksum field if you have set MD5 naming,
It doesn't matter if you have MD5 turned on, it's the value from Generated file naming hash that matters to figure out the right name for the generated file.

I'm very new to Stash so I don't know if the naming convention changed recently but if it did that might explain why only your older scenes have this problem.

Check the naming and if it matches then try to regenerate the files and then report back to see if there is anything that can be done.

**Comment by puc9** [comment]
Based on https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#cue_timings the old format is not valid as it is missing the millisecond component `ttt`:

```
Each cue timing contains five components:

-     Timestamp for start time.
-     At least one space.
-     The string "-->".
-     At least one space.
-     Timestamp for end time, which must be greater than the start time.

The timestamps must be in one of two formats:

-     mm:ss.ttt
-     hh:mm:ss.ttt
```

So I guess that you are out of luck and you will need to regenerate them.
As for why it worked before, I do not know, but I would bet that it stopped working when they switched the video player.

I don't know if something can be done to automatically fix this, I will leave it to the devs to answer that if/when they have the time.

**Comment by WithoutPants** [comment]
I don't think it's related to the format issue. I think it's related to the image filename being incorrect.

I would think that this is a latent issue introduced with https://github.com/stashapp/stash/issues/2481

It would explain why it's only older scenes that have this issue. My suggestion would be to find and delete vtt files which contain `<md5-length checksum>_sprite.jpg` and regenerate the sprite scrubber files.
