### ISSUE TITLE
[Feature] Match partially-typed tags aliases 

### ISSUE THREAD

**Issue by YurikaL** [stashapp/stash#3180]
**Is your feature request related to a problem? Please describe.**
When manually printing tags in the input field, a drop-down menu appears below the input field that shows suggestions for matching tags while typing. Primary tag names are displayed even if the tag name entered partially, but aliases are displayed only if they are entered completely. It would be nice to match aliases the same way as primary tag names.

**Describe the solution you'd like**
Match aliases' names, even if they are typed partially.

**Describe alternatives you've considered**
Maybe make this feature optional, for those who prefer only full matching?

**Additional context**
<details><summary>Primary name matched even when partially printed</summary>

![matching primary name](https://user-images.githubusercontent.com/43180936/203629531-61f824d7-db53-4a2f-9922-2d0634ae39bd.png)
</details>

<details><summary>Alias matched only when fully printed</summary>

![matching alias](https://user-images.githubusercontent.com/43180936/203629519-dead285b-ee98-4cda-912d-1f833a1cb467.png)
</details>

**Comment by bdbenim** [comment]
Yes, this would be a great change!

Not sure if this belongs in its own feature request, but it's very closely related: If the user has typed out a tag in full, then that should be the top result among all matches (and therefore the one that will be selected on hitting Enter). Currently, partial matches (excluding aliases as described above) will be higher on the list if they come first alphabetically, e.g.:

![Screenshot 2022-12-01 131209](https://user-images.githubusercontent.com/97994155/205160338-ac4bb06b-f874-47e4-960a-4e0443a6a130.png)

If I type 'abc' and hit enter, I expect the 'abc' tag to be applied; however, the 'aabc' tag will in fact be applied instead because it comes first alphabetically.

**Comment by bdbenim** [comment]
To add: both of these quirks became noticeable to me recently when I thought to add abbreviations of some commonly-used tags as aliases. This would allow me to quickly enter them with a sort of shorthand while still keeping the same name for the tag when displayed. Unfortunately, this rarely worked because of the alphabetical sorting. And the lack of partial matches on aliases makes it harder to find some rarely-used tags if I don't remember exactly what I named them.

**Comment by WithoutPants** [comment]
I think this is resolved by #4478
