### ISSUE TITLE
Scenes Tagger config - "Set Tags" Persistence

### ISSUE THREAD

**Issue by Foucoubou** [stashapp/stash#3210]
**Describe the bug**
The configuration of Scene Tagger, specifically tickbox "Set Tags" gets set to false after restart of stash not regarding to previous set value.

**Expected behavior**
Expecting the persistent setting which would last even for restart.
![image](https://user-images.githubusercontent.com/105973305/204645321-beaf3e18-55ce-4461-9cbd-10b069fba4e3.png)

**Comment by Foucoubou** [comment]
Hello,
did anyone possibly has any idea how to avoid this thing?
It is really pain, when matching the scenes and realizing after that, that this tickbox was off :P

**Comment by Flashy78** [comment]
Pretty sure those settings are saved in your browser. So if you use incognito or a different browser, you will lose your previous settings.

**Comment by Foucoubou** [comment]
> Pretty sure those settings are saved in your browser. So if you use incognito or a different browser, you will lose your previous settings.

Hmm... It would be nice to have this in the config file probably, if it is not...

**Comment by DogmaDragon** [comment]
Wouldn't call this a bug. Working as intended as the settings are stored in [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) on your browser. 

Make sure your cookies are enabled for the site or the settings will get reset to default. 

Though it's definitely worth improving to make it persistent.

**Comment by BonerFide** [comment]
There's a couple of potentially easier options than the proper server side persistence, I listed them in #4982 after being caught by this issue for the 4th ish time. Same trap that I've fallen into every time as @Foucoubou . That the settings aren't persisted wouldn't be as big of a problem as it is if it was obvious they had been lost, instead of silently causing missing data.

It may be working as intended, but it's not just an inconvenience / extra step, it presents as a bug. One I think pretty much everyone that has been using stash for a long period that doesn't use the defaults has fallen into every few months.
