### ISSUE TITLE
[Feature] Improve Scanning Button to include other functions (Auto Tag, Generate)

### ISSUE THREAD

**Issue by synsyn93** [stashapp/stash#323]
When clicking "Scan" allow it to do multiple actions at once if needed.  Make the other options toggle-able so that if a user does not want to generate sprites or kick off the auto-tag feature they don't have to.    

Alternatively another solution might be when clicking multiple options (Scan, Auto-Tag, Generate) queue them up so that eventually each will finish.

**Comment by bnkai** [comment]
Scanning and generating/doing something else at the same time is not safe.
On the other hand adding the other tasks in a queue  seems ok to me and a good feature to have.

**Comment by JoeSmithStarkers** [comment]
Hi @bnkai, i'm curious why scanning and generating sprites/previews isn't safe? 

I've been running a modified stash for quite some time, that among other things implements sprite/preview generation while scanning. However I am interested if there is a reason why this isn't safe to do?

![image](https://user-images.githubusercontent.com/60503487/77639826-761f2780-6fad-11ea-8f38-380afc58d30c.png)

**Comment by bnkai** [comment]
I mentioned scanning and generating sprites/previews at the same time. My reason was that the scanning process is adding the file data (checksum among  other things ) in the db which the other two tasks depend to to get data. What you are doing is not in parallel, you are  effectively running the two generate tasks in parallel but AFTER scan is complete. That is "safe" and if it works for you it's ok it's just that a lot of people are complaining that scan takes a lot of time and this adds to it so i'm not sure it's ok for all (scanning imo is supposed to get the minimal things needed done for stash work eg file details and screenshots).

**Comment by rg9400** [comment]
+1 from my side. My usecase is that I have my files stored in a cloud (GDrive). When being read as part of the scan, they are streamed locally and cached for some time (until newer files replace them in the cache). Since Stash is reading the entire file, this takes a long time, which is fine as such. However, since Video Preview generation happens later, that would mean I would need to re-stream the entire file again for that task at a later time.

By allowing users to run these 3 tasks in a queue per item, it would allow the subsequent tasks (Preview Generation + Autotag) to happen on the already cached file, making the whole process significantly more efficient.
