### ISSUE TITLE
[Bug Report] Type Error "error loading dynamically imported module" when loading Scene

### ISSUE THREAD

**Issue by SirCumAlot1988** [stashapp/stash#3263]
**Describe the bug**
When I load a scene the attached type error is thrown

**To Reproduce**
1. Import a Scene
2. Go to Scenes Browser
3. Open the scene

**Expected behavior**
Scene should be opened

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/98083850/206851774-d62fe882-921b-4e72-96fa-2c0a2ff1dd18.JPG)

**Stash Version: v0.18.0-15-gce080c1b

The bug also appears in Stash v0.18.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 107.0.1

**Comment by WithoutPants** [comment]
I'm not sure what's going wrong here. Does the same error appear if you refresh the page? Is it only on a specific scene or all scenes?

**Comment by AldanaFan** [comment]
Hi,

Yes, when I refresh the page I get the same error. I tried a couple of test files and get the same error for all of them. For testing purposes I named one file C:/Test/test.mp4 to see, if it's related to the filename or path, but I still get the same error. Let me know, if you need more information.

Cheers

**Comment by AldanaFan** [comment]
Hi,

I've figured out, that it's a browser plugin problem. I use AdBlocker Ultimate for Firefox, which is causing these issues. After adding localhost to the exception lists it's working very well.

Since v0.16.1 is still working fine for me in Firefox, without the localhost exception, it must be related to the Stash update to v0.18.0 somehow.

Anyhow, from my side this issue can be closed. Thank you for this great piece of software!

Cheers
