### ISSUE TITLE
Scanner doesn't have all the options

### ISSUE THREAD

**Issue by QuarkZ26** [stashapp/stash#3316]
I have renamed all my pics and was trying to get the Titles in Stash to change too. While checking the help, the following is listed:

- Don't include file extension in title
- Set name, date, details from embedded file metadata.

Those aren't showing for me, but then again, there's not really any mention of the title itself. Rescanning and Cleaning didn't work. Is that expected behavior that changing a file name doesn't change the title in Stash?

**Comment by HereIam80** [comment]
This is expected behavior. The filename has nothing to do with the title except for the initial scan where it gets filled in instead of leaving the title empty.

The options you mentioned are not a part of stash anymore and those entries in the help section probably need to be removed.

**Comment by QuarkZ26** [comment]
So there is no way to change the title anymore to make it match the actual file name?

**Comment by HereIam80** [comment]
Apart from manually editing the title I don't think there is. The only thing you can do is remove the images and scan them again. Obviously you would loose the metadata attached to them however.

**Comment by QuarkZ26** [comment]
Wow, what a major oversight for a software that probably handles hundreds if not thousands of files that might be moved, renamed, or whatever else. It seems like re-titling option during scan would make sense?

**Comment by HereIam80** [comment]
Actually Stash handles moving, renaming and everything else exceptionally well.
Because it just needs another scan to find those files again in their new folders/with their new filenames and it changes the database accordingly. If that wasn't the case stash wouldn't even find your files anymore.

The title however as I said is NOT the filename but anything you want it to be.
It gets more clear when you are looking at scenes. A scene almost always has a totally different title than the filename would be.
I agree however that the handling of images in stash is not the best and can definitely be approved upon and some task to mass-rename titles may not be bad. For right now I am sure it is possible to create a plugin or at least some script for your use-case to automate it.

**Comment by QuarkZ26** [comment]
Fair enough. There's a lot i don't use in Stash, I mostly use it to have a web interface and deal with the rest in my folders directly. I guess i should try scrappers and all and see how everything works, I don't really have an issue with losing metadata at this point
Thanks!
