### ISSUE TITLE
Jellyfin Third Party Integration

### ISSUE THREAD

**Issue by seniorm0ment** [stashapp/stash#3399]
Would be very nice to be able to get Jellyfin to pull all metadata from Stash.
This would allow users to use Jellyfin exclusively for playback, but let Stash handle the metadata and tagging for Porn content. 

The user would add the same exact folder in Stash and Jellyfin.
Then the plugin for Jellyfin would fetch all the metadata from stash for the matching file paths.
 
Favorites in Jellyfin would be marked in Stash as favorites.
Also on first load of the plugin, if Jellyfin already has favorited videos for that folder it would recognize that and mark them in stash too.

**Comment by MikeLund** [comment]
Would https://github.com/stashapp/CommunityScripts/tree/main/scripts/kodi-helper not work for the first bit you mentioned? I'm not an expert as I'm only using Plex (which has a pretty decent agent-plugin for Stash), but Jellyfin has the same nfo data format as Kodi it looks like based on their documentation.

**Comment by seniorm0ment** [comment]
Nfo isn't really the cleanest way to do it imo. It would kinda suck to need nfo files for everything. 
It would work, but it isn't beautiful. Nfo on Jellyfin is more of a comptability thing.
I'm not familiar with how the plex plugin works, but I presume you just give it the ip and port and maybe an api token to connect to stash and it matches the filenames and paths up between the two and syncs metadata or something along that line?
That would imo be the way to do it. Not sure if jellyfin exposes hashes of files, but that could be used for identifying the files instead of relying on filenames

**Comment by MikeLund** [comment]
> I'm not familiar with how the plex plugin works, but I presume you just give it the ip and port and maybe an api token to connect to stash and it matches the filenames and paths up between the two and syncs metadata or something along that line?

Feel free to read [the code](https://github.com/Darklyter/StashPlexAgent.bundle/blob/main/Contents/Code/__init__.py), but yes, it's a plugin in Plex (really a "metadata agent") that queries the Stash API by matching filename and fetches the metadata into Plex like that. I think it technically could match oshash, but haven't tried that because full path+filename works best for me. It's still only one-way sync though, eg ratings from Plex don't get put into Stash.

Jellyfin has plugins, but they're in C# instead of Python. And yes, I agree it would be possible to function similar to the Plex plugin, just someone has to code it.

**Comment by Maista6969** [comment]
Out of scope for the Stash project
