### ISSUE TITLE
[Bug Report] Negative Lookbehind parsed as invalid Regex

### ISSUE THREAD

**Issue by SpedNSFW** [stashapp/stash#3418]
**Describe the bug**
Due to the performer "Lexi Sample", I've had to update one of my exclusion patterns to check for `lexi.` before `sample\.mp4$`. The updated regex is `(?<!lexi.)sample\.mp4$`.
After doing another scan with the updated exclusion pattern, I got the files I wanted, however I checked the logs and it was made clear that Golang doesn't support negative lookbehinds (or lookaheads) due to technical reasons, so the reason those files weren't excluded is because that pattern wasn't enabled at all, and thus any sample files would also get through.

I'm not sure if there are any workarounds that can be made in the code, but the alternative to the Regex pattern above is as follows:

```
(?:(?:^|[^i])|(?:^|[^x])i|(?:^|[^e])xi|(?:^|[^l])exi).sample\.mp4$
```

It isn't nice or easy to maintain if updates need to be made.

As this is a technical restriction within the language itself, I'm not sure if this will be fixed, but this is still a bug in my opinion. Workarounds are possible ([here's some Python code to create an alternative to negative lookbehinds](https://gist.github.com/SpedNSFW/1a42b795c702333ccb328f1bee27fff5) for example).

**Comment by DingDongSoLong4** [comment]
Yes this is very unlikely to be fixed as lookbehinds/lookaheads are one of the constructs not supported by Go's regex engine [re2](https://github.com/google/re2/wiki/Syntax) due to their inherent inefficiency. 

As I understand it, the reason why lookbehinds/lookaheads aren't generally needed is because it's usually fairly simple to write code to exclude matches if required - in your case you could use a capture group on the 5 characters before "sample" and just skip the match programmatically if it equals "lexi.". However, since in stash the user only has access to the regex itself that workaround becomes impossible.

I don't think it's really realistic to include an automated "alternative creator" for this specific scenario. One thing that might help would be to have "inclusion" patterns, where if a filename matches one of them then it will be included even if matched by an exclusion pattern. Or a ordered list of patterns where each one either accepts or rejects a match. But all that would be quite complicated both to understand and implement and likely not very useful to the vast majority of users, so also probably unrealistic.

Something that should definitely be done though (and which probably warrants a separate issue) is to validate all regexes before they are saved to the config file, to prevent them from "silently failing" when they are actually used.

**Comment by SpedNSFW** [comment]
> I don't think it's really realistic to include an automated "alternative creator" for this specific scenario. One thing that might help would be to have "inclusion" patterns, where if a filename matches one of them then it will be included even if matched by an exclusion pattern. Or a ordered list of patterns where each one either accepts or rejects a match. But all that would be quite complicated both to understand and implement and likely not very useful to the vast majority of users, so also probably unrealistic.

Inclusion patterns are actually a decent idea. Perhaps call them "Override Patterns" just to help with any confusion.

> Something that should definitely be done though (and which probably warrants a separate issue) is to validate all regexes before they are saved to the config file, to prevent them from "silently failing" when they are actually used.

I agree. Since the regex patterns are stored as strings, it's simple to run a regex check over them looking for any positive/negative lookaheads/lookbehinds.

**Comment by DingDongSoLong4** [comment]
> I agree. Since the regex patterns are stored as strings, it's simple to run a regex check over them looking for any positive/negative lookaheads/lookbehinds.

Well I was thinking more like just trying to `regexp.Compile` it so as to eliminate all kinds of regex errors. Since that would only be done on save, the overhead is not an issue.
