### ISSUE TITLE
Stash-box scrapper does not always associate performers correctly

### ISSUE THREAD

**Issue by Teda1** [stashapp/stash#3473]
**Describe the bug**
The stash-box scrapper will associate performers incorrectly when a performer with a StashID associated with it and with the same name exists in the user's DB. The scrapper does not take into account that the performer in the user's DB does not have the same StashID.

For instance, when tagging the scene https://stashdb.org/scenes/a47bb051-b573-4419-97d3-c485b1556467, I have a performer named Aubrey who has the StashID https://stashdb.org/performers/815f2de4-d274-4699-8be6-db486d1936b5. My Aubrey is different from the Aubrey in the scene I'm attempting to tag, but since my Aubrey happens to have the same name and a StashID, the prompt to create a new performer does not appear and Stash instead tags the scene with the wrong Aubrey.

This bug has been around for a while. I'm just now getting around to creating this issue.

**Comment by Flashy78** [comment]
The functionality is to first match by StashID, and if no perfomer exists, match by name, so the user doesn't have to manually search for the performer in their list. I wouldn't say this is a bug, it's doing what it's meant to do, it's just that you don't agree with the first Aubrey that it found.

I guess a change would be that if it matches an Aubrey, and that Aubrey has a Stash ID that is different, then don't automatically pick them. I can definitely see this causing confusion though, since the user won't know why their Aubrey wasn't selected for them to save the new Stash ID to, when all the other times they tag the performer is selected automatically for them.

Not sure what a good implementation would be for this behavior change.

**Comment by Teda1** [comment]
The scraper shouldn't intentionally be tagging performers incorrectly. If the scrapper knows a performer's StashID does not match, it should leave the performer selection field open for the user and provide them the option to create the correct performer the same way it does when it determines the user doesn't have a performer of that name with a StashID. The current behavior serves to hurt user trust.

**Comment by Teda1** [comment]
Before the disambiguous update, I understand that Stash wouldn't have been able to create a new performer in this case due to the name not being unique. At that point, I think the better solution would have been to leave the performer selection field open. With the disambiguous update, that previous limitation now has a workaround.

**Comment by Flashy78** [comment]
I think you're coming at it from the point of view that if a performer has a Stash ID, then that's it, they're matched. But since performers can have many Stash IDs, then you can't actually say that the performer is being tagged incorrectly simply

If I have Aubrey Plaza with a Stash ID, someone creates a new scene with a new Aubrey Plaza on StashDB and I tag that scene, I would expect to have my existing Aubrey Plaza selected and have the Stash ID added to her instead of creating another one.
I would think there was something broken if I remembered I already have an Aubrey Plaza and the tagger didn't select her.

Perhaps a better solution than not selecting, would be to display a little red exclamation mark next to the dropdown that says something like "Performer matched by name, but already has a different Stash ID".

**Comment by AdultSun** [comment]
Something else to consider here is which Stash-Box a performer's StashID is linked to. If a local performer has multiple StashIDs from different Stash-Boxes, than there likely isn't a problem. But if a local performer has multiple StashIDs from the same Stash-Box, then somebody (you or a Stash-Box) probably messed up somewhere at some point. It should be seen as a signal that something is wrong and that a closer look is necessary to figure out how best to fix it.

**Comment by Teda1** [comment]
I have acquired enough performers in my database to know how common names can be, even with names where a performer has a first and last name. Assumptions should not be made in the code on the user's behalf. 

If you have Aubrey Plaza with a Stash ID, someone creates a new scene with a new Aubrey Plaza on StashDB, and you tag that scene, the StashDB scrapper should be faithful to the data on StashDB and create an Aubrey Plaza with the StashID, it found. Appropriate measures have started to be implemented to ensure correct data is provided. Attempting to over-compensate for the potential errors in StashDB in the current way only leads to other errors. Going back to your `Aubrey Plaza` scenario, before any new performer gets created in my DB, I always do a quick search to ensure the performer being created is indeed new. I've mentioned it before; mismatched performers are much harder to detect than duplicate performers.

**Comment by Flashy78** [comment]
I guess I just don't think existing functionality that has worked one way for years should just be changed without some way of explaining it to the user.
How would this change of just not matching a performer by name affect Identify, Autotag, Import/Export?
How does it interact with existing tagged performers who are subsequently merged or deleted from StashDB?

In the end maybe we're talking about different things, because your PR does not change what I thought you were talking about.

**Comment by Teda1** [comment]
It makes sense that we were talking about different things. The fix for this issue doesn't take anything away from the user. It actually gives the user more choice. My fix ensures that the performer selection box and the create and skip buttons are not taken away when the scrapper hasn't confidently matched a performer.

**Comment by Flashy78** [comment]
You are changing it so that if the Stash ID does not match, the dropdown is shown with the performer selected, instead of locking in that performer to be selected.
I thought you were saying you wanted to show the dropdown with no perfomer selected at all.

**Comment by Teda1** [comment]
> You are changing it so that if the Stash ID does not match, the dropdown is shown with the performer selected, instead of locking in that performer to be selected.

Correct. I’m not sure where the misunderstanding came from.
