### ISSUE TITLE
[Bug Report] Not working on Smart TV

### ISSUE THREAD

**Issue by erebous** [stashapp/stash#3487]
Last dev build stopped working on LG browser running webos. It ask for the password then just the background is shown.

**Comment by DingDongSoLong4** [comment]
This is probably due to the dependency upgrade which dropped support for some older browser versions.

Would you be able to find out the webos version your TV uses? From [here](https://webostv.developer.lge.com/develop/specifications/web-api-and-web-engine) it should be in Settings > General > TV Information > webOS TV version.

**Comment by leeroyian** [comment]
Can confirm update to latest dev build breaks all functionality on LG TV browsers, It's an LG C9 from 2019 and the webOS tv version is 4.9.7-14.

**Comment by DingDongSoLong4** [comment]
That LG site says that the version of Chromium used in webOS 4.x is Chromium 53, which was released in 2017 and doesn't support ES modules which should also be a requirement on v0.19/v0.19.1 and not just the latest dev build.

Can you send the TV's user-agent string? (using a website like https://www.whatsmyua.info is probably easiest)
