### ISSUE TITLE
[Bug Report] Adding relative Path instead of absolute.

### ISSUE THREAD

**Issue by Syunica** [stashapp/stash#3716]
**Describe the bug**
Adding a New Library.
Any Up Direction adds ..\ , making them relative.
The problem is that, with this behaviour, the file path in the scenes also remain relative, so i had to copy paste the actual library path in order to have the actual path showed in every scene.

**To Reproduce**
1. Go to Library
2. Click on "Add Library"
3. Click on "Up Directory"

**Expected behavior**
Showing absolute Path

**Screenshots**
https://discord.com/channels/559159668438728723/559159931505213440/1102974462783127582
Video posted on the official stash discord.

**Stash Version: (from Settings -> About):**
v0.20.2

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Opera GX
 - Version LVL4 (core: 97.0.4719.89)

**Comment by Phasetime** [comment]
I can reproduce the bug if the initial path you type in is malformed and the directory view defaults to the stash root directory. After that any Up a directory remains relative to that stash root folder. I think you can create an issue for that.

**Comment by WithoutPants** [comment]
Having spent some time playing with this, I think ultimately it is working as expected.

If the input text isn't an absolute path (`D` as per the video posted), then it is assumed to be a relative path. Since `D` is not a directory in the current working directory, the directories for the current working directory are listed. An absolute path can be made by typing in `<letter>:\` in Windows, or `/` in the text field. As far as I can determine, there's nothing to fix here.
