### ISSUE TITLE
[Bug Report] .jpg is scene cover image is converted to .png when pasting from keyboard

### ISSUE THREAD

**Issue by oikmeg** [stashapp/stash#3742]
**Describe the bug**
Uploading a 5k (5760x3840), 1.5MB jpeg image as a scene cover, results in a 5K, 18MB png file being stored on the server as the scene cover. This seems to be isolated to using copy+paste the image. If you use the regular 'set image' from file, the jpg is stored normally.

**To Reproduce**
1. Go to scene details>edit.
2. Upload a 5k scene cover image as the cover, by using 'copy image' on your desktop, then ctrl + v into the screen area.
3. Reload page or go back to scene listing.
4. Check image on server (open image in new tab from bottom left edit scene cover).
5. Download image, check file size.

**Expected behavior**
Image should be stored 1:1 as a jpg, not a png.

**Stash Version: (from Settings -> About):** v0.20.2 (docker)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Brave (Chromium)
 - Version: v1.51.114

**Comment by oikmeg** [comment]
This seems to be a somewhat known phenomenon:
https://stackoverflow.com/questions/29056371/why-does-pnging-an-image-from-a-jpg-make-it-10x-bigger

I think the issue would be resolved by:
- Using JPEG as a default file storage to begin with
- Using WEBP as the default storage.

**Comment by DingDongSoLong4** [comment]
Stash doesn't do any processing of scene covers that I know of, whether pasting from clipboard or uploading a file directly. That being said, I can replicate the issue on Firefox on macOS, and a bit of investigation shows that it's actually Firefox which is converting the images to PNG before forwarding them to Stash.

I can't replicate it on Chrome on either macOS or Linux though, the images aren't re-encoded and are kept as JPGs. (Pasting images on Firefox on Linux doesn't work for me at all).

I don't have Brave installed to check there, but it seems likely that the issue is browser side and not Stash side. I could be wrong though. Would you be able to test a different browser to see if the issue persists?

**Comment by oikmeg** [comment]
I could reproduce this using Vivaldi (also Chromium engine) on Linux. On Linux, Firefox copy+paste doesn't work for me either at all.

**Comment by UncleRoger33** [comment]
> **Expected behavior**
> Image should be stored 1:1 as a jpg, not a png.

> a bit of investigation shows that it's actually Firefox which is converting the images to PNG before forwarding them to Stash.

Found a discussion thread about saving as PNG/JPG on Mozilla Support forums from 2019. 

> Because PNG is a lossless format (meaning better quality), Firefox tries to save that format whenever possible. However, there are some circumstances when screenshots will be saved as JPGs. This is mostly dictated by size restrictions.

One of the moderators says "_opening the file as a data URI allows to save the file as a .jpg file_" and suggests running the JavaScript code below on the Firefox browser console: 

```JavaScript
var cb = Services.clipboard;
var ps = Services.prompt;
var flavor = "image/jpeg"
var trans = Cc["@mozilla.org/widget/transferable;1"].createInstance(Ci.nsITransferable);
trans.init(null);
trans.addDataFlavor(flavor);
var str = {}, dat = "";
cb.getData(trans,cb.kGlobalClipboard);
try {trans.getTransferData(flavor, str, {})} catch(e){alert(e.toString().substr(0,800))}
if (str && str.value){
dat = str.value.data;
dat = "data:" + flavor + ";base64," + btoa(dat);
var obj = new Object; obj.value = dat;
ps.prompt(null, "CLIPBOARD", "< \"" + (dat ?"":"NO \"") + flavor + "\" DATA from CLIPBOARD >", obj, null, {});
```

Source: https://support.mozilla.org/en-US/questions/1259800

I'm not an expert, but perhaps tweaking and using this makeshift code somewhere in the Stash codebase allows Firefox to forbid converting everything to PNG files.

**Comment by DingDongSoLong4** [comment]
@UncleRoger33 That snippet there is for running in the [Browser Console](https://firefox-source-docs.mozilla.org/devtools-user/browser_console/index.html), which is not the standard Javascript console, but rather a hidden (behind an `about:config` flag) console which applies to the entire browser rather than just one tab. I haven't actually run that code, but even if it did work, Javascript on a webpage (ie Stash) cannot access the browser console, as it would be a massive security hole.

I don't think this issue is something fixable on the Stash end - it needs to be fixed (if deemed a bug, that is) by Firefox itself. For now you're going to have to upload the file directly, or just use another browser.

**Comment by UncleRoger33** [comment]
Thanks for the explanation, there is no need for a hammer to kill a fly. 

Using another browser seems the easiest workaround for now.
