### ISSUE TITLE
[Bug Report] SQL Error After Deleting Item

### ISSUE THREAD

**Issue by Flashy78** [stashapp/stash#3835]
If you create a studio or tag and then delete it, a subsequent call is made to `FindScenes` and passing in the just deleted id.
This fails with:

```
failed to get hierarchical values: error executing
`WITH RECURSIVE items AS ( SELECT id as root_id, id as item_id, 0 as depth FROM studios WHERE id in (?)
UNION SELECT p.root_id, c.id, depth + 1 FROM studios as c INNER JOIN items as p ON c.parent_id = p.item_id )
SELECT 'VALUES' || GROUP_CONCAT('(' || root_id || ', ' || item_id || ')') AS val FROM items\`
[[27]]: sql: Scan error on column index 0, name "val": converting NULL to string is unsupported
```
Sometimes it shows up in the log and sometimes it doesn't, maybe related to the page navigation after a deletion. Commenting out the navigation causes the error to always be displayed in the UI.
https://github.com/stashapp/stash/blob/develop/ui/v2.5/src/components/Studios/StudioDetails/Studio.tsx#L136

Confirmed in v.21 and latest develop.

**Comment by DogmaDragon** [comment]
Reproduced on https://github.com/stashapp/stash/commit/f65e87773c4b9fb053f4c5f23bcb77c03adbbccd.

**Comment by DingDongSoLong4** [comment]
This only happens when the scene tab is selected, because studio mutations and tag mutations only invalidate the `findScenes` query, which is arguably incorrect behaviour. Mutating a tag or a studio will impact the results of all `find...` queries which can have a tag or studio as a filter argument.

It also only happens when "Display subtag/sub-studios content" is enabled, or if you manually change the filter on the studio/tag page to include subsidiary studios/tags.

When you do this query
```gql
{
  findScenes(scene_filter: {
    studios: {value: 0, modifier: INCLUDES}
  }) {
    count
  }
}
```
it simply returns count 0, but this query
```gql
{
  findScenes(scene_filter: {
    studios: {value: 0, modifier: INCLUDES, depth: -1}
  }) {
    count
  }
}
```
returns the hierarchical error. This, in my opinion, is the issue - filtering for an invalid studio should just return nothing instead of an error.
