### ISSUE TITLE
[Bug Report] Task Queue status box no longer "live"

### ISSUE THREAD

**Issue by LeGrosFromage** [stashapp/stash#3847]
**Describe the bug**
In Settings, Tasks, when you perform an activity that would display progress in the Task Queue panel, that information is no longer displayed.  If you refresh while doing a task eg a library scan, information will display at the instant in time the refresh was done, but it won't update.

**To Reproduce**
1. Go to 'Settings', 'Task'
2. Click on 'Library Scan' or "Generate'
3. Scroll up to 'Task Queue'
4. Observe no status being displayed.  Refresh and you'll see some data but it's immediately stale and does not live update as it used to previously (all previous versions prior to 0.21.0).

**Expected behavior**
A live display of the current task being performed.

**Screenshots**
NA

**Stash Version: (from Settings -> About):**
v0.21.0
Build hash:
9180a68c

**Desktop (please complete the following information):**
 - OS: Windows, Linux, Mac
 - Browser: Vivaldi, Firefox, Chrome
 - Version: Latest

**Smartphone (please complete the following information):**
Not tried

**Additional context**
This has always worked prior to current lease.  While not exactly a show-stopper as bugs go, it can be handy to see where Stash is at in doing scans or image/vtt/sprite generation.

**Comment by DingDongSoLong4** [comment]
This can happen when the websocket connection isn't working, since that is used for live updating of things like the task list.

Can you open the browser devtools (F12) and see if there are any websocket-related error messages in the Console tab? Something along the lines of "WebSocket connection failed" or "can't establish a connection to the server at `ws://.../graphql`"?

I haven't noticed any issues myself, running on the latest development version. Can't reproduce running on build 9180a68 either.

If you're running stash behind a reverse proxy (nginx, apache, etc) then this a common issue, as special configuration is required for websockets to work. Check out the stash-docs page [here](https://docs.stashapp.cc/networking/reverse-proxy/) for recommended configurations.

**Comment by LeGrosFromage** [comment]
I did as you suggested and yes, I see a lot of this kind of thing:
```
Failed to load resource: the server responded with a status of 404 ()
index-16ac931a.js:2207 WebSocket connection to 'wss://stash.---redacted---/graphql' failed:
```

Now that I've seen that error and your note about Nginx, it did make me realize/remember that I just recently switched from hostname:9999 to stash.hostname via reverse proxy.  I'd forgotten I'd done that (it's all handled via my NAS) but then I wouldn't of thought there was correlation there.

Closing the ticket, thanks for the information @DingDongSoLong4.  File this one under PEBCAK.
