### ISSUE TITLE
Excessive database calls on various functions

### ISSUE THREAD

**Issue by Darklyter** [stashapp/stash#3891]
**Describe the bug**
While I haven't checked every function, I've noticed a large number of excessive database calls during at least two.

1) When saving a new performer in Tagger, a SELECT is called for every performer in the database after the new performer is saved.  In my case this means that over 20k selects are performed.  This is when the Performer is "Saved", so doesn't matter whether it's a new performer being created or matching one already in the database.

An example of the SELECT would be **_`SELECT 'performer_aliases'.'alias' FROM 'performer_aliases' WHERE ('performer_aliases'.'performer_id' = 1075), args: []`_**

2) When running **_`{allGalleries{id title scenes{id} files {path basename}}}`_** in the Playground, the query took over 10 minutes to complete.   This was for only 2,748 galleries in the database.  The execution also accounted for over 600 database calls, almost all of which were labelled as 'Slow SQL' in the logs.  This one I'm not sure if the calls are actually excessive or simply very slow

**To Reproduce**
To reproduce simply save a performer or run that query in the Playground with galleries in the database

**Screenshots**
Screenshots and further details are available on [Discord](https://discord.com/channels/559159668438728723/649346231482712099/1127669500830027806)

Supplemental logs are attached.  The logs were saved while no other Stash activities were occurring, and only contain the logs entries created during the execution of those two activities

**Stash Version: (from Settings -> About):**
Stash v0.21.0

**Desktop (please complete the following information):**
 - Ubuntu (Running in Docker on an 8th gen i7, 32gig, with an NVME drive)
 - Opera & Edge

[performer_save.txt](https://github.com/stashapp/stash/files/11998106/performer_save.txt)
[gallery_select.txt](https://github.com/stashapp/stash/files/11998107/gallery_select.txt)

**Comment by DingDongSoLong4** [comment]
The tagger causing many selects is likely because adding a new performer clears the entire frontend cache for the `AllPerformersForFilter` query, meaning that the query is re-run and thus data for every performer is fetched from the database again. Since we know how adding a new performer will affect the `AllPerformersForFilter` query beforehand, it should be possible to avoid the refetch.

That second query taking 10 minutes is strange. I've got 18,725 galleries and running the query in the playground only takes 3 seconds. Almost all of those galleries are zip based and have one attached scene.

Going off of the linked Discord messages, I think the cause of the slowdown is the fact that you've got ~228k scenes which is causing the `files`, `scenes_files` and `scenes` tables to be enormous, which means that queries on them will be enormous.

Theoretically neither `scenes_files` nor `scenes` need to be accessed for that specific query, since only the scene id is being requested there. I suspect fixing that is probably going to require fairly large backend reworking. This is probably where we approach the limits of good old SQLite.

**Comment by WithoutPants** [comment]
With the new selector changes in 0.25, I'm reasonably confident that this is addressed.
