### ISSUE TITLE
[Feature] Creating Multiple Libraries

### ISSUE THREAD

**Issue by 8ullyMaguire** [stashapp/stash#3899]
**Is your feature request related to a problem? Please describe.**
Currently, Stash only allows for a single library to be created. As the library grows in size, it becomes slow and difficult to browse.

**Describe the solution you'd like**
It would be great to have the ability to create multiple libraries within Stash. This would allow users to organize their content more efficiently and make browsing faster. Additionally, it would be helpful to be able to set a hierarchy so that a library can contain others. For example, there could be a global library that contains all the other libraries.

**Describe alternatives you've considered**
One alternative would be to create separate instances of Stash for each library. However, this would be cumbersome and inefficient.

**Additional context**

**Comment by stg-annon** [comment]
the way stash stores data in SQLite would likely mean that any additional library would need its own DB file which would essentially mean another instance of Stash if you want to access them concurrently, the amount of effort it would take to make this not the case, just on the database side of things, would be immense

I don't realistically see this happening, however a system that would make hosting multiple instances of Stash easier I could see it would likely sit in front of Stash and  handle the different ports/configs/paths much like a reverse proxy

**Comment by 8ullyMaguire** [comment]
If it's too difficult, we can simply ask the AI to do it when it becomes capable enough. I wouldn't like multiple Stash instances because then there would be no way to search globally if needed.

**Comment by stg-annon** [comment]
If all you want is multiple dirs to be available in Stash and to filter among them this could be accomplished with a path filter to only give you scenes from that library path, the ability to add multiple library paths already exists

something like this
![image](https://github.com/stashapp/stash/assets/14135675/dd161cdd-b0ce-4d78-8860-432bafe0ea5c)

**Comment by echo6ix** [comment]
> The main reason I want something like libraries is primarily because the search has become slower as the number of scenes has increased. Creating filters doesn't seem to make the search any faster. Is there a way to partition the Scenes table based on paths or tags and only search within a subset?

How many scenes do you have?

**Comment by ALonelyJuicebox** [comment]
Agreed with @echo6ix -- If the root goal of this request is _performance_, can you help to quantify that a bit?
- How many scenes are in your Stash?
- Can you describe the hardware that Stash is running on? (CPU, hard drive, etc)
- What's an example of query you're trying to run? Just a phrase? Or is it inclusive of several additional filters? 
- How long does that query take to run?

I don't even necessarily see how multiple Stash databases would help here if performance is the goal

**Comment by 8ullyMaguire** [comment]
- 300k scenes
- Hardware

Type|Item|Price
:----|:----|:----
**CPU** | [AMD Ryzen 7 5700G 3.8 GHz 8-Core Processor](https://es.pcpartpicker.com/product/ycGbt6/amd-ryzen-7-5700g-38-ghz-8-core-processor-100-100000263box) | €220.00 
**CPU Cooler** | [Scythe Ninja 5 43.03 CFM CPU Cooler](https://es.pcpartpicker.com/product/dZ3H99/scythe-ninja-5-4303-cfm-cpu-cooler-scnj-5000) | €62.00 
**Motherboard** | [Gigabyte B450M DS3H Micro ATX AM4 Motherboard](https://es.pcpartpicker.com/product/hpRzK8/gigabyte-b450m-ds3h-micro-atx-am4-motherboard-b450m-ds3h) | €66.00 
**Memory** | [Corsair Vengeance LPX 32 GB (2 x 16 GB) DDR4-4000 CL18 Memory](https://es.pcpartpicker.com/product/pp848d/corsair-vengeance-lpx-32-gb-2-x-16-gb-ddr4-4000-memory-cmk32gx4m2z4000c18) | €173.49 @ Amazon Espana 
**Storage** | [Crucial P2 500 GB M.2-2280 PCIe 3.0 X4 NVME Solid State Drive](https://es.pcpartpicker.com/product/G9XYcf/crucial-p2-500-gb-m2-2280-nvme-solid-state-drive-ct500p2ssd8) | €45.00 
**Case** | [Corsair Carbide Series 100R ATX Mid Tower Case](https://es.pcpartpicker.com/product/PzM323/corsair-case-cc9011077ww) | €64.95 
**Power Supply** | [Corsair RM1000i 1000 W 80+ Gold Certified Fully Modular ATX Power Supply](https://es.pcpartpicker.com/product/w9Jkcf/corsair-power-supply-cp9020084na) | €70.00 
 | *Prices include shipping, taxes, rebates, and discounts* |
 | **Total** | **€701.44**
 | Generated by [PCPartPicker](https://pcpartpicker.com) 2023-07-12 20:16 CEST+0200 |

- A simple word query without any filters takes around a minute.

**Comment by DingDongSoLong4** [comment]
The hardware likely makes very little difference here, apart from the SSD and non-ancient CPU. The slowdown is the enormous number of scenes, and SQLite not being able to cope with the sheer volume.

Splitting storage into individually searchable libraries will definitely help, but that would require a large part of the backend to be reworked, and will probably also negatively impact searching the "global library" as you put it. I might be wrong, but I think for many users (myself included) the ability to search an _entire collection_ for many different kinds of specific things (tags, studios, performers, etc) is what makes Stash useful.

FYI a word query is probably one of if not the most difficult query type for the database to handle, because it needs to search for your word for any of several database columns (title, details, filename, ...) and in your case it needs to do that 300 000 times - it's no wonder it's slow.

**Comment by stg-annon** [comment]
question is if the text query is being applied after the filters or not as that may help here as well, good test may be to get a filter that applies to say 10K scenes then search that to see the performance difference, looks like there is an effort to potentially allow other DB backends so that may resolve this as well
