### ISSUE TITLE
[Feature] Modify the location of the tag image/description box on hover

### ISSUE THREAD

**Issue by ALonelyJuicebox** [stashapp/stash#3911]
**Challenge** 
When the feature `Display Tag Description & Tag Image on hover` (https://github.com/stashapp/stash/issues/2575) was implemented, it was implemented such that the window that appears on hover appears directly **above** the object the user is mousing over. 

This unfortunately leads to elements of the Edit page/Details page being hidden during regular use. (As seen in the example below)
Ordinarily this might be something worth addressing with custom CSS but unfortunately this will likely need to be addressed in react. 

**Proposed Solution**
I'd like to request that the tag description box be displayed to the right of the element and on top of the scene itself-- similar to the initially proposed UX.

_Current State_
![reposition](https://github.com/stashapp/stash/assets/76471868/165a5ddd-e070-405a-a72c-5980b9880a28)

_Ideal State_
![StashIdeaForTagHover2](https://user-images.githubusercontent.com/76471868/167505141-07f57097-8311-4872-a31e-f213cd8b0642.png)

Thanks! 🙂

**Comment by Flashy78** [comment]
It seems like this is a one line change from `top` to `right`.
However it will still attach directly to the tag in the Scene Details tab, so it will still cover parts of it if the tag is on the left side.

Are you saying it should always display overtop of the video player? If so it looks ok if the tag is near the right hand side, or in the Edit select box, but looks pretty funny if the tag is on the left side resulting in a large empty gap, with the popup seeming to appear out of nowhere.

**Comment by ALonelyJuicebox** [comment]
Is there a chance you can post a screenshot of how intense the empty gap is? Honestly...I'll take an empty gap over hiding fields any day. 😅

**Comment by WithoutPants** [comment]
This placement in the select box list has irritated me since adding the feature. I consider that current behaviour a usability issue and a bug. 

The placement for the tag links not so much an issue imo, since it's an optional user interaction - whereas the select box, you _have_ to hover to select something. More on this below.

We can't really just replace the placement everywhere, since `top` is really the only place we can guarantee has room to display the popover. 

I think the short-term solution is to change the hover placement to `right` on the select control of the edit pages only. That addresses the immediate usability issue. For a more permanent solution, I propose adding the tag's image to the select box items as a small icon on the left side. Hovering over the icon will show the popover above (as per current behaviour). This means that the UI will not be occluded by the popover when selecting a tag.

**Comment by WithoutPants** [comment]
$51 bounty placed ([#676327](https://opencollective.com/stashapp/contributions/676327))
