### ISSUE TITLE
[RFC] Autotag wildcard

### ISSUE THREAD

**Issue by teogolang** [stashapp/stash#3914]
my tags are not being recognized automatically due to naming and connected words and/or special characters

suppose tag "anime"

these are not matched files:
bestanime.mp4
4kanime.mp4
..

can we make tags with wildcard like in windows search? would be a huge time saver
when I try to add *anime as tag doesn't detect at all

**Comment by echo6ix** [comment]
I am not sure yoru title matches what you are requesting. If I understand correctly, you're essentially asking for a class of tags that contain regular expressions which are matched against the library during an auto tag. If so you might want to rename to something like _Regular expression tags_?

I haven't used PornVault in years but the dev implemented this when I requested it before scrapers were a thing. It was useful for precision auto tagging edge cases like yours or auto tagging a pattern against multiple criteria, such as specific non-unique single name performer associated with a specific studio, `(name.*studio|studio.*name)`.

Tag type|Syntax|Examples
---|---|---
string|string|`anime`
regex|regex:pattern|`regex:anime`, `regex:(cars?\|automobiles?\|suvs?)`, `regex:superhero.*marvel\|marvel.*superhero)`

---
Otherwise in Stash, I think you should just be able to search for `anime` and it will return all scenes in your library containing the string `anime` in your file path. Then bulk add the anime tag.

Another way, using regex if you required a more complex regular expression against the file path would be: Scenes > Filter > `Path matches regex _______`

**Comment by teogolang** [comment]
> I am not sure yoru title matches what you are requesting. If I understand correctly, you're essentially asking for a class of tags that contain regular expressions which are matched against the library during an auto tag. If so you might want to rename to something like _Regular expression tags_?
> 
> I haven't used PornVault in years but the dev implemented this when I requested it before scrapers were a thing. It was useful for precision auto tagging edge cases like yours or auto tagging a pattern against multiple criteria, such as specific non-unique single name performer associated with a specific studio, `(name.*studio|studio.*name)`.
> 
> Tag type	Syntax	Examples
> string	string	`anime`
> regex	regex:pattern	`regex:anime`, `regex:(cars?|automobiles?|suvs?)`, `regex:superhero.*marvel|marvel.*superhero)`
> Otherwise in Stash, I think you should just be able to search for `anime` and it will return all scenes in your library containing the string `anime` in your file path. Then bulk add the anime tag.
> 
> Another way, using regex if you required a more complex regular expression against the file path would be: Scenes > Filter > `Path matches regex _______`

Interesting, I was able to search and find them but how to bulk tag? I was able to scrape and find some (not all) but I have to click save on every single file matched

**Comment by echo6ix** [comment]
> but how to bulk tag?

I'm assuming you mean manually bulk tagging.

1. Selecting the items to bulk tag
  a. Method 1 (selective bulk tagging). When you hover your moue over a scene card you will notice on the top left corner of the card a checkbox appears. Click the checkbox of the first item you want to bulk tag. For all subsequent items you want to bulk tag you can click anywhere on the scene card.
  b. Method 2 (mass bulk tagging). In the toolbar area, click the horizontal overflow button. Click _Select All_ from the dropdown menu. This will automatically select all your scene cards on the page.
![image](https://github.com/stashapp/stash/assets/37937507/9a55e6b7-8f31-4d28-95bd-cc77bc1059fe)

2. Now that you have the desired scenes selected to bulk tag you you will click the pencil icon in the toolbar area to open the *Edit Scene* modal window for tagging
![image](https://github.com/stashapp/stash/assets/37937507/44c169c8-03a8-4c78-b650-1f9e2fcb5405)
