### ISSUE TITLE
[Feature] Image Clips animated preview for wall view

### ISSUE THREAD

**Issue by Dankonite** [stashapp/stash#3993]
**Is your feature request related to a problem? Please describe.**
Now that image-clips (short videos) are able to be identified as images, using the image tab wall view no longer has a way to play them as animated previews like in the scene and marker wall views.

**Describe the solution you'd like**
in the interface panel adding a dropdown for image clips in the image wall view to be animated like scenes and markers. 

**Describe alternatives you've considered**
I use them for short 60s max videos, playing them outright might eat up alot of performance, but also generating previews might not make sense for all of them. might have to have a generate function for them to be easier to display on wall view.

**Additional context**
open to opinions

**Comment by yoshnopa** [comment]
This is already possible and one reason for me to implement this feature!
By default, you will see a stillframe. This is due to the Capacity needed on the server to generate a preview of a video contrasted to the power needed to only generate a single frame. Thats why only the latter is done on the fly. 
To generate a preview of the video used then on the wall view, you have an option to do while scanning for new images (which will then get the according support files generated) by toggling the "Generate previews for image clips" in the library section, right below the scan button.
For your already scanned items, you can generate them by going to the "Generated Content" section in tasks, toggle "Image Clip Previews", and click generate.
Please refer to the manual for more information (Questionmark top right, section "Images and Galleries").

If that doesn't help, please give feedback. Otherwise please close this issue.
