### ISSUE TITLE
[Bug Report] Scene: input: Scene Internal system error.

### ISSUE THREAD

**Issue by ConstantMoo** [stashapp/stash#4072]
Hi there,

Like #4030, after upgrading to v0.22.0, attempting a sceneUpdate Mutation from the API results in the following error in the stash logs:

```
23-08-30 17:38:08Error   Scene: input: Scene Internal system error. Error <runtime error: invalid memory address or nil pointer dereference>
2023-08-30 17:38:08Error   runtime error: invalid memory address or nil pointer dereference
```

As a result, the scene doesn't update its data (performers, studio, title, etc). However, the API responds a OK status code to the client.

I upgraded to v0.22.1 but the issue is still here. Note that I didn't change anything to my client sceneUpdate call code. I only updated Stash from v0.21.0 which was working.

**Comment by MrX292** [comment]
that works correctly for me.
can you maybe post the call you are making?

**Comment by ConstantMoo** [comment]
Sure! Here's my code of the call. Note that client code is C# using GraphQL Nuget Package:

```
var Mutation = new GraphQLRequest
{
    Query = @"mutation ($inputscene: SceneUpdateInput!) {
                Scene: sceneUpdate(input : $inputscene)
                {
                    id,
                    title,
                    url,
                    details,
                    organized,
                    date,
                    studio {id name},
                    performers { id name }
                }
              }",
    Variables = new
    {
        inputscene = new
        {
            id = SceneToUpdate.Id,
            title = SceneToUpdate.Title,
            details = SceneToUpdate.Details,
            url = SceneToUpdate.URL,
            date = SceneToUpdate.Date,
            studio_id = SceneToUpdate.StudioID,
            performer_ids = PerformersIDToUpdate,
            organized = SceneToUpdate.Organized,
        }
    }
};
var Response = await this._client.SendMutationAsync<GQLResponseScene>(Mutation);
```

**Comment by Flashy78** [comment]
It looks like url has been depcrecated and replaced with urls.
https://github.com/stashapp/stash/blob/develop/graphql/schema/types/scene.graphql#L126

It should still work, but maybe try updating your code to a list of urls and see if it works?

**Comment by ConstantMoo** [comment]
Ah I see. Temporary removing the `url` field from my query seems to make it work. I'll have to update my code to support the array of urls. However, I'd argue that the API shouldn't reply OK if the input was using a deprecated field and results in an internal system error.

**Comment by DingDongSoLong4** [comment]
Minimal reproducible graphql query:
```gql
mutation {
  sceneUpdate(input: {
    id: 1,
    url: null,
  }) {
    id
  }
}
```

The issue is here: https://github.com/stashapp/stash/blob/8abb3c0d0868647d09698099d6c999505277e18e/internal/api/resolver_mutation_scene.go#L202-L207
and happens because `translator.hasField("url")` can return `true` even if `input.URL` is `nil`.

@WithoutPants should a `url: null` input clear the URL list, or should it simply be ignored? I'd lean towards ignoring it, but just wanted to check. The fix is straightforward either way.

This same bug also happens with the `aliases` field on the `performerUpdate` endpoint, and the fix would be the same.

Regarding the API replying OK (200) - this is correct behaviour, and is simply how a graphql server works. Since you can request multiple bits of data in a single HTTP request, if an error occurs on only one of those requests, it doesn't make sense to return a failure code for the entire request. When checking whether the request failed, you need to look at the `errors` field in the returned JSON object, not the HTTP status code.

**Comment by ConstantMoo** [comment]
Thanks for the findings! My client may indeed send null values, and that was the case for the url of the scene it was trying to update.
I agree that it should be ignored if the value is null, it's much simpler to implement and avoid unintentional data loss on the client side.

**Comment by WithoutPants** [comment]
> @WithoutPants should a `url: null` input clear the URL list, or should it simply be ignored? I'd lean towards ignoring it, just to minimize unintentional data loss, but just wanted to check. The fix is straightforward either way.

This should be consistent with the other behaviour in the API. For other fields, if a field is present but `null`, then it is considered clearing the field. That's what it should be here as well.
