### ISSUE TITLE
[Feature] Custom default sorting

### ISSUE THREAD

**Issue by zhgwn** [stashapp/stash#4137]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open the video tab, and I need to change the page size and the sorting method to be the way I like.

**Describe the solution you'd like**
I would like an option to set current page size / sorting / display / filter on each tabs (videos, galleries, movies, ...)

**Comment by MrX292** [comment]
You can set default filters for the different tabs.

**Comment by Dankonite** [comment]
if you click set as default on the filters button it will save page layout and sorting. for instance I have a no stash id filter that opens tagger view automagically. if you dont set a name it will just be applied by default every time you go to that page. with the exception of performer and tag pages because they dont support filters iirc
