### ISSUE TITLE
[RFC] Changing image storage from DB blob to file system

### ISSUE THREAD

**Issue by Anon247** [stashapp/stash#425]
## Scope
The goal of this would increase the performance of the server and database by separating the image data from the database itself and instead provide file paths to the image files in the database. 

There are definitely debates to be had over whether:
- a file system solution would be faster for the size of images
- the trade-offs (losing ACID on files) are worth it
- it's a good decision to change something that already works for increased performance, potentially only noticed by a small number of users

From my reading, it seems if the files being stored are over 1MB, it would be more efficient to use file system storage.

 [This article from SQLite](https://www.sqlite.org/intern-v-extern-blob.html) suggests that files over 100KB in size would be faster read from the file system rather than the database.

## Reference Reading
https://www.sqlite.org/fasterthanfs.html
https://www.sqlite.org/intern-v-extern-blob.html
https://dzone.com/articles/which-is-better-saving-files-in-database-or-in-fil
https://dba.stackexchange.com/questions/120091/why-do-large-images-stored-in-database-hurt-performance
https://www.microsoft.com/en-us/research/publication/to-blob-or-not-to-blob-large-object-storage-in-a-database-or-a-filesystem

**Comment by InfiniteTF** [comment]
I think it's worth doing, not necessarily because of performance, but to save us from the maintenance involved with storing images in multiple places. If they're all on the filesystem that's easier to manage, both for  stash devs, and for anyone scripting directly against the database.

**Comment by bnkai** [comment]
I'm a little hesitant ( i make backups of the sqlite database file directly and that adds one more step to my backup process ) but i wouldn't mind that much. The changes needed also are quite extensive so  i also don't know if it's trully worth it.
If implemented though i would prefer to have a seperate folder structure than the generated metadata so that you we can differentiate between data we can regenerate  if needed and data we must backup ( custom scene cover , movie , perfomer and studio images ). 
It would also be beneficial to make more subfolders so that we don't end up with 40k+ files in a single folder like screenshots is now (the  way squid stores it's cache might be a good choice  http://etutorials.org/Server+Administration/Squid.+The+definitive+guide/Chapter+13.+Log+Files/13.3+store.log/ ).

**Comment by WithoutPants** [comment]
Recent investigations (#478, #475) have discovered that the presence of blobs severely impacts query performance, since many of the queries get all columns.

One possible alternative might be to move these blobs into one or more separate tables. This should alleviate performance issues by ensuring that image blobs are only queried for when explicitly needed.

**Comment by bnkai** [comment]
I think moving into separate tables is a good compromise. It is can be implemented easier and the performance improvement should be good enough. Also migrations would go faster.
