### ISSUE TITLE
[Bug Report] Stash won't open in Quest 2 (any browser)

### ISSUE THREAD

**Issue by brachna** [stashapp/stash#4357]
**Describe the bug**
Stash page does not open in Quest 2.
Tried with Meta Browser, Wolvic, sideloaded Brave, DeoVR.

**To Reproduce**
1. Launch Stash server on host machine
2. Open any browser in Quest 2
3. Open http://192.168.1.33:9999
4. It won't open

**Expected behavior**
Stash opens in Quest 2

Stash Version: v0.23.1-71-geca5838c (nightly as of writing this issue, but latest stable didn't work either)

**Desktop (Host):**
 - OS: Windows 10

**Client**
 - Device: Meta Quest 2
 - Firmware: [60.0]
 - Browser [Meta Browser, Wolvic, sideloaded Brave, DeoVR]
 - Version [all latest]

**Additional context**
On my smartphone (Android 10) I can't open Stash either. However it does open after using duckdns and caddy (so https://mystashaddr.duckdns.org does open it).
Quest 2 however won't open even that. Is it related to certificates and Android 12 being strict with them?
But then I wonder how Navidrome works like a charm. Navidrome works fine on http://192.168.1.33:4533 on both smartphone and Quest 2.

**Comment by DingDongSoLong4** [comment]
By "it won't open", do you mean it gives a "connection failed" or "unable to connect" error, or does it successfully load but give a blank page?

If it's the former (a connection error), then the problem is almost certainly with your network setup, and it's unlikely to be an issue with Stash itself. Given that you seem to be having issues with opening Stash on your phone as well, it's even more likely to be a network issue.

If it's the latter (a blank page), then it could be that the browser is too old and doesn't support certain Javascript features, but that seems unlikely given that the Quest 2 was released relatively recently, and that it isn't working on multiple browsers. Browser incompatibility is usually only an issue on old Smart TVs that have long since stopped receiving software updates.

Either way, I'd recommend joining the [Discord server](https://discord.gg/2TsNFKt) and asking in #help - it will be much easier to troubleshoot and figure out the cause than here on GitHub.

**Comment by brachna** [comment]
It's a connection error, not blank page.

Current workaround for me is using ADB:
adb shell ip route
#xx.x.xx.x/19 dev wlan0  proto kernel  scope link  src 192.168.1.36
adb tcpip 5555
adb connect 192.168.1.36:5555
adb reverse tcp:9999 tcp:9999

Now Stash can be accessed as http://localhost:9999 in Quest 2

**Comment by brachna** [comment]
Solved. It was Windows firewall.
