### ISSUE TITLE
[Feature] Opt-in video comments metadata -> details

### ISSUE THREAD

**Issue by QxxxGit** [stashapp/stash#4392]
I use yt-dlp often, and with the commands `--add-metadata` and `--parse-metadata`, I'm able to add the description of a video to the comments field of a video's metadata. It would be nice if Stash would add it to the details field.

I'm pretty confident it used to work this way natively, as I have multiple scenes with their details filled by the comments metadata in their video files. From a little digging, these scenes were created in late 2021 -- so maybe it worked around then and something changed.

In case it could potentially cause conflicts somewhere, it might be ideal to have an opt-in setting.

**Comment by DingDongSoLong4** [comment]
This was indeed a feature once, but it was deprecated as it was not ported over during the files refactor (in v0.17).

From #2743:
> - deprecated useFileMetadata and stripFileExtension scan options. These are probably better suited as scrapers, plugins or scripts.

`useFileMetadata` was the scan option that enabled the feature you're referring to. I think I agree with the reasoning given for the deprecation - a scraper that pulls from file metadata would be more versatile than something built into the scan task. You'd be able to set metadata at any time, rather than only during the initial scan, for example.

I don't know if someone has already written such a scraper, so you might have to write it yourself. I'm sure there are many python libraries to get every possible kind of metadata out of a video file though, so I don't think it should be too difficult.

**Comment by QxxxGit** [comment]
Thanks for the info. In that case, I'll close this request. I'll consider writing a plugin after thinking on it.
