### ISSUE TITLE
[Bug Report] Video player frequently loads queued scene with the volume muted

### ISSUE THREAD

**Issue by Thurlam** [stashapp/stash#4436]
**Describe the bug**
The video player sets itself to mute on scene load.

**To Reproduce**
View a scene that is part of a queue, and then select a new video from that queue to load (player buttons, autoplay, and manual scene select all work). Reloading the page works as well. It will load with the volume set to mute, for some reason...very frequently, but not always. I have yet to discern the pattern as to when it works properly.

**Expected behavior**
I expect it to only be set to mute when I manually mute it myself.

**Stash Version: v0.24.1**

**Desktop:**
 - OS: Windows 10
 - Browser: Edge
 - Version: 120.0.2210.91

**Additional context**
Volume is still saved, for the record; unmuting returns it to the desired volume.

**Comment by WithoutPants** [comment]
I'm not able to reproduce this. The volume persistance is stored in the browser's local forage, which you can view in the dev tools (F12), Application tab under `IndexedDB -> localforage -> keyvaluepairs`. Take a look at the `volume-muted` value, using the refresh button to update the values as you click through to scenes. Those values should only be changed when changing the volume, so I can't imagine why they'd be muting randomly.

**Comment by DingDongSoLong4** [comment]
My guess is this: https://github.com/stashapp/stash/blob/95a2c8d13fa2ec9591b55908ffb79c71c10c7428/ui/v2.5/src/components/ScenePlayer/ScenePlayer.tsx#L770-L776

Which mutes the player before retrying if an autoplay fails, because browsers often block or can be configured to block non-muted autoplay. However this does have the side-effect of ending up with a muted player. It could also happen if the player fails to play for some other reason.

In hindsight I think it's probably better to just fail the first time and not retry muted. I'll make a PR.

**Comment by Gitoilet** [comment]
Experiencing the same behavior, but in very particular circumstances.

_Start with no cache, create a queue. Initial scene will load with full volume and unmuted._ Clicking next results in different behavior:

1) Sometimes the next scene is loaded, but it's muted. Maintains the last volume setting, it's just muted.
2) Otherwise, next scene is loaded with same volume level, unmuted (expected behavior).

I randomly loaded a few different queues and went scene by scene, and eventually, a scene would come up that would be muted. From that point forward, all scenes that follow it in the queue are muted. Unmuting results in expected behavior, until it finds another scene that triggers the muting. Entire time, cache shows that `volume-muted: false`.

Seems like something involving scene data, but codecs are no different from scene to scene.

**Comment by DingDongSoLong4** [comment]
@Gitoilet that sounds exactly like what I imagine would happen if the player "fails to play for some other reason" - ie it's failing to play, but not because the browser blocked it.

When the CI build on #4450 finishes (should be done in ~5 minutes), can you test the built binaries and see if you still get the issue? They'll be at https://github.com/stashapp/stash/actions/runs/7482635653 under Artifacts.

**Comment by Thurlam** [comment]
I think that did the trick. I haven't been able to reproduce the bug when using that build. Given it was happening with startling regularity before, I'm pretty sure it's fixed. Great work, thanks :)

also can confirm that the volume-muted value stayed set to 'false' the whole time when the bug was occurring, for what it's worth.
