### ISSUE TITLE
[Bug Report] Stash seems to ignore alias and disambiguation for performers when autotagging. 

### ISSUE THREAD

**Issue by ecto1a2003** [stashapp/stash#4519]
**Describe the bug**
Stash seems to ignore alais and disambiguation feilds for a performer when autotagging, tags, and studios do this fine.

**To Reproduce**
1. add alias to performer
2. have or crated file that only has that alias in its path
3. perform full or partial autotag
4. ignored

**Expected behavior**
Id expect similar behavior to tags or studios, some performers have gone by dulitple differrnt names and also have common misspellings

**Screenshots**

**Stash Version: (from Settings -> About):**

v0.24.3
Build hash:
aeb68a58
Build time:
2024-01-15 00:32:38

**Additional context**
Happens for existing and new performers.

**Comment by echo6ix** [comment]
This isn't a bug, it's intended behavior.

**Comment by ecto1a2003** [comment]
I see, is that expected to change? What should i do?

**Comment by HereIam80** [comment]
I don't know your use-case but 90% of the time auto-tag is not the tool you want to use.
Here is what we recommend to get your metadata: https://docs.stashapp.cc/beginner-guides/guide-to-scraping/

**Comment by ecto1a2003** [comment]
A manual process. Fun

**Comment by DogmaDragon** [comment]
Auto Tag has limitations with current implementation, and performer aliases is one of them. Replacing Auto Tag with an equivalent or better plugin is part of the long term roadmap for Stash. 

As far as alternatives, using Tagger is the recommended method, since it allows verifying the information before saving it, but if you prefer automatic tasks there is [Identify](https://docs.stashapp.cc/in-app-manual/tasks/identify/).

**Comment by ecto1a2003** [comment]
Oh interesting, doesn't help with alot of my material. Is identify smart enough to asis with the alias issue. For instance ammo and amouranth are the same perfomer but id ha e to make 2 perfomers currently

**Comment by ecto1a2003** [comment]
Is there a long term roadmap posted somewhere?

**Comment by DogmaDragon** [comment]
How do you determine it's the same performer? It can be a different performer with the same name, or even multiple performers using those names.

Common aliases need a reference point to associate with for them to be able to be match to a specific profile. 

I would recommend checking [different stash-box instances](https://guidelines.stashdb.org/docs/faq_getting-started/stashdb/accessing-stash-boxes/) that try to solve this problem by matching based on [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) instead of unreliable names. 

---

Roadmap is only a rough draft at this point.
[![image](https://github.com/stashapp/stash/assets/103123951/f9a39c46-a321-4d3c-a6e5-2a4d5246ea2e)](https://discord.com/channels/559159668438728723/645283324071247911/1197013453198598298)

**Comment by ecto1a2003** [comment]
Typically empornium tags, ill grab everything for one perfomer and they'll have had different names of the files will have comon misspellings. 

Heather harmon and heather brooke is the classic example.

**Comment by DogmaDragon** [comment]
Their synonym tags are also managed and associated manually. Like I said, you need a reference point to know if the association matches the one you want to apply it to, it doesn't happen automatically.

**Comment by ecto1a2003** [comment]
I understand, i was just hoping for functionally similar to tags to help with differences in spelling, names, aliases and the like. Now i have to process everything by hand and hope stash db even has it. If it doesn't, and i have a lot of amatuer content, i have to take care of all those issues by hand. 

Kinda feels like going to a library and theres lists of all the books by their attitbites ( color page count size) but none for author or title

Ill trudge along i guess. Not like thers a better option

**Comment by DogmaDragon** [comment]
Auto Tag only works with objects that are already created, it doesn't create new ones. So if you create those misspellings yourself, it wouldn't solve your issue even if it recognized aliases. 

For amateur stuff you can give a try FansDB stash-box instance which is focused around independent creators.

All libraries had to be managed by someone first for others to be able to take advantage of that categorization, it doesn't happen automatically. 

There is also a [scraper that can scrape .torrent files](https://github.com/stashapp/CommunityScrapers/tree/master/scrapers/torrent) which have embedded metadata.

**Comment by ecto1a2003** [comment]
This is all very cool, i just wish it was as automagic as autotag
