### ISSUE TITLE
[Bug Report] stash-win.exe not refreshing python path on first boot

### ISSUE THREAD

**Issue by feederbox826** [stashapp/stash#4859]
**Describe the bug**
stash-win.exe will not respect or look into the python path on first boot

**To Reproduce**
1. run stash-win.exe
2. go through setup
3. set python.exe path to fake exe
4. No `using configured python path: ...` in trace log

**Expected behavior**
stash-win.exe takes python-path on first boot

**Screenshots**
N/A

**Stash Version: (from Settings -> About):**
0.5.2

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Originally from https://github.com/stashapp/stash/issues/4856
Troubleshooting in [discord](https://discord.com/channels/559159668438728723/559159931505213440/1241994657223675954)

While this has a "resolution" I belive this behaviour is still unintentional

**Comment by WithoutPants** [comment]
Documenting this now as I'm out of time to work on it today:

Funnily enough, this doesn't manifest if you compile stash with go version 1.22. My initial tests couldn't reproduce this. It was only when I tried using the release binaries, or used go version 1.19.3 that I could reproduce it.

There's a couple of issues going on that will need cleaning up, but the summary is that `plugin.Config.getExecCommand` is overwriting its `Exec` slice instead of modifying a copy to return - this explains the growing path that occurs on repeated runs. Additionally, it looks like the behaviour of `exec.LookPath` has changed slightly between 1.19.3 and 1.22 such that the former is _not_ returning an error while the latter (I think) is. The behaviour when it doesn't return an error is strange and likely incorrect.

**Comment by feederbox826** [comment]
> I didn't document it in the issue, but try running `PATH='' stash`

Copied from discord, left here for prosterity
