### ISSUE TITLE
[Feature] Hardware transcoding on macOS (VideoToolbox)

### ISSUE THREAD

**Issue by honeybeaver** [stashapp/stash#4945]
**Is your feature request related to a problem? Please describe.**

In connection to this feature in the 0.26.0: 
> When enabled, full hardware transcoding is used where possible. (https://github.com/stashapp/stash/pull/4765)

I tested this on a Mac with Apple Silicon. It appears ffmpeg HW transcoding does not use VideoToolbox on Mac yet, when streaming media. 

**Describe the solution you'd like**

When on macOS, test & use these flags in ffmpeg to enable HW transcoding using VideoToolbox (from [ffmpeg docs](https://trac.ffmpeg.org/wiki/HWAccelIntro#VideoToolbox)):

> To use H.264/HEVC hardware encoding in macOS, just use the encoder `-c:v h264_videotoolbox` or `-c:v hevc_videotoolbox` for H.264 or HEVC respectively. 

**Describe alternatives you've considered**

Without hardware acceleration, software transcoding works on the CPU. In most cases though, transcoding takes a lot CPU time, either making it not possible to transcode quickly enough (rare) or affecting other apps running on the machine (common). 

**Additional context**

This may also apply to decode and other times ffmpeg is converting media, such as scan and previews, and not just streaming. 

Intel Macs also use this method to access hardware encoding. 

Searching the code, it does not look like VideoToolbox appears anywhere yet, and I didn't see a full discussion of this case in other HW transcoding discussions.

Thank you!

**Comment by feederbox826** [comment]
The referenced full hardware transcoding is for NVIDIA cards only - I don't belive stash has a check for VideoToolbox support at all

**Comment by NodudeWasTaken** [comment]
Unfortunately scale_vt (videotoolbox) currently doesn't call ff_scale_adjust_dimensions, meaning it cannot scale with respect to the aspect ratio unless i insert some hacks or refactor how that's done.
> The referenced full hardware transcoding is for NVIDIA cards only - I don't belive stash has a check for VideoToolbox support at all

The referenced full hardware transcoding is enabled for NVIDIA, Intel and VAAPI.

**Comment by m13v** [comment]
We use VideoToolbox extensively in Fazm for encoding screen recordings on macOS. Here are the flags that work well for us:

For HEVC hardware encoding:
- `-c:v hevc_videotoolbox -q:v 65 -tag:v hvc1` gives good quality at reasonable file sizes
- On Apple Silicon, `hevc_videotoolbox` is significantly faster than on Intel. M1+ chips have dedicated ProRes/HEVC encode blocks that run independently of the GPU

For hardware decode + encode pipeline:
- `-hwaccel videotoolbox -c:v hevc_videotoolbox` enables both hardware decode and encode, keeping frames in GPU memory and avoiding CPU copies
- This is particularly important for transcoding: without hardware decode, frames get decoded on CPU, uploaded to GPU for encode, which bottlenecks on the memory bus

A few gotchas:
1. VideoToolbox H.264 encoder (`h264_videotoolbox`) has a session limit. If stash is transcoding multiple streams simultaneously, you will hit a `-12902` error when the limit is reached. HEVC has the same limit but it is slightly higher on newer hardware.

2. On Intel Macs with AMD GPUs (like the Sunshine issue above), the hardware encoder is on the Intel Quick Sync block, not the AMD GPU. If Quick Sync is not available (Mac Pro with only AMD GPU, no iGPU), hardware encoding is not possible and you need to fall back to software.

3. For scan/preview generation, hardware decode alone (without re-encoding) gives a big speedup. `-hwaccel videotoolbox` on the input side, with software encoding for thumbnails, is often the best approach since thumbnail encoding is trivially fast.

This would be a great addition to stash for macOS users.

**Comment by m13v** [comment]
Our open-source video encoder that uses VideoToolbox for HEVC encoding is here. It shows the session setup, quality parameters, and chunk-based encoding pipeline:

https://github.com/m13v/macos-session-replay/blob/main/Sources/SessionReplay/VideoChunkEncoder.swift
