### ISSUE TITLE
[Bug Report] Error when running any tasks from PHash Duplicate Tagger

### ISSUE THREAD

**Issue by Plop** [stashapp/stash#5020]
**Describe the bug**

Logs output when running any tasks for PHash Duplicate Tagger give me an error :
```

ERRO[2024-06-26 20:59:19] [Plugin / PHash Duplicate Tagger] Traceback (most recent call last): 

ERRO[2024-06-26 20:59:19] [Plugin / PHash Duplicate Tagger]   File "/root/.stash/plugins/community/phashDuplicateTagger/phashDuplicateTagger.py", line 281, in <module> 

ERRO[2024-06-26 20:59:19] [Plugin / PHash Duplicate Tagger]     for name, func in getmembers(config, isfunction): 

ERRO[2024-06-26 20:59:19] [Plugin / PHash Duplicate Tagger]                                  ^^^^^^ 

ERRO[2024-06-26 20:59:19] [Plugin / PHash Duplicate Tagger] NameError: name 'config' is not defined 

ERRO[2024-06-26 20:59:19] Plugin returned error: exit status 1         
```

**To Reproduce**
1. Go to 'Settings' > 'Tasks' > 'Plugin tasks'
2. Click on any tasks under "PHash Duplicate Tagger"
3. See error in container logs

**Expected behavior**

No error and tasks running fine

**Stash Version: (from Settings -> About):**

v0.26.1
Build hash:
d1998cb5
Build time:
2024-06-10 00:23:10

PHash Duplicate Tagger (0.1.4)

Running on Docker Container

Thanks for the help :)

**Comment by Maista6969** [comment]
Probably belongs in the [CommunityScripts repo](https://github.com/stashapp/CommunityScripts/) since this has nothing to do with Stash itself

This plugin requires some user configuration: go to `/root/.stash/plugins/community/phashDuplicateTagger` and make a copy of `config_example.py` called simply `config.py`. Open it in a text editor and read it to make sure there are no surprises in there. The error you posted occurs because this `config.py` file does not exist when the plugin is installed

Unfortunately the plugin management UI has no way to display the README for plugins/scrapers and no way to communicate required configuration by users so there's no way you'd know this without asking on Discord or here on Github 😅

**Comment by Plop** [comment]
Thanks a lot ! I looked into the ReadMe of the phash plugin on github, but couldn't find this information. It works fine now, thanks :)
