### ISSUE TITLE
[Bug Report] Excessive reads from Stashes when applying tags

### ISSUE THREAD

**Issue by Trizkat** [stashapp/stash#504]
**Describe the bug**
When adding to tags to videos that lacks the container information, reads are made to the Stashes.
With a large number of selected scenes, activity spikes on the drive.

**To Reproduce**
1. Have an older database without the format table in scenes filled out.
2. Click on Scenes
3. Select all scenes on the page
4. Add a tag to those scenes.
5. Disk activity should now increase.

**Expected behavior**
Expected behavior would be that dealing with tags should only affect R/W where the database is stored I guess.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox
 - Version 75.0

**Additional context**
Rescan the library and the issue disappears.

**Comment by WithoutPants** [comment]
This is happening because `is_streamable` runs ffprobe on each scene if the container isn't set on the scene. Ideally, we would be only getting `is_streamable` when we need to actually stream the scene. At least, we should put some sort of message up indicating that the user needs to rescan their media after upgrading to the relevant version.
