### ISSUE TITLE
Add Play random button to sceneplayer

### ISSUE THREAD

**Issue by matakapo** [stashapp/stash#557]
add a play random button in the `sceneplayer` to change the scene randomly without having to come back to navigate on scene or scene marker

**Comment by velzy00** [comment]
I like this idea a lot. I'd also like the option of a play random button instead of the currently slightly buried menu option.

**Comment by silembir** [comment]
Bumping this feature.  This is something I would really want to see as well.

**Comment by WithoutPants** [comment]
Evaluating design of this for a bounty request:

I think this would be best implemented using #309 instead. Navigating a scene from a scene query would include a playlist view in the scene page, allowing navigation between scenes from the query (including shuffling).

Ideally this would be implemented after we shift to videojs, but it should be easy enough to implement using jwplayer. The original query should be stored by the browser, and this will be used to populate the playlist in the page and in jwplayer. The player itself should have a play next button, and the playlist should be visible on the page. 

The playlist view should be collapsible. My preference is to have it above the scene player, and to make the sprite viewer collapsible (I don't personally see the use in it at all). However, some may prefer a panel to the side, I think like how Google does it. 

Pornhub show it above the video like so:

![image](https://user-images.githubusercontent.com/53250216/109734523-404ede00-7c15-11eb-8557-8e0f7eda2c84.png)

Youtube shows it to the right of the video (we could potentially add it as a tab on the left panel I guess):

![image](https://user-images.githubusercontent.com/53250216/109734585-578dcb80-7c15-11eb-87b8-be19ae438147.png)

Implementation details:
* scene page should have an optional parameter to indicate that playlist should be included.
* we will want event hooks into jwplayer to detect when a video finished to change the current scene to the next in the playlist.
* this should be possible to implement without any backend changes.

To give an indication of effort, if I were to tackle this, I'd be looking at 3 days (24 hours). I believe that someone else may already be working on a similar feature however, so there may be prior work already.

**Comment by silembir** [comment]
Just to clarify, this is my desired use case for the bounty:
I just want a button that is perhaps persistent on the top of Stash (next to the settings icon perhaps) that shuffles my entire library and plays a random video.  The playlist shuffle is also useful but I don't really use playlists.  The button would ideally be accessible from the main page as well as an individual scene page and also possibly triggered by a hotkey.  Currently the only way to play a random scene is the dropdown menu on the main search page and I'm just trying to avoid doing this every time.  Is this what you had in mind?

**Comment by JuliusDorsey** [comment]
Stop

**Comment by WithoutPants** [comment]
> I just want a button that is persistent on the top of Stash (next to the settings icon perhaps) that shuffles my entire library and plays a random video.

I'm hesitant to add another button to the navbar for a reasonably niche function. My proposed alternative use case here is that you would click on scenes, set the filter appropriately (in this case, clear filters), and click the Play Random button. This would play a random scene from the current query, populating a playlist with other scenes from the query. The playlist would also be shuffled when clicking the Play Random button, so the following videos would also be randomised. You would click the play next button to play another random video. This means that you would not need to re-navigate back out to the scenes page to play another random video.

The existing Play Random button is more useful than a top-level "play random scene from my library" button, since it limits what will be played to what's in the current filter. There are other similar use-cases to yours where someone might want to play random scenes featuring a specific performer, for example. 

Putting the Play Random button in the filter bar instead of in the overflow menu is possible, but I'd want it as an option, since the filter bar is crowded enough.

I'd prefer not to add another "play random" button to the scene player page, since it would be superceded by playlist functionality anyway and would otherwise be a pretty limited function.

**Comment by silembir** [comment]
Ah OK, thanks for the clarification.  I was just looking for easier access to the next random video.  I think that solution meets my desired use case.  I'm placing a $25 bounty on this issue or #309 if you think that's more appropriate.

**Comment by WithoutPants** [comment]
Confirmed. $25 bounty on this issue.

**Comment by matakapo** [comment]
can i place 25$ too ?
