### ISSUE TITLE
[Feature] Default filter for "unscrapped" scenes

### ISSUE THREAD

**Issue by Cromseth** [stashapp/stash#569]
After adding some scenes videos and do a scan you have to enter "scenes" tab and play with the filter to get that new (or just unscrapped) scenes you added. Maybe it could be great to add an default button or filter to index that scenes. I don't know if that should be a set of "empy" values (filter conf) or just another variable to scenes at database. Could be interesting?

**Comment by bnkai** [comment]
I just use the filter missing ->  url.  Adding the studio name to the find input also limits down the scenes and helps when scraping for a from a specific site.
Empty values is not a way to know since some fields eg title can be populated during scan if you choose to do so and descriptions might be null even after the scraping since some sites don't use them.

**Comment by bnkai** [comment]
@Cromseth is the url missing and sort by desc date added enough ?
```
http://localhost:9998/scenes?c={%22type%22:%22sceneIsMissing%22,%22value%22:%22url%22,%22modifier%22:%22EQUALS%22}&sortby=created_at&sortdir=desc
```
You could add a bookmark to the above for example
 Can we close this?

**Comment by Cromseth** [comment]
Yep. Thanks.
