### ISSUE TITLE
[Feature] Show thumbnail instead of paused preview when moving mouse away from scene

### ISSUE THREAD

**Issue by Wannabestraight** [stashapp/stash#576]
**Is your feature request related to a problem? Please describe.**
Having animated scene previews is a really cool feature, but can be frustrating when trying to browse to figure out what to watch. 

It gets frustrating when every time you hover your mouse anywhere in the scene window it starts the preview then when removed the preview stops but doesn't revert to showing the assigned thumbnail requiring you to reload the page in order to show it again.

This becomes an issue when a lot of scenes have black fade in's or other intros and your entire scene page is turned to a sea of black in just a few short swipes across the screen when you are trying to organise stuff or just browse what to watch.

**Describe the solution you'd like**
When moving mouse off of the scene preview, revert to showing the assigned thumbnail while still retaining the part of the video you stopped the preview on.
This way your page will always look organised and clean but you still retain the ability to resume the playback of the preview

**Describe alternatives you've considered**
Can't really figure out what benefits the current system has over the suggested one, scene previews are so short and go by fast so its not like you are gonna reorganise the look of your entire scene page temporarily by picking your favourite part of the preview and avoiding moving the mouse to anywhere other then the edges of the screen.
But if the current system is a version some find perfect for them, maybe include a button in settings to switch between showing preview only when hovering and showing preview constantly.

**Comment by WithoutPants** [comment]
I thought there was a fairly easy fix for this issue, but it's unfortunately not so simple.

[This stackoverflow question](https://stackoverflow.com/questions/29462715/video-poster-reset-when-mouseleave-the-div) details the problem. We have a flag that allows resetting the video tag when the mouse leaves the element, but unfortunately there is a noticeable flicker when mousing out because of the video tag reloading the poster. I think the solution is to have two overlapping elements - one for the video and one for the poster image - and show and hide them based on the hover.

**Comment by InfiniteTF** [comment]
@WithoutPants Feel free to assign this to me for v0.4. Should be able to reuse the setup from the wall page.
