### ISSUE TITLE
[Request] Add and display studio without image

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#58]
Please consider adding the following:

1. Ability to create new studio without an image. Studios that do not have an image should just appear as a text link.
2. A toggle override in the settings to display the text studio name everywhere instead of the studio image

What's the use-case for this other than preferring text over a logo? A lot of studios don't have a logo or image representation, such as very small clips 4 sale "studios".

**Comment by StashAppDev** [comment]
Images are required due to how I handle the JSON export.  I needed some type of unique identifier for the studio json filenames which could be mapped back to the studio name string.  The identifier I use is the MD5 hash of the image.

For example:

* Studio A has an image which hashes to 30bcf62db486d0248f5566833074fed3.
* The metadata exports to studios/30bcf62db486d0248f5566833074fed3.json
* in `mappings.json` under the `studios` map I map "Studio A" to `30bcf62db486d0248f5566833074fed3`.  Allowing me to map the correct studio file to the given studio name

This probably isn't ideal, but I haven't had time to circle back and rethink the JSON schema and how this might work.

**Comment by echo6ix** [comment]
Thanks for taking your time to explain how it works.

I don't understand why the identifier cannot be from the MD5 hash of a string value, such as the Studio Name, but I'm sure there's a good reason.

**Comment by Leopere** [comment]
Closed by #109
