### ISSUE TITLE
[Bug Report] XPath Scraper shouldn't remove newlines for Detail fields

### ISSUE THREAD

**Issue by compound-dumbo** [stashapp/stash#591]
**Describe the bug**
Currently, when a scene scraper is run, the resulting Detail field's newlines get removed.

**To Reproduce**
1. Go to the edit tab on a scene
2. Fill in an URL of a scene with a multiline description that has a scraper associated with it
3. Scrape the scene details
4. Profit

**Expected behavior**
Since Detail is presented as a multiline textbox, I would expect newlines to survive.

**Stash Version: v0.1.1-167-gdc5efb9**

**Comment by bnkai** [comment]
This was already mentioned in discord channel and here https://github.com/stashapp/CommunityScrapers/pull/49 . The problem is that the xpath code applies some common postprocessing that removes multiple spaces and newlines for every field. For the details one I think we can skip the line ( "\n" ) removal. 
To complete this the scene details panel in the UI needs the `pre` class defined in the css 
```
.pre { 
white-space: pre-line;
}
```
Was adviced
I had some code that wasn't working as I wanted but I forgot to revisit that, I'll have another look when I can.

**Comment by bnkai** [comment]
related to #579

**Comment by WithoutPants** [comment]
@bnkai is this still a reproducible?

**Comment by bnkai** [comment]
@WithoutPants I wouldn't say reproducible since I don't  have a test sample available but it's not yet 100% resolved. Nodetext function that processes every field still removes newlines. #579 works for newlines that are added by the user or are part of an element attribute but not for newlines that are already processed by the nodeText function

**Comment by WithoutPants** [comment]
Closed as presumably stale. If we're still getting this, we can reopen or open a new issue.

**Comment by feederbox826** [comment]
I'd like to open this back up to discussion as it's a small fix that we can coordinate with CommunityScrapers for a seamless failover **without** regressions in lower versions

**Comment by Gykes** [comment]
My plan was to work through this, and the rest of the existing stuff in the scraper project, once .30 is squared away.
