### ISSUE TITLE
Tagging based on file name

### ISSUE THREAD

**Issue by StashAppDev** [stashapp/stash#6]
https://github.com/stashapp/StashServer/issues/33

**Comment by Leopere** [comment]
Theoretically, a better potential option, in the end, would be a hugely beneficial addition to the world is to have a huge public GraphQL DB for the pursuit of perfection when it comes to tagging data.  

We should consider a simple DB that people can contribute tags to which clearly is far out of scope here but it appears as though this is an issue that comes up constantly around the web.

**Comment by Leopere** [comment]
Something that would be generally agnostic to the data indexed within and store nothing of any copyright issues but just metadata surrounding a database of perceptual fingerprints which I know is difficult when people are constantly remixing the video content, however, we should aim for primarily tagging officially base content then find any scenes that are sectioned out from there.  It Might be a huge undertaking in the long run but if someone would be willing to add this it wouldn't be a terrible contribution to the world in my opinion.

**Comment by WithoutPants** [comment]
With the filename scene parser now merged (#164), I'm looking at extending it to set performers, tags, and studio.

### Approach 1

My current thinking is to support the configuration of a series of rules in the parser. Each rule would consist of a set of conditions and a set of actions to be performed if the conditions are met.

Conditions could be a simple string match (with some smart delimiter removal logic), or use a regex for finer control. I suspect most usage will be met by a single condition, but we could add ANDing and ORing for multiple conditions.

Actions would be one or more of the following, all of which would be performed after conditions are met:
- add performer(s)
- set performers (overwrite logic)
- set studio
- add tag(s)
- set tags

The problem I envision with this approach is that it's soon going to become unwieldy when you have a large amount of performers and studios to match. We don't want to have to a to create 5000 rules to match the performers we have in our database.

This might work well to match studios, since I've noticed that scene releases do often shorten the studio names. It also allows setting tags associated with a given performer or 

### Approach 2

Add `{performer}`, `{studio}`, `{tag}` as fields to the filename parser.
For performer and studio, parser would remove any delimiters from the captured field, perform a search for the resulting performer/studio and set in the results.

I imagine that this approach might be a bit hit and miss. Scene releases that I've come across have the performer name then the title, and it's often hard to distinguish (programatically) between title and performer.

The answer may be to combine the two approaches. Use the latter to perform the coarse grained processing, and rules to handle the corner cases.

I'd welcome feedback and ideas about how this might be implemented.

**Comment by Leopere** [comment]
I think that Approach 1 sounds like a real winner long term when the system becomes more complex however would it make more sense to use Approach 2 in the beginning to master the functionality then open it up to do rules-based implementation at a later time in case we expand the functionality of the application?

**Comment by GernBlanston12** [comment]
Approach 2 would seem the best fit to me, but why do we have to denote fields again? How hard is "search this file name for all these Performer names", and "search this file name for all these tag names", done on scene import or edit of a file name? You could simply disregard spaces out of Tag names and Performers, as well as the file name, and just look for each Performer/Tag/Studio name among the file name string, right? Am I missing something? Even if you have 5000 tags, you're only searching a short-ass file name string with another short-ass tag name, with each one.

**Comment by WithoutPants** [comment]
I like this idea too. Propose the following:
- include an option on save of new performer/studio/tag to search and apply tags to existing scenes based on filename
- add a button to perform the above scan for a specific existing performer/studio/tag
- add task buttons to the tasks settings page to perform the above scans for all performers/studios/tags
- add an option to tag newly scanned scenes with tag/studio/performer based on filename

It's possible that this idea might make the other approaches redudant, but I suppose we can cater for multiple use cases.

**Comment by Leopere** [comment]
Eventually tagging via the filename will likely be deprecated and upgraded to collecting metadata that isn't in the theoretical Stash Meta API.

**Comment by WithoutPants** [comment]
Overlaps with #34
