### ISSUE TITLE
Allow doing AND query in search bar

### ISSUE THREAD

**Issue by victorhooi** [stashapp/stash#612]
The search bar in Stash by default does an OR query.

(For example, searching for "car bus truck", will search for any files with any of those search terms in them).

You can do an AND search for two terms, using the `%` operator - but not three or more. (For example, "car%bus" will search for any files with both "car" and "bus" in them somewhere).

Would it be possible to add some way to search using AND, if required? (either by operator, toggle, menu etc.  - not sure which UX is the right way to expose, but operator seems easiest).

**Comment by JoeSmithStarkers** [comment]
I do wonder why search does "OR" by default. At least from my perspective that doesn't seem like what most users would naturally expect from a search field. 

I believe it's far more common for user to want the intersection of search terms rather than the union, but i'm not 100% clear on the use case for it being "OR" by default. The only use case i can think of is if you have a list of terms that may mean the same thing. eg "bus van".

Based on my uses cases the ideal would be defaulting to "AND" with the ability to specify "OR" eg. "red bus|van" which would return results including ("red" and "bus") and ("red" and "van").

**Comment by seducingbits** [comment]
yep this is weird. i made it a habbit to put the queries in quotes so it acts as an AND.

**Comment by Wannabestraight** [comment]
Oh this explains why using the search was so frustrating when typing one word would bring results somewhat similiar to what i was looking for and then adding a second word completely messed up the search..

**Comment by peolic** [comment]
I add `"` to the start or the end of the query - that seems to make it an AND query.

**Comment by echo6ix** [comment]
I think this is related to the request for a query syntax. See #185

**Comment by kermieisinthehouse** [comment]
This has been fixed in the latest release! You can now manually type 'or' between words to have the old behavior
