### ISSUE TITLE
[Request] Remove deleted scenes from database

### ISSUE THREAD

**Issue by ghost** [stashapp/stash#63]
It would be nice to have a feature which removes deleted scenes (and generated content) from the database, when a scene is deleted. I currently have a few dangling scenes which have an entry in stash but can't be played because they are deleted from the filesystem. I tried to look into it myself but I am not familiar with GQL and GO and don't know where to start.

**Comment by ueaslsef** [comment]
Assuming you are using linux:

Find the checksum of the scene in the ui. Copy it.
Then, open up stash's db with `sqlite3`. If not installed, install it.
```bash
sqlite3 ~/.stash/stash-go.sqlite
```
Then 
```sql
DELETE FROM scenes WHERE checksum LIKE '<CHECKSUM>';
```

**Comment by dotbanana** [comment]
I second this. It would be good if the content stashapp shows is a representation of the content of a specific folder. The "Scan"-Script could do an integrity check basically if all files are still present and if not delete it from database.

**Comment by bnkai** [comment]
I'm pretty sure that the clean button in the tasks section is reserved mainly for that  (when it gets implemented though )

If you wan to delete manually from DB , it's mentioned before  deleting a scene you should delete the relevant entries from tables **scene_markers** and **performers_scenes** because of foreign key constraints.
something like this for example  .... (lets say scene id is 50)

```
DELETE FROM performers_scenes WHERE scene_id = 50;
DELETE FROM scene_markers WHERE scene_id = 50;
DELETE FROM scenes WHERE id = 50 ;

```

**Comment by dotbanana** [comment]
I've written a little bashscript to automate this things with your commands. This works great so far but i stumbled across a strange oddity and i don't know if i am doing something horribly wrong or there is some shennanigans going on:  

These commands only work for me up to scene 352. With a higher id the commands fail. I checked with a sqlite-viewer the stash-go.sqlite and really the listing also there goes only to 352. But my recent videofile showing in stash has id 742. Where is the info saved for these files? I looked across the stash-go.sqlite but couldn't find it. But somehow all the scenes above 352 still show up in the stash-UI and on the startpage it says Scenes 742.
In table sqlite_sequence scenes has value 352.  

My bash-script:  

`#!/bin/bash
# Script needs to be called with number of scene you want to remove
pathtofile=$( sqlite3 ~/.stash/stash-go.sqlite "SELECT path FROM scenes WHERE id = $1;" )
sqlite3 ~/.stash/stash-go.sqlite "DELETE FROM performers_scenes WHERE scene_id = $1;"
sqlite3 ~/.stash/stash-go.sqlite "DELETE FROM scene_markers WHERE scene_id = $1;"
sqlite3 ~/.stash/stash-go.sqlite "DELETE FROM scenes WHERE id = $1;"
rm $pathtofile;`  

When this works my plan is to check the sqlite-db for a specific tag ('delete') and remove the tagged files then from database.

**Comment by bnkai** [comment]
I have 10k files and all of them are in the db file.
Can you check manually with the sqlite3 binary?
e.g.
sqlite3 ~/.stash/stash-go.sqlite
select * from scenes;

**Comment by WithoutPants** [comment]
I may look into this if @StashAppDev doesn't first. 

How does something like this look:

- the scan function marks files that exist in the database but not on the filesystem as "missing". 
- the scan function will also match files marked as "missing" as unmark them if they are found in the filesystem.
- missing scenes do not show in scene queries by default, but you can filter for them.
- specific missing items will be able to be deleted with a button on the scene page (or from the query page once multiselect is implemented)
- all missing items can be deleted with the existing Clean button

I prefer this approach simply because a file not being found may not necessarily be because the user intended the scene to be removed from the database altogether - especially if the file is not found due to a transient issue (like a drive or network location being unavailable). This allows the user to see which files are marked as missing before they run the Clean function. I'd hate to have my ratings/tags/etc wiped out due to this being implemented the wrong way.

**Comment by bnkai** [comment]
I was thinking about it too but it needs changes to the db schema also so i left it for later.
I would create an extra function for the missing file part though as it's more of a reverse scan...
and i was thinking of an extra flag for the scan maybe to mark duplicate,missing files also or even better an extra table to group them together

**Comment by dotbanana** [comment]
> 
> 
> I have 10k files and all of them are in the db file.
> Can you check manually with the sqlite3 binary?
> e.g.
> sqlite3 ~/.stash/stash-go.sqlite
> select * from scenes;

I get a similar output when doing this:

![Unbenannt](https://user-images.githubusercontent.com/22258372/62821721-aed2d380-bb79-11e9-9752-3bde1549368a.png)

Note: I am using this way to populate the database maybe it has something to do with this: 
https://github.com/stashapp/stash/issues/74#issuecomment-512565022  
  
A restart of stash doesn't help. I have frankly no idea where the script is taking its input from this is completely mysterious.

**Comment by echo6ix** [comment]
A clean function should also remove any orphaned transcodes, thumbnails, etc.

**Comment by WithoutPants** [comment]
#146 looks to have addressed this issue and this can probably be closed. @Leopere
