### ISSUE TITLE
cannot generate .wmv sprites and markers

### ISSUE THREAD

**Issue by xiosensei** [stashapp/stash#635]
it seems that .wmv files are not being sprites and markers are not being generated due to an error in ffmpeg

**To Reproduce**
1. use docker container on windows with latest:development version
2. place .wmv files in your data directory
3. scan library
4. check sprites and markers and click generate in the stash settings

**Expected behavior**
no errors. and sprite and marker generation for .wmv files

**Stash Version: (from Settings -> About):**
883a0e7

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: firefox
 - Version: latest

**Additional context**
Error log:
```stash_1 | time="2020-06-25T19:29:03Z" level=info msg="[generator] generating scene preview for /data/sites/video.wmv"

stash_1 | time="2020-06-25T19:29:03Z" level=error msg="ffmpeg error when running command </usr/bin/ffmpeg -v error -xerror -ss 0 -i /data/sites/video.wmv -t 0.75 -max_muxing_queue_size 1024 -y -c:v libx264 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -vf scale=640:-2 -c:a aac -b:a 128k -strict -2 /generated/tmp/preview000.mp4>: [mp4 @ 0x5555565536c0] Non-monotonous DTS in output stream 0:1; previous: 15360, current: 13362; aborting.\n"

stash_1 | time="2020-06-25T19:29:03Z" level=error msg="ffmpeg error when running command </usr/bin/ffmpeg -v error -xerror -ss 266 -i /data/sites/video.wmv -t 0.75 -max_muxing_queue_size 1024 -y -c:v libx264 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -vf scale=640:-2 -c:a aac -b:a 128k -strict -2 /generated/tmp/preview001.mp4>: /data/sites/video.wmv: corrupt decoded frame in stream 1\n"

stash_1 | time="2020-06-25T19:29:03Z" level=error msg="ffmpeg error when running command </usr/bin/ffmpeg -v error -xerror -ss 532 -i /data/sites/video.wmv -t 0.75 -max_muxing_queue_size 1024 -y -c:v libx264 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -vf scale=640:-2 -c:a aac -b:a 128k -strict -2 /generated/tmp/preview002.mp4>: /data/sites/video.wmv: corrupt decoded frame in stream 1\n"

stash_1 | time="2020-06-25T19:29:05Z" level=error msg="ffmpeg error when running command </usr/bin/ffmpeg -v error -xerror -ss 1596 -i /data/sites/video.wmv -t 0.75 -max_muxing_queue_size 1024 -y -c:v libx264 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -vf scale=640:-2 -c:a aac -b:a 128k -strict -2 /generated/tmp/preview006.mp4>: /data/sites/video.wmv: corrupt decoded frame in stream 1\n"

stash_1 | time="2020-06-25T19:29:05Z" level=error msg="ffmpeg error when running command </usr/bin/ffmpeg -v error -xerror -ss 1862 -i /data/sites/video.wmv -t 0.75 -max_muxing_queue_size 1024 -y -c:v libx264 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -vf scale=640:-2 -c:a aac -b:a 128k -strict -2 /generated/tmp/preview007.mp4>: /data/sites/video.wmv: corrupt decoded frame in stream 1\n"

stash_1 | time="2020-06-25T19:29:07Z" level=error msg="ffmpeg error when running command </usr/bin/ffmpeg -v error -xerror -ss 2926 -i /data/sites/video.wmv -t 0.75 -max_muxing_queue_size 1024 -y -c:v libx264 -pix_fmt yuv420p -profile:v high -level 4.2 -preset slow -crf 21 -threads 4 -vf scale=640:-2 -c:a aac -b:a 128k -strict -2 /generated/tmp/preview011.mp4>: /data/sites/video.wmv: corrupt decoded frame in stream 1\n"

stash_1 | time="2020-06-25T19:29:07Z" level=error msg="ffmpeg error when running command </usr/bin/ffmpeg -v error -f concat -i /generated/tmp/files.txt -y -c copy /generated/screenshots/980f24481de546b4e4bec431935b8ba1.mp4>: [mov,mp4,m4a,3gp,3g2,mj2 @ 0x555556a99880] moov atom not found\n[concat @ 0x555556a8e2c0] Impossible to open '/generated/tmp/preview000.mp4'\n/generated/tmp/files.txt: Invalid data found when processing input\n"

time="2020-06-25T19:29:07Z" level=info msg="Generate finished"scene marker 5 of 52> scene marker 1 of 5```

**Comment by xiosensei** [comment]
this is not one files but multiples files. the videos work fine using MPC

**Comment by JoeSmithStarkers** [comment]
Hi @xiosensei,

 i have many wmv files in my library and of the five i checked. None have a problem with preview videos or sprites. 

My guess this is related to specific features of the wmv files in your library. (Most likely variable frame rate).  Is it possible for you extract the videos media info using MediaInfo from [https://mediaarea.net/en/MediaInfo](https://mediaarea.net/en/MediaInfo)

JoeSmithStarkers

**Comment by xiosensei** [comment]
```
General
Complete name               : E:\xxx\data\sites\dogfart.blacksonblondes\blacksonblondes.02.12.26.bridgette.kerkove.wmv
Format                      : Windows Media
File size                   : 328 MiB
Duration                    : 43 min 17 s
Overall bit rate mode       : Constant
Overall bit rate            : 1 061 kb/s
Maximum Overall bit rate    : 1 069 kb/s
Encoded date                : UTC 2005-06-25 19:48:28.310
Copyright                   : www.blacksonblondes.com

Video
ID                          : 1
Format                      : VC-1
Format profile              : MP@ML
Codec ID                    : WMV3
Codec ID/Info               : Windows Media Video 9
Codec ID/Hint               : WMV3
Description of the codec    : Windows Media Video 9 - Professional
Duration                    : 43 min 17 s
Bit rate mode               : Constant
Bit rate                    : 1 009 kb/s
Width                       : 640 pixels
Height                      : 480 pixels
Display aspect ratio        : 4:3
Frame rate                  : 29.970 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Compression mode            : Lossy
Bits/(Pixel*Frame)          : 0.110
Stream size                 : 312 MiB (95%)
Language                    : English (United States)

Audio
ID                          : 2
Format                      : WMA
Format version              : Version 2
Codec ID                    : 161
Codec ID/Info               : Windows Media Audio
Description of the codec    : Windows Media Audio 9.1 -  48 kbps, 32 kHz, stereo 1-pass CBR
Duration                    : 43 min 17 s
Bit rate mode               : Constant
Bit rate                    : 48.0 kb/s
Channel(s)                  : 2 channels
Sampling rate               : 32.0 kHz
Bit depth                   : 16 bits
Stream size                 : 14.9 MiB (5%)
Language                    : English (United States)

```

**Comment by bnkai** [comment]
Problems with specific files will always be present.
Playing through mpc doesn't guarantee that the file is ok.
During scanning if ffmpeg encounters something it doesn't like it errors out quickly. This was decided because otherwise  it would either create problematic files or take too long to encode properly.

If you have a lot of this files i would recommend opening a new request issue for individual ( per scene ) generation of previews. That way we could remove the `-error` ffmpeg option or even add some slower "safer" encoding option.

If you don't have a lot of files or are willing to try manually you can run the ffmpeg commands without the `-xerror` option in the order you see them. If the resulting file is not ok you can also try the lot slower  `/usr/bin/ffmpeg -v error  -i /data/sites/video.wmv -ss 0 -t 0.75 ......`  (the `-ss XX`  option after the `-i`)

From the mediainfo of the file you posted i don't see anything suspicious.

**Comment by JoeSmithStarkers** [comment]
Interesting, I didn't notice the addition of -xerror to ScenePreviewVideoChunk command line. Make sense why quite a few of my files are no longer generating preview. I can confirm most of my wmv files will no longer create previews, 5 in 40 had previews, 3 of which were broken (one, two or three chunks long, but not complete. This could be my changes not detecting if one of the chunks had failed).

It would be a good feature to have an option that fall-backs to slower/unsafe encoding options when an error is detected. This can ether be a default, eg single fallback option. The other is error specific fallbacks, however I think it’s probably best to keep it simple. As handling error specific fallbacks is annoying if there are multiple error types present in a single file.

One of the obvious options would be to use slow seek instead of fast seek. I think that would fix the bulk of broken avi previews (when they distort with a green tint). And the other like you say is to remove -xerror, as a lot of wmv files error out: with “Non-monotonous DTS" but without xerror they produce fine previews.

I also considered the possibility of using the transcoded (if exists) as a source for the preview but for most this isn’t probably practical.

**Comment by rg9400** [comment]
I have this issue with .wmv and .avi files. For .avi, I typically get the below error. Since some indicate a corrupt file, while others are related to the container/codec, Stash would need to parse and differentiate all the various errors. Until then though, it would be nice if the errors could be stored in the DB so that Stash does not try to regenerate previews for them each time unless we force that generation.

I have over 1000 of these types of files, and any time I want to generate new previews, it spends hours trying each of them again.

`[mp3float @ 0000021a354b1500] Header missing`
