### ISSUE TITLE
[Feature] Setting default tagging mode for the multi-scene edit

### ISSUE THREAD

**Issue by Trizkat** [stashapp/stash#645]
**Is your feature request related to a problem? Please describe.**
The multi-scene editor used to default to adding new tags. The new and better looking editor defaults to setting new tags.
The worst thing that could happen went from adding unwanted tags to a scene, to clearing out all the tags I wanted to keep.

**Describe the solution you'd like**
My preferred solution would be if Stash either remembers my last used setting, or the default can be set over on the settings page. 

**Describe alternatives you've considered**
I guess the easier alternative is to revert the behavior. But I'd rather see more options to cater to peoples different ways of using the software.

**Comment by hyde231** [comment]
I see use cases for both behaviors. Wouldn't it be possible to have an option switch in the editor to choose between keeping existing tags and overwriting/overriding?

**Comment by peolic** [comment]
@hyde231 
You can cycle between the modes (set / add / remove) for editing tags/performers by clicking the icon next to the field.

![p](https://user-images.githubusercontent.com/66393006/86199392-af45d580-bb62-11ea-9b62-bceb6a5a62ae.png)

**Comment by seducingbits** [comment]
I agree, a wrongly added tag can easily be reverted. A wrongly set tag on already tagged scenes isnt revertable without a database backup afaik. I would vote to set both, performer and tag options to "add" as default.
When tags or performers are missing, "set" or "add" doesnt make a difference anyways.

**Comment by WithoutPants** [comment]
Yep, I can see a serious usability issue with the current implementation. Having the default as the "Set" action makes sense if your selected scenes all have the same tags/performers since these are populated as such in Set mode. But when they have different values, then the values are left empty, which may cause a mismatch of expectations from the user, with potentially destructive consequences. 

Set is the more potentially destructive mode, and should not be the default in my opinion. This makes setting/overriding existing values a specific mode that the user has to knowingly set, instead of the default.

An alternative would be to set the mode based on the original values - if the values are all the same, default to "Set" with the values prepopulated, otherwise default to "Add". However I think this would be inconsistent behaviour and would serve to confuse and/or annoy the users more than it would help.

Having a default multi-edit mode configuration option would be overkill in my opinion, and remembering the last mode is probably more effort than its worth.
