### ISSUE TITLE
[Feature] Better identical file handling

### ISSUE THREAD

**Issue by WithoutPants** [stashapp/stash#727]
**Is your feature request related to a problem? Please describe.**
If you have identical files in your library, then stash will calculate hashes for the duplicates every time it performs a scan. These files also pollute the log when they are encountered. I think the underlying assumption is that users would remove these files. My use case is that I choose not to remove the duplicates.

Having duplicates causes further issues in that the file path for the duplicate video file is not stored, so if I have two identical files `garbageName.mp4` and `descriptiveName.mp4`, and the former is imported into stash but the latter is detected as a duplicate, then I cannot query on `descriptiveName` since this name is not stored.

**Describe the solution you'd like**
Store additional file paths for each scene. There would continue to be a primary file path, but other paths will be stored when a duplicate is detected. It should be possible to mark a duplicate file path as the new primary path.

**Comment by bnkai** [comment]
If the duplicates get added to the DB there should be a separate section that lists them. A few stats could be useful there also eg total files, filesize etc...
The user that wants to delete them can have a look there instead of searching the log files and the user that wants to keep them can manage them easier.
For duplicate files i think MD5 checksums should be enforced (if a file is duplicate according to oshash->caclulate md5. if its equal ok other wise print error/warning ) . I wouldn't want to remove a file that is "duplicate" according to oshash to only find out later that it was incomplete at some part.

**Comment by InfiniteTF** [comment]
My general opinion is that we should separate files from scenes into their own table, and give them uuids so we don't have to worry about dupe collisions. 

It would make it much easier to implement features like multiple scenes per file, and would make cleaning far less destructive since scenes would merely become orphaned rather than deleted when a file disappears.

It would also solve the duplicate issue since two files with the same hash would both show up as sources for the scene if we join files on scenes by hash. Resolving moved files would continue to work the same way as well, since files are basically just { uuid, hash, path } and would slot right back into the system when cleaned+rescanned.

**Comment by WithoutPants** [comment]
Need to also consider behaviour for when a file is moved if there are multiple candidates to "move" them to.

**Comment by lightSpeedBubble** [comment]
Just to add to the usefulness of that feature: as one may jump between programs (I personally come from MComix and am still undecided), since the databases work differently, the only way to unify categorization of content and not have to do it all over again in each program is to use the filesystem and symlinks for content that is to be put in several categories (e.g. 1 image featuring 2 performers). On top of that, this allows to just use the file explorer of your choice if you want to, and easily find what you're looking for.

**Comment by WithoutPants** [comment]
This is implemented in the files refactor work and can now be closed.
