### ISSUE TITLE
[Feature] Custom scene relationships

### ISSUE THREAD

**Issue by WithoutPants** [stashapp/stash#728]
**Is your feature request related to a problem? Please describe.**
I have a need to relate scenes to each other for some common element. Some examples:
* Scenes with the same anonymous performers (see #235)
* Scenes form a series (where a playlist is not necessarily desired)
* Scenes that are duplicates

**Describe the solution you'd like**
I would like to relate multiple scenes together with a freely defined handle. So using the first example, I might relate scenes `X`, `Y` and `Z` together with the handle `performer`. `Z` might also be related to scenes `A` and `B` with the handle `series`. Navigating to scene `X` would show scenes `Y` and `Z` in a related scenes section, under the heading `performer`. Navigating to scene `Z` would also show `performer` related scenes, but would also have a section `series` showing scenes `A` and `B`.

This would also allow duplicate identification to be made easier by showing related duplicate scenes. 

It should be possible to query for scenes with related scenes of a given handle.

**Comment by bnkai** [comment]
It could be a little more generic also eg taged or named collections. A collection could have galleries, movies or scenes all together related. Instead of adding the movie,gallery from the scene part a new collection can be created and anything from the above added (could be even individual images in the future) including tags eg `duplicate`, `corrupt` , `studio xxxx`.

**Comment by JoeSmithStarkers** [comment]
In essence “performer, movie, studio, tags” are all forms of typed relationships, however when used we create a named set, eg “Alison Rivers”, as the name is important. One functionality that stash is missing, is un-named but typed relationships. As an example duplicate is a type of relationship, and you may have many groups of duplicates which when specified aren’t named. eg Duplicates: [(Scene 1 & 2), (Scence 4 & 5)]
 
Named relationships like tags are easy to create or modify, however un-named typed relationships are easy to create but hard to modify. As a scene maybe in multiple of the same type, eg a scene may appear in multiple unknownPerformer sets. One quick fix is to only allow each type of relationship to be specified for a scene once, but this seems limiting. Creation/modification is easy for automatically created sets like duplicates (eg phashing/checksum matching). However I’m curious how the UI for this would work in the unknownPerformer case. 

I personally think implementing un-named typed relationships isn’t worth while as for most cases humans prefer named sets, eg unknownPerfomer case: “TheBlondWithTheBig___”.

Also related is the concept of tag categories, or parent/child tags. I think rather than trying to implemented un-named typed tags, it maybe better to implement tag categories (whether as a single level concept, or as part of parent/child tags). Parent/child tags can implement tag categories but this may get difficult.

In the duplicate case, this means generating pseudo useless names like “duplicate_123” and “duplicate_124” but these tags live in the category duplicate. Which should have a setting, that allows this set/group/relationship to be known by the category name rather than the tags. Eg when listed in scene playback screen, it should display as “duplicate” rather than “duplicate_1231231212312”. (Additionally be hidden when manually adding)”. 

I prefer the the notion of tag categories with settings that determine the behaviour of that category. Difficult (from a db perspective) would be a tag setting that allows only one of a set of duplicates to be displayed in the search results. Or alternately a tag that could hide content. The tag category could also have a custom colour settings, or a setting that controls whether it displayed in the tagging edit box.

Tags categories also make managing tags easier, as people use tags for many purposes, whether tagging actions/acts or personal favourite lists etc or duplicates. Tagging sources also can be handled, eg automatically tagged from metadata vs manually tagged.

I also like the idea of using “:” as seperator to specific levels of tag, eg “Act:BackRub” or “UnknownPerformer:TheBlondWithTheBig___”.

Just my two cents.

**Comment by JediMaster25** [comment]
Wouldn't scenes having series make movies redundant?

Related to [Link scenes to other related scenes or galleries](https://github.com/stashapp/stash/issues/3201)

**Comment by WithoutPants** [comment]
I think Groups covers this use-case well enough.
