### ISSUE TITLE
[Bug Report] Some scanned files give ParseDateStringAsTime Error but no other information

### ISSUE THREAD

**Issue by sprayidle** [stashapp/stash#731]
During scanning I get the following error on 13 files:
ParseDateStringAsTime failed: dateString <>

There is no other information given so I cannot find the files giving the error. 

Can you make the error give the file path so I can check the files or remove them?

Stash Version: v0.2.1-53-g634b892

**Comment by AdultFunStuff** [comment]
I am encountering the same problem in 0.3.0, and I believe it is preventing me from moving away from md5 hashing in favor of oshash.

On every scan, the following entries are logged:

time="2020-09-13T20:07:59-03:00" level=info msg="Starting scan of 1107 files. 1 New files found"
time="2020-09-13T20:08:01-03:00" level=error msg="ParseDateStringAsTime failed: dateString <>"
time="2020-09-13T20:08:02-03:00" level=info msg="Finished scan"
time="2020-09-13T20:08:02-03:00" level=info msg="Finished gallery association"

The '1 New files found' entry reappears on each scan.
Running version 0.3.0.
The "Set name, date, details from metadata (if present)" option (disabled or enabled) does not change this outcome.

Attempting to set generated file naming hash to oshash gives the error "GraphQL error: some oshash values are missing on scenes. Run Scan to populate" which will not go away, presumably because of the lingering 1 "new" file.

Even with log verbosity set to Debug or Trace, the logs do not indicate which file or path is new and causing the date parsing failure

**Comment by WithoutPants** [comment]
So sorry for being so late to address this. This error looked like a warning that shows up periodically, but does not prevent scanning. Once I knew what to look for, I discovered five of these instances in my own library (of over 23k files). A PR will be going up shortly to address this.

@AdultFunStuff this error should be unrelated to your issue. The presence of new files during scanning should not prevent moving to OSHash. Please raise another issue if you still have this problem.
