### ISSUE TITLE
[Feature] Add support for .cbz files

### ISSUE THREAD

**Issue by Roxxers** [stashapp/stash#768]
The gallery feature of the program supports zip files. .cbz files are zip files that are read by programs to act like comics, manga, etc. This is really handy for hentai storage. 

The program already deals with zip files really easy so it should just be expanding what file extensions the server scans for. It should be able to deal with a cbz file the exact same as a zip file.

You could rename all cbz files to zip but then it becomes a lot harder to view the files outside of the webapp.

Also worth nothing that the cb[x] naming for extensions applies to different archives as well. If you were to add support for tar (cbt), 7zip (cb7), or rar (cbr) then it might be worth adding the comic book version of those files as well.

**Comment by bnkai** [comment]
Cbz support is failrly easy since its a zip file as you stated.

For rar,7z files apart from finding a pure golang library to support them (tar has that ifrom the standard lib) there is an isssue with accessing the files. Tar, rar , 7z need sequential access afaik ( you need to go through the archive till you reach  the wanted file).
While this is not a problem for manga readers as you go through images in sequence one at a time it is a problem for stash. 

The above would make it a very low priority to support said archives imho.
