### ISSUE TITLE
[Feature] Increase Sprite Generator Performance

### ISSUE THREAD

**Issue by PhillipHayes6** [stashapp/stash#920]
**Is your feature request related to a problem? Please describe.**

The sprite generator is not very fast. I think one problem is that ffmpeg is called for every timestamp, adding a lot of overhead.

**Describe the solution you'd like**

Call ffmpeg only once per video

**Describe alternatives you've considered**

I played around with gpu based hardware acceleration, but it does not make any significant difference

**Additional context**

I've build a small prototype which outperforms the current implementation by an order of magnitude, at least on my system.

Extracting a frame from a video takes about 5 seconds on my system, which adds up to about 7 minutes per file. My implementation takes about 40-60 seconds per file.

You can check my code here, just ignore the cuda stuff, I was experimenting with hardware acceleration options for ffmpeg.

https://github.com/PhillipHayes6/stash/commit/d420679118ae7a4c8dc4a466183823a210f70714

Relevant files:

* pkg/ffmpeg/encoder_batch_screenshot.go
* pkg/manager/generator_sprite.go

I'm happy to kick in a PR, but I think it only makes sense after #820 is merged :)

**Comment by JoeSmithStarkers** [comment]
Hi @PhillipHayes6 

I think further investigation and benchmarking is required. I'm curious why one each invocation of ffmpeg is taking 5 seconds on your system, as it is a lot less on mine.

I did a quick test on my dev system (mac osx), generateSpriteImage is the time taken for each complete sprite (all 81 images + gluing them all together to make the sprite). 
generateSpriteImage finished (9.388229243s)
generateSpriteImage finished (12.103144131s) 
generateSpriteImage finished (1m8.745767142s) 
generateSpriteImage finished (13.772193671s) 
generateSpriteImage finished (21.133514504s) 
generateSpriteImage finished (1m16.721998995s) 
generateSpriteImage finished (44.863363556s) 
generateSpriteImage finished (44.143106945s) 
generateSpriteImage finished (44.726799592s) 

As you can see at most it's taking 1 minute 16 seconds on a 40minute long 2160p file. A rough calculation suggests it taking 0.9sec per frame.

The issue i have with the approach you've taken is: using the select filter forces ffmpeg to decode the whole video. The approach we've taken uses fast seeks between each frame. This prevents ffmpeg from decoding the whole video.

The ideal would be the best of both, a single invocation with multiple fast seeks. I did get this working but it took about the same amount of time as the current approach. The issue is ffmpeg is not optimised to handle 81 video inputs (huge memory), or alternatively using a concat source (eg a playlist with seeking specified). (see my concat attempt here: https://pastebin.pl/view/2a24a47c)

(mtn the fastest sprite generator uses libavcodec directly, so it can do the single invocation fast seeks: http://moviethumbnail.sourceforge.net/)

When people talk about hardware encoding sprites / previews, I've always felt that this is probably not a use case that developers of gpu encoders have considered. Eg because if you are encoding a 2 hour movie, who cares if it takes 5+ seconds to initialise the gpu, or 5+ seconds to handle a seek, because for most encoding tasks seeks are never done.

Can you confirm if it takes 5 seconds per frame without any modification, as i wonder if just loading hardware encoding is taking the other 4 seconds?

**Comment by PhillipHayes6** [comment]
Hi @JoeSmithStarkers 

> Can you confirm if it takes 5 seconds per frame without any modification, as i wonder if just loading hardware encoding is taking the other 4 seconds?

I'm on Windows 10, Stash uses multiple Storages. A very slow network drive and local hdds. I only timed the ffmpeg invocation, which seems to be the critical operation:

| Location | Storage   | Filesize | Time Develop  | Time Fork     | Relative Delta |
|----------|-----------|----------|---------------|---------------|----------------|
| a.mkv    | Local HDD | 12.27GB  | 7m59.2610196s | 5m28.0498213s | -46,09%        |
| b.mp4    | Local HDD | 2.8GB    | 8m5.0204883s  | 1m21.7972213s | -492,95%       |
| c.mp4    | Local HDD | 1.12GB   | 7m46.8988701s | 1m22.4971573s | -465,96%       |
| d.mp4    | Network   | 2.13GB   | 8m15.3692214s | 3m1.9291038s  | -172,29%       |
| e.mov    | Network   | 4.67GB   | 8m12.4674112s | 7m5.183572s   | -15,82%        |

So I don't think its related to the hardware acceleration.

> When people talk about hardware encoding sprites / previews, I've always felt that this is probably not a use case that developers of gpu encoders have considered. Eg because if you are encoding a 2 hour movie, who cares if it takes 5+ seconds to initialise the gpu, or 5+ seconds to handle a seek, because for most encoding tasks seeks are never done.

I agree, but spawning 81 ffmpeg processes also seems not the ideal solution. I mean there must be some IO overhead there. But maybee it a windows related ffmpeg problem. I'll look further into it.

ffmpeg Info
````
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 10.2.1 (GCC) 20200726
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
````

Hardware:

AMD Ryzen 7 3700X 8-Core
32 GB RAM
Nvidia GeForce RTX 2070 Super

**Comment by JoeSmithStarkers** [comment]
> ... but spawning 81 ffmpeg processes also seems not the ideal solution. I mean there must be some IO overhead there. But maybee it a windows related ffmpeg problem. I'll look further into it.

I agree. When I first saw how stash did previews/sprites I thought that can't be efficient. But the ffmpeg.exe will stay resident in memory between calls, and most of the important parts of the media file will be cached by the operating system. So overall it did better than I expected. (Decoding tens of thousands of frames (108k@30fps for one hour) when you only want 81 of them isn't that efficient ether, so compared to starting up ffmpeg 81 times doesn't seem that bad)

Are you running windows defender by any chance? Could you disable it for another test? I just wonder if windows defender is doing a scan on exe load or something. This issue is worth looking into as many stash users are windows users.

Note: we both running the same versions of ffmpeg but i'm on intel mac osx.

**Comment by PhillipHayes6** [comment]
> Are you running windows defender by any chance? Could you disable it for another test? I just wonder if windows defender is doing a scan on exe load or something. This issue is worth looking into as many stash users are windows users.

Nailed it! It wasn't the windows defender, but my lovely ~Adware~ Antivirus "AVG AntiVirus Free". I disabled it and the sprite generation speed is now similar to yours.

Thanks for pointing me in that direction!

**Comment by JoeSmithStarkers** [comment]
Glad you found the issue :) Also happy you investigated it and proposed a different solution.

Maybe worth putting in an automated check to see ffmpeg/ffprobe startup is overly slow. Should usually be less than 1-2 seconds, but might be worth printing a warning in the log files if it takes more.

**Comment by kermieisinthehouse** [comment]
I believe a single ffmpeg call implementation was researched and was slower. The current solution is fast as ffmpeg will live in page cache during generation.
