### ISSUE TITLE
GIF/Short Loop Image Support

### ISSUE THREAD

**Issue by yoshnopa** [stashapp/stash#926]
**Is your feature request related to a problem? Please describe.**
I am not sure if this is in your current design philosophy, but many image pages support the upload of small video snippets, commonly called gif, but rarely actually being in the format of .gif, but most likely mp4 or webm. For an entire page of NSFW examples, see [redgifs.com](https://www.redgifs.com/), but also all image boorus, pornhub, and many more. Those loops are short (most likely less than a minute, always less than two), and are made for looping by default. 
My request is adding support for such videos in the galleries and images view. This could be done by looking at a scan with image only and make all found videos to such a gif entry. As this may break some setups, an additional checkbox might be used, left unchecked by default, or a third option besides scenes and images. It would also mean some kind of viewing in the carousel if possible.

**Comment by Hoowah** [comment]
I strongly agree with this.

There was a related suggestion to this issue, requesting that short clips have their own section to resolve them cluttering the scenes section.

https://github.com/stashapp/stash/issues/671

But I also agree with @Withoutpants :

> "I think if we're to consider something like this, then it should have a distinct set of features that can't be met by the scenes subsystem."

And that this would be an answer, but it needs to be proven that the image subsystem fits short clips better than the scene subsystem.

Reasons I think short clips are more compatible with images:

- Short clips in some contexts are the successor to gif.

- Short clips from social media are often displayed in the same environment as images, with a better user experience if they autoplay.

- Short clips are easy to view in a collage because of their short length.

- Short clips often use portrait aspect ratios, which fit well in a collage where images (or other short clips) occupy otherwise empty horizontal space.

Reasons I think short clips are less compatible with scenes:

- I don't think there's anything you can do to make the scene page layout, or any 16:9 screen displaying a single vertical video, elegant.

- Portrait aspect ratios are also an aesthetic problem for scene cards and wall previews, though I'd rather see that fixed than use it as an argument here.

- For scenes, you browse with previews, select a preview and go to new page to watch the content. This isn't expedient to just see a short clip.

- The film strip isn't useful and wastes vertical space. Easily fixable by removing it for short clips, but the point I'm making is that you're changing the scene page to accommodate short clips and that should be weighed against changing the images system instead.

- Markers aren't useful for short clips either.

- I think the fact that an answer to issue 671 was to one day have better filtering options is telling. There's a clear necessity for users to separate encounters with short clips and full scenes. If it's also a fact that there's a general desire for users to combine encounters with short clips and images, its obvious where short clips belong.

As for organization, the best solution I can think of is a cut-off duration for what is categorized as a short clip or a scene, with maybe more leeway for vertical videos? I hope that would be satisfactory. I don't think it's a good idea to depend on a particular organization scheme from the user and that stores short clips and scenes in separate directories with separate rules. You could allow that, but the whole idea is more robust if that wasn't needed.

I also think there are times where a user will want to find short clips when using the scene search, but I can't write about every detail before I know how much traction this will actually get.

If anyone is interested is seeing how short clips and images work together in collage format, I recommend looking at scrolller.com and imagine it if bandwidth wasn't an issue.

**Comment by secondfolder** [comment]
I think @Hoowah's very detailed answer covers things well (also thanks for introducing me to https://scrolller.com/, very cool). I do however want to propose a third option to the question of whether clips fit more in the Scenes view or the Image view. What about a third view called "Media" or something that combines entities from both? https://github.com/stashapp/stash/issues/1030 This would help solve the issue of gifs and video clips being technically different but can conceptually be very similar as far as the user viewing them is concerned.
