### ISSUE TITLE
[Feature] Settings options: User-defined default sortby & filter parameters

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#956]
Let the user specify somewhere in the settings page -- likely the interface section -- the default _sortby_ and _filter_ parameters for each section of stash.

Eg.
_Section_: scenes
_Sortby_ parameters: created_at&sortdir=desc
_Filter_ parameters:

_Section_: performers
_Sortby_ parameters: sortby=birthdate
_Filter_ parameters: {"type":"gender","value":"Female","modifier":"EQUALS"}

**Comment by InfiniteTF** [comment]
I think this should be implemented as part of user definable filters described in #671. When you apply a filter or change sorting you'll get an option to save that as a shortcut. If the user chooses they can then save the filter as default rather than naming it. This avoids having to add a whole filter configuration component to the config page which is already overloaded.

**Comment by peolic** [comment]
This is now possible as of v0.8.0 using [saved filters](https://github.com/stashapp/stash/pull/1474) ("Set as default" option).
